export { ChatWidget } from './components/ChatWidget'
export { default as ChatPopup } from './components/ChatPopup'
export { ChatIcon } from './components/ChatIcon'
export { ChatBubble } from './components/ChatBubble'
export { QuickActions } from './components/QuickActions'
export { ProactiveMessagePreview } from './components/ProactiveMessagePreview'
export { NotificationCenter } from './components/NotificationCenter'
export { TutorAvatar } from './components/TutorAvatar'
export { MissingKeyBanner } from './components/MissingKeyBanner'
export { TypingIndicator } from './components/TypingIndicator'
export { WelcomeState } from './components/WelcomeState'
export { ChatStyles } from './components/ChatStyles'
export { useExitAnimation } from './components/useExitAnimation'
export { ContextSuggestionCard } from './components/ContextSuggestionCard'

export { useProactiveMessages, DEFAULT_QUICK_ACTIONS, ACTION_LABELS, PROACTIVE_CATEGORY_LABELS, PROACTIVE_PRIORITY_LABELS } from './hooks/useProactiveMessages'
export { useChatWidget } from './hooks/useChatWidget'

export { MessageStorage } from './services/messageStorage'
export { ProactiveMessageService } from './services/proactiveMessageService'
export { ProactiveEventBus } from './services/proactiveEventBus'
export { generateProactiveMessages, generateContextSuggestions } from './services/proactiveMessageEngine'
export type { ProactiveEngineInput, LearnerProfile } from './services/proactiveMessageEngine'

export { getContextSuggestions, getContextAwareQuickActions } from './utils/contextSuggestions'

export type * from './types'
export type * from './schemas/chat'
