import { z } from 'zod'

export const isoString = z.string().refine(v => !isNaN(Date.parse(v)), { message: 'Invalid ISO date' })

export const transcriptLanguageSchema = z.string().min(1)

export const transcriptSourceSchema = z.enum(['manual', 'auto-generated', 'unknown'])

export const cefrLevelSchema = z.enum(['A1', 'A2', 'B1', 'B2', 'C1', 'C2', 'unknown'])

export const ieltsBandRangeSchema = z.enum(['0-4.0', '4.0-5.0', '5.0-6.0', '6.0-7.0', '7.0-8.0', '8.0-9.0', 'unknown'])

export const accentSchema = z.enum([
  'american', 'british', 'australian', 'canadian', 'indian',
  'irish', 'scottish', 'south-african', 'non-native', 'unknown',
])

export const difficultyLevelSchema = z.enum(['beginner', 'intermediate', 'upper-intermediate', 'advanced', 'unknown'])

export const noteCategorySchema = z.enum([
  'vocabulary', 'grammar', 'listening', 'speaking-idea',
  'writing-idea', 'important-fact', 'personal-note',
])

export const exerciseTypeSchema = z.enum([
  'fill-blanks', 'multiple-choice', 'true-false-not-given',
  'vocabulary-matching', 'sentence-completion', 'summary-completion',
  'listening-comprehension', 'dictation', 'shadowing',
  'speaking-response', 'summary-challenge',
])

export const studyActivityTypeSchema = z.enum([
  'learning-mode-started', 'learning-mode-ended',
  'word-opened', 'word-saved', 'sentence-saved',
  'note-created', 'note-edited', 'note-deleted',
  'exercise-started', 'exercise-completed',
  'dictation-attempt', 'shadowing-attempt',
  'speaking-attempt', 'summary-submitted',
  'transcript-segment-replayed',
  'video-analysis-completed',
  'tutor-intervention',
  'study-session-completed',
  'playlist-created', 'playlist-video-added',
])

export const playlistStatusSchema = z.enum(['planned', 'in-progress', 'completed'])

export const reviewFormatSchema = z.enum([
  'meaning-to-word', 'word-to-meaning',
  'fill-in-subtitle', 'listen-and-type',
  'audio-to-sentence', 'explain-sentence',
  'speak-using-word', 'return-to-timestamp',
])

export const vocabDifficultySchema = z.enum(['easy', 'medium', 'hard', 'unknown'])

export const youtubeVideoSchema = z.object({
  id: z.string().min(1),
  videoId: z.string().min(1),
  title: z.string().default(''),
  channelName: z.string().default(''),
  channelUrl: z.string().default(''),
  duration: z.number().default(0),
  thumbnailUrl: z.string().default(''),
  description: z.string().default(''),
  tags: z.array(z.string()).default([]),
  transcriptLanguage: transcriptLanguageSchema.default(''),
  transcriptSource: transcriptSourceSchema.default('unknown'),
  cefrLevel: cefrLevelSchema.default('unknown'),
  ieltsLevel: ieltsBandRangeSchema.default('unknown'),
  speakingSpeed: z.number().default(0),
  accent: accentSchema.default('unknown'),
  topicCategories: z.array(z.string()).default([]),
  advancedWordCount: z.number().default(0),
  recommendedLevel: difficultyLevelSchema.default('unknown'),
  mainChallenges: z.array(z.string()).default([]),
  estimatedStudyMinutes: z.number().default(0),
  analysisVersion: z.string().default(''),
  analysisTranscriptHash: z.string().default(''),
  subtitleAvailability: z.enum(['available', 'auto-generated', 'none', 'unknown']).default('unknown'),
  createdAt: isoString,
  updatedAt: isoString,
})

export const transcriptSegmentSchema = z.object({
  id: z.string().min(1),
  videoId: z.string().min(1),
  start: z.number().min(0),
  end: z.number().min(0),
  text: z.string().min(1),
  language: transcriptLanguageSchema.default('en'),
  source: transcriptSourceSchema.default('unknown'),
  words: z.array(z.object({
    word: z.string(),
    start: z.number(),
    end: z.number(),
  })).default([]),
  isAutoGenerated: z.boolean().default(false),
})

export const transcriptSchema = z.object({
  id: z.string().min(1),
  videoId: z.string().min(1),
  language: transcriptLanguageSchema.default('en'),
  source: transcriptSourceSchema.default('unknown'),
  segments: z.array(transcriptSegmentSchema).default([]),
  contentHash: z.string().default(''),
  fullText: z.string().default(''),
  wordCount: z.number().default(0),
  fetchedAt: isoString,
})

export const videoAnalysisSchema = z.object({
  id: z.string().min(1),
  videoId: z.string().min(1),
  transcriptHash: z.string().default(''),
  cefrLevel: cefrLevelSchema.default('unknown'),
  ieltsLevel: ieltsBandRangeSchema.default('unknown'),
  speakingSpeed: z.number().default(0),
  topicCategories: z.array(z.string()).default([]),
  accent: accentSchema.default('unknown'),
  advancedWordCount: z.number().default(0),
  recommendedLevel: difficultyLevelSchema.default('unknown'),
  mainChallenges: z.array(z.string()).default([]),
  estimatedStudyMinutes: z.number().default(0),
  analysisVersion: z.string().default('1.0'),
  isAIEstimated: z.boolean().default(false),
  createdAt: isoString,
})

export const videoVocabularySourceSchema = z.object({
  id: z.string().min(1),
  vocabularyId: z.string().min(1),
  videoId: z.string().min(1),
  timestamp: z.number().default(0),
  sentence: z.string().default(''),
  transcriptSegmentId: z.string().default(''),
  sourceCreatedAt: isoString,
})

export const savedSentenceSchema = z.object({
  id: z.string().min(1),
  videoId: z.string().min(1),
  text: z.string().min(1),
  startTimestamp: z.number().default(0),
  endTimestamp: z.number().default(0),
  videoTitle: z.string().default(''),
  videoUrl: z.string().default(''),
  transcriptLanguage: transcriptLanguageSchema.default('en'),
  selectedVocabulary: z.array(z.string()).default([]),
  userNote: z.string().default(''),
  tags: z.array(z.string()).default([]),
  isFavorite: z.boolean().default(false),
  createdAt: isoString,
  updatedAt: isoString,
})

export const timestampedNoteSchema = z.object({
  id: z.string().min(1),
  videoId: z.string().min(1),
  text: z.string().min(1),
  timestamp: z.number().default(0),
  transcriptSegmentId: z.string().default(''),
  transcriptText: z.string().default(''),
  category: noteCategorySchema.default('personal-note'),
  tags: z.array(z.string()).default([]),
  videoTitle: z.string().default(''),
  videoUrl: z.string().default(''),
  isFavorite: z.boolean().default(false),
  createdAt: isoString,
  updatedAt: isoString,
})

export const learningPlaylistSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  description: z.string().default(''),
  playlistType: z.enum([
    'ielts-listening', 'technology', 'environment', 'education',
    'british-english', 'american-english', 'interview-practice',
    'academic-vocabulary', 'custom',
  ]).default('custom'),
  videoIds: z.array(z.string()).default([]),
  goal: z.string().default(''),
  status: playlistStatusSchema.default('planned'),
  isFavorite: z.boolean().default(false),
  createdAt: isoString,
  updatedAt: isoString,
})

export const playlistItemSchema = z.object({
  id: z.string().min(1),
  playlistId: z.string().min(1),
  videoId: z.string().min(1),
  sortOrder: z.number().default(0),
  personalNote: z.string().default(''),
  status: playlistStatusSchema.default('planned'),
  addedAt: isoString,
})

export const videoStudySessionSchema = z.object({
  id: z.string().min(1),
  videoId: z.string().min(1),
  startTime: isoString,
  endTime: isoString.optional(),
  activeStudyDuration: z.number().default(0),
  watchDuration: z.number().default(0),
  wordsViewed: z.number().default(0),
  wordsSaved: z.number().default(0),
  sentencesSaved: z.number().default(0),
  notesCreated: z.number().default(0),
  exercisesAttempted: z.number().default(0),
  exerciseScores: z.array(z.object({
    exerciseId: z.string(),
    type: exerciseTypeSchema,
    score: z.number(),
    total: z.number(),
  })).default([]),
  dictationAccuracy: z.number().default(0),
  speakingAttempts: z.number().default(0),
  shadowingAttempts: z.number().default(0),
  summaryAttempts: z.number().default(0),
  tutorInterventions: z.number().default(0),
  isCompleted: z.boolean().default(false),
  createdAt: isoString,
  updatedAt: isoString,
})

export const studyActivitySchema = z.object({
  id: z.string().min(1),
  sessionId: z.string().min(1),
  videoId: z.string().min(1),
  activityType: studyActivityTypeSchema,
  metadata: z.record(z.string(), z.unknown()).default({}),
  timestamp: isoString,
})

export const exerciseSchema = z.object({
  id: z.string().min(1),
  videoId: z.string().min(1),
  type: exerciseTypeSchema,
  instructions: z.string().default(''),
  sourceSegments: z.array(z.string()).default([]),
  transcriptHash: z.string().default(''),
  difficulty: difficultyLevelSchema.default('intermediate'),
  questions: z.array(z.union([
    z.object({
      id: z.string(),
      type: z.literal('fill-blanks'),
      text: z.string(),
      blanks: z.array(z.string()),
      correctAnswers: z.array(z.string()),
      explanation: z.string().default(''),
    }),
    z.object({
      id: z.string(),
      type: z.literal('multiple-choice'),
      question: z.string(),
      options: z.array(z.string()),
      correctAnswer: z.number(),
      explanation: z.string().default(''),
    }),
    z.object({
      id: z.string(),
      type: z.literal('true-false-not-given'),
      statement: z.string(),
      correctAnswer: z.enum(['true', 'false', 'not-given']),
      explanation: z.string().default(''),
    }),
    z.object({
      id: z.string(),
      type: z.literal('vocabulary-matching'),
      prompt: z.string(),
      items: z.array(z.string()),
      definitions: z.array(z.string()),
      correctMatches: z.record(z.string(), z.number()),
      explanation: z.string().default(''),
    }),
    z.object({
      id: z.string(),
      type: z.literal('sentence-completion'),
      question: z.string(),
      correctAnswer: z.string(),
      acceptableAnswers: z.array(z.string()).default([]),
      explanation: z.string().default(''),
    }),
    z.object({
      id: z.string(),
      type: z.literal('dictation'),
      sentence: z.string(),
      startTimestamp: z.number(),
      hints: z.array(z.string()).default([]),
    }),
    z.object({
      id: z.string(),
      type: z.literal('speaking-response'),
      prompt: z.string(),
      preparationTime: z.number().default(30),
      responseTime: z.number().default(60),
      part: z.union([z.literal(1), z.literal(2), z.literal(3)]).default(1),
    }),
  ])).default([]),
  score: z.number().default(0),
  totalQuestions: z.number().default(0),
  isCompleted: z.boolean().default(false),
  attemptHistory: z.array(z.object({
    attemptId: z.string(),
    score: z.number(),
    total: z.number(),
    timestamp: isoString,
  })).default([]),
  generationSource: z.enum(['ai', 'deterministic']).default('deterministic'),
  generationOptions: z.string().default('{}'),
  createdAt: isoString,
  updatedAt: isoString,
})

export const exerciseAttemptSchema = z.object({
  id: z.string().min(1),
  exerciseId: z.string().min(1),
  videoId: z.string().min(1),
  answers: z.record(z.string(), z.unknown()).default({}),
  score: z.number().default(0),
  total: z.number().default(0),
  accuracy: z.number().default(0),
  timeSpentSeconds: z.number().default(0),
  mistakes: z.array(z.object({
    questionId: z.string(),
    question: z.string(),
    userAnswer: z.string(),
    correctAnswer: z.string(),
    explanation: z.string().default(''),
  })).default([]),
  createdAt: isoString,
})

export const dictationAttemptSchema = z.object({
  id: z.string().min(1),
  videoId: z.string().min(1),
  sentence: z.string().min(1),
  userInput: z.string().default(''),
  normalizedUserInput: z.string().default(''),
  normalizedCorrect: z.string().default(''),
  startTimestamp: z.number().default(0),
  endTimestamp: z.number().default(0),
  accuracy: z.number().default(0),
  insertedWords: z.array(z.string()).default([]),
  missingWords: z.array(z.string()).default([]),
  incorrectWords: z.array(z.object({
    expected: z.string(),
    received: z.string(),
  })).default([]),
  hintsUsed: z.number().default(0),
  replayCount: z.number().default(0),
  timeSpentSeconds: z.number().default(0),
  isDifficult: z.boolean().default(false),
  createdAt: isoString,
})

export const shadowingAttemptSchema = z.object({
  id: z.string().min(1),
  videoId: z.string().min(1),
  sentence: z.string().min(1),
  startTimestamp: z.number().default(0),
  endTimestamp: z.number().default(0),
  recordingRef: z.string().default(''),
  recordingDuration: z.number().default(0),
  playbackSpeed: z.number().default(1),
  userRating: z.number().default(0),
  aiFeedback: z.string().default(''),
  aiScore: z.number().default(0),
  notes: z.string().default(''),
  createdAt: isoString,
})

export const speakingAttemptSchema = z.object({
  id: z.string().min(1),
  videoId: z.string().min(1),
  prompt: z.string().min(1),
  part: z.union([z.literal(1), z.literal(2), z.literal(3)]).default(1),
  recordingRef: z.string().default(''),
  recordingDuration: z.number().default(0),
  preparationTime: z.number().default(0),
  responseText: z.string().default(''),
  fluencyScore: z.number().default(0),
  vocabularyScore: z.number().default(0),
  grammarScore: z.number().default(0),
  pronunciationScore: z.number().default(0),
  relevanceScore: z.number().default(0),
  coherenceScore: z.number().default(0),
  estimatedBand: z.number().default(0),
  rubricVersion: z.string().default('1.0'),
  feedback: z.string().default(''),
  suggestedImprovements: z.array(z.string()).default([]),
  isEvaluated: z.boolean().default(false),
  createdAt: isoString,
})

export const summaryAttemptSchema = z.object({
  id: z.string().min(1),
  videoId: z.string().min(1),
  summaryType: z.enum([
    'one-sentence', 'fifty-word', 'own-words',
    'opinion', 'writing-task2-ideas', 'short-speaking',
  ]).default('own-words'),
  userAnswer: z.string().default(''),
  aiReview: z.string().default(''),
  aiScore: z.number().default(0),
  missingKeyIdeas: z.array(z.string()).default([]),
  incorrectInterpretations: z.array(z.string()).default([]),
  vocabularyImprovements: z.array(z.string()).default([]),
  grammarIssues: z.array(z.string()).default([]),
  coherenceIssues: z.array(z.string()).default([]),
  betterExpression: z.string().default(''),
  modelResponse: z.string().default(''),
  isReviewed: z.boolean().default(false),
  createdAt: isoString,
})

export const tutorInterventionSchema = z.object({
  id: z.string().min(1),
  sessionId: z.string().min(1),
  videoId: z.string().min(1),
  triggerEvent: studyActivityTypeSchema,
  message: z.string().min(1),
  priority: z.enum(['low', 'medium', 'high']).default('medium'),
  action: z.string().default(''),
  isDismissed: z.boolean().default(false),
  createdAt: isoString,
})

export const aiGenerationCacheSchema = z.object({
  id: z.string().min(1),
  cacheKey: z.string().min(1),
  videoId: z.string().min(1),
  cacheType: z.enum([
    'analysis', 'vocabulary', 'exercises', 'grammar',
    'summary', 'speaking-feedback', 'channel-evaluation',
  ]).default('analysis'),
  contentHash: z.string().default(''),
  response: z.string().min(1),
  model: z.string().default(''),
  tokensUsed: z.number().default(0),
  createdAt: isoString,
  expiresAt: isoString,
})

export const channelEvaluationSchema = z.object({
  id: z.string().min(1),
  channelId: z.string().min(1),
  channelName: z.string().default(''),
  subtitleAvailability: z.enum(['high', 'medium', 'low', 'unknown']).default('unknown'),
  typicalSpeakingSpeed: z.number().default(0),
  commonTopics: z.array(z.string()).default([]),
  estimatedLevel: difficultyLevelSchema.default('unknown'),
  averageVideoDuration: z.number().default(0),
  ieltsRelevance: z.enum(['high', 'medium', 'low', 'unknown']).default('unknown'),
  recommendedUseCases: z.array(z.string()).default([]),
  videosAnalyzed: z.number().default(0),
  lastAnalyzedAt: isoString,
  createdAt: isoString,
})

export type YouTubeVideo = z.infer<typeof youtubeVideoSchema>
export type Transcript = z.infer<typeof transcriptSchema>
export type TranscriptSegment = z.infer<typeof transcriptSegmentSchema>
export type VideoAnalysis = z.infer<typeof videoAnalysisSchema>
export type VideoVocabularySource = z.infer<typeof videoVocabularySourceSchema>
export type SavedSentence = z.infer<typeof savedSentenceSchema>
export type TimestampedNote = z.infer<typeof timestampedNoteSchema>
export type LearningPlaylist = z.infer<typeof learningPlaylistSchema>
export type PlaylistItem = z.infer<typeof playlistItemSchema>
export type VideoStudySession = z.infer<typeof videoStudySessionSchema>
export type StudyActivity = z.infer<typeof studyActivitySchema>
export type Exercise = z.infer<typeof exerciseSchema>
export type ExerciseAttempt = z.infer<typeof exerciseAttemptSchema>
export type DictationAttempt = z.infer<typeof dictationAttemptSchema>
export type ShadowingAttempt = z.infer<typeof shadowingAttemptSchema>
export type SpeakingAttempt = z.infer<typeof speakingAttemptSchema>
export type SummaryAttempt = z.infer<typeof summaryAttemptSchema>
export type TutorIntervention = z.infer<typeof tutorInterventionSchema>
export type AIGenerationCache = z.infer<typeof aiGenerationCacheSchema>
export type ChannelEvaluation = z.infer<typeof channelEvaluationSchema>
