export { createCollocation } from './Collocation'
export type { Collocation, Register } from './Collocation'
export { createSynonym } from './Synonym'
export type { Synonym } from './Synonym'
export { createAntonym } from './Antonym'
export type { Antonym, AntonymType } from './Antonym'
export { createWordFamilyMember } from './WordFamilyMember'
export type { WordFamilyMember, PartOfSpeech, VerbConjugation } from './WordFamilyMember'
export { createCommonMistake } from './CommonMistake'
export type { CommonMistake, CommonMistakeType } from './CommonMistake'
export { createUsageExample } from './UsageExample'
export type { UsageExample, UsageExampleSource } from './UsageExample'
export { createInflection } from './Inflection'
export type { Inflection, InflectionType } from './Inflection'
export { createWordConnection } from './WordConnection'
export type { WordConnection } from './WordConnection'
export { createTopicCluster } from './TopicCluster'
export type { TopicCluster } from './TopicCluster'
