import type { UsefulPhrase } from '@ielts/storage'

const now = '2025-01-01T00:00:00.000Z'

export const USEFUL_PHRASES_PACK_ID = 'useful-phrases-v1'

export const BUILT_IN_USEFUL_PHRASES: UsefulPhrase[] = [
  {
    id: 'built-in-phrase-writing-1',
    phrase: 'It is widely believed that...',
    meaning: 'Many people think that...',
    usageExample: 'It is widely believed that education is the key to success.',
    topic: 'Writing',
    skill: 'writing',
    tags: ['essay', 'opinion'],
    difficulty: 'medium',
    isFavorite: false,
    status: 'new',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'built-in-phrase-writing-2',
    phrase: 'This essay will discuss both perspectives before presenting my own view.',
    meaning: 'A sentence used to outline the structure of a discussion essay.',
    usageExample: 'This essay will discuss both perspectives before presenting my own view.',
    topic: 'Writing',
    skill: 'writing',
    tags: ['essay', 'structure'],
    difficulty: 'medium',
    isFavorite: false,
    status: 'new',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'built-in-phrase-writing-3',
    phrase: 'On the one hand... On the other hand...',
    meaning: 'Used to present two contrasting viewpoints.',
    usageExample: 'On the one hand, technology has made communication easier. On the other hand, it has reduced face-to-face interaction.',
    topic: 'Writing',
    skill: 'writing',
    tags: ['essay', 'contrast'],
    difficulty: 'easy',
    isFavorite: false,
    status: 'new',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'built-in-phrase-speaking-1',
    phrase: 'In my opinion, I would say that...',
    meaning: 'A polite way to express your opinion.',
    usageExample: 'In my opinion, I would say that the government should invest more in public transport.',
    topic: 'Speaking',
    skill: 'speaking',
    tags: ['speaking', 'opinion'],
    difficulty: 'easy',
    isFavorite: false,
    status: 'new',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'built-in-phrase-speaking-2',
    phrase: 'That is an interesting question. Let me think about it for a moment.',
    meaning: 'A phrase to buy time while thinking of an answer.',
    usageExample: 'That is an interesting question. Let me think about it for a moment.',
    topic: 'Speaking',
    skill: 'speaking',
    tags: ['speaking', 'strategy'],
    difficulty: 'easy',
    isFavorite: false,
    status: 'new',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'built-in-phrase-academic-1',
    phrase: 'There is a growing body of evidence that suggests...',
    meaning: 'Used to introduce research or data supporting an argument.',
    usageExample: 'There is a growing body of evidence that suggests climate change is accelerating.',
    topic: 'Academic',
    skill: 'writing',
    tags: ['academic', 'evidence'],
    difficulty: 'hard',
    isFavorite: false,
    status: 'new',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'built-in-phrase-academic-2',
    phrase: 'This is particularly significant because...',
    meaning: 'Used to emphasize the importance of a point.',
    usageExample: 'This is particularly significant because it affects millions of people worldwide.',
    topic: 'Academic',
    skill: 'writing',
    tags: ['academic', 'emphasis'],
    difficulty: 'medium',
    isFavorite: false,
    status: 'new',
    createdAt: now,
    updatedAt: now,
  },
]
