import type { SpeakingQuestion } from '@ielts/storage'

const now = '2025-01-01T00:00:00.000Z'

export const SPEAKING_QUESTIONS_PACK_ID = 'speaking-questions-v1'

export const BUILT_IN_SPEAKING_QUESTIONS: SpeakingQuestion[] = [
  {
    id: 'built-in-speaking-p1-travel-1',
    part: 1,
    question: 'Do you like to travel? Why or why not?',
    topic: 'Travel',
    followUpQuestions: [],
    tags: ['travel', 'personal', 'hobbies'],
    difficulty: 'easy',
    isFavorite: false,
    status: 'new',
    isDone: false,
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'built-in-speaking-p1-work-1',
    part: 1,
    question: 'What do you do? Do you study or work?',
    topic: 'Work',
    followUpQuestions: [],
    tags: ['work', 'study', 'personal'],
    difficulty: 'easy',
    isFavorite: false,
    status: 'new',
    isDone: false,
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'built-in-speaking-p1-technology-1',
    part: 1,
    question: 'How often do you use the internet? What do you usually do online?',
    topic: 'Technology',
    followUpQuestions: [],
    tags: ['technology', 'internet', 'daily-life'],
    difficulty: 'easy',
    isFavorite: false,
    status: 'new',
    isDone: false,
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'built-in-speaking-p2-technology-1',
    part: 2,
    question: 'Describe a piece of technology that you find useful. You should say: what it is, when you got it, how you use it, and explain why you find it useful.',
    topic: 'Technology',
    cueCard: 'Describe a piece of technology that you find useful.',
    followUpQuestions: ['How has technology changed the way people communicate?', 'Do you think older people find it difficult to use new technology?', 'What technological advancement has been most important in recent years?'],
    tags: ['technology', 'daily-life', 'description'],
    difficulty: 'medium',
    isFavorite: false,
    status: 'new',
    isDone: false,
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'built-in-speaking-p2-place-1',
    part: 2,
    question: 'Describe a place you have visited that you found beautiful. You should say: where it was, when you went there, what you saw, and explain why you found it beautiful.',
    topic: 'Travel',
    cueCard: 'Describe a beautiful place you have visited.',
    followUpQuestions: ['Why do people enjoy visiting beautiful places?', 'How can tourism affect natural beauty?', 'Do you think cities can be beautiful?'],
    tags: ['travel', 'nature', 'description'],
    difficulty: 'medium',
    isFavorite: false,
    status: 'new',
    isDone: false,
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'built-in-speaking-p3-society-1',
    part: 3,
    question: 'How has technology changed the way people communicate in modern society? Do you think these changes are positive or negative?',
    topic: 'Technology',
    cueCard: '',
    followUpQuestions: ['What are the disadvantages of relying on digital communication?', 'How do you think people will communicate in the future?', 'Do you agree that face-to-face communication is becoming less important?'],
    tags: ['technology', 'society', 'communication'],
    difficulty: 'hard',
    isFavorite: false,
    status: 'new',
    isDone: false,
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'built-in-speaking-p3-environment-1',
    part: 3,
    question: 'What can individuals do to help protect the environment? Do you think government action is more important than individual efforts?',
    topic: 'Environment',
    cueCard: '',
    followUpQuestions: ['Why do some people ignore environmental issues?', 'Should companies be forced to reduce their environmental impact?', 'What is the biggest environmental challenge facing the world today?'],
    tags: ['environment', 'society', 'responsibility'],
    difficulty: 'hard',
    isFavorite: false,
    status: 'new',
    isDone: false,
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
]
