import type { WritingPrompt } from '@ielts/storage'

const now = '2025-01-01T00:00:00.000Z'

export const WRITING_PROMPTS_PACK_ID = 'writing-prompts-v1'

export const BUILT_IN_WRITING_PROMPTS: WritingPrompt[] = [
  {
    id: 'built-in-writing-task2-transport-1',
    taskType: 'task2',
    question: 'Some people believe that governments should invest more in public transportation to reduce traffic congestion. Others think that building more roads is the better solution. Discuss both views and give your own opinion.',
    topic: 'Transport',
    instructions: 'You should spend about 40 minutes on this task. Write at least 250 words.',
    tags: ['transport', 'government', 'environment'],
    difficulty: 'medium',
    isFavorite: false,
    status: 'new',
    isDone: false,
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'built-in-writing-task2-education-1',
    taskType: 'task2',
    question: 'Some people think that universities should focus on providing academic knowledge rather than practical skills. To what extent do you agree or disagree?',
    topic: 'Education',
    instructions: 'You should spend about 40 minutes on this task. Write at least 250 words.',
    tags: ['education', 'academic', 'employment'],
    difficulty: 'medium',
    isFavorite: false,
    status: 'new',
    isDone: false,
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'built-in-writing-task2-technology-1',
    taskType: 'task2',
    question: 'In the past, people stored knowledge in books. Nowadays, people store knowledge on the internet. Do the advantages of this development outweigh the disadvantages?',
    topic: 'Technology',
    instructions: 'You should spend about 40 minutes on this task. Write at least 250 words.',
    tags: ['technology', 'internet', 'knowledge'],
    difficulty: 'easy',
    isFavorite: false,
    status: 'new',
    isDone: false,
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'built-in-writing-task2-environment-1',
    taskType: 'task2',
    question: 'Environmental problems are too big for individual countries to solve. International cooperation is necessary. To what extent do you agree or disagree?',
    topic: 'Environment',
    instructions: 'You should spend about 40 minutes on this task. Write at least 250 words.',
    tags: ['environment', 'globalization', 'cooperation'],
    difficulty: 'medium',
    isFavorite: false,
    status: 'new',
    isDone: false,
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'built-in-writing-task1-technology-1',
    taskType: 'task1',
    question: 'The chart below shows the percentage of households in a country with internet access from 2015 to 2022. Summarize the information by selecting and reporting the main features.',
    topic: 'Technology',
    instructions: 'You should spend about 20 minutes on this task. Write at least 150 words.',
    tags: ['technology', 'chart', 'trends'],
    difficulty: 'easy',
    isFavorite: false,
    status: 'new',
    isDone: false,
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'built-in-writing-task1-environment-1',
    taskType: 'task1',
    question: 'The table shows the amount of waste produced by different countries in millions of tonnes per year. Summarize the information by selecting and reporting the main features.',
    topic: 'Environment',
    instructions: 'You should spend about 20 minutes on this task. Write at least 150 words.',
    tags: ['environment', 'table', 'data'],
    difficulty: 'medium',
    isFavorite: false,
    status: 'new',
    isDone: false,
    notes: '',
    createdAt: now,
    updatedAt: now,
  },
]
