import type { TranscriptOptions, TranscriptResult } from './types'
import { TranscriptError, PlayerResponseNotFoundError } from './types'
import type { ITranscriptService, IYoutubeTranscriptRepository, IMemoryTranscriptCache } from './interfaces'
import type { TranscriptData } from '../../../domain/types'

const DEBUG = process.env.NODE_ENV === 'development'

function log(...args: unknown[]): void {
  if (DEBUG) console.debug('[TranscriptService]', ...args)
}

export type PersistentCacheAccess = {
  readonly get: (videoId: string, language: string) => Promise<TranscriptData | null>
  readonly set: (videoId: string, language: string, data: TranscriptData) => Promise<void>
}

export class TranscriptService implements ITranscriptService {
  constructor(
    private readonly repository: IYoutubeTranscriptRepository,
    private readonly memoryCache: IMemoryTranscriptCache,
    private readonly persistentCache?: PersistentCacheAccess,
  ) {}

  async getTranscript(
    videoId: string,
    options?: TranscriptOptions,
  ): Promise<TranscriptResult> {
    try {
      const signal = options?.signal
      const forceRefresh = options?.forceRefresh ?? false

      if (!videoId) {
        return this.errorResult(
          new PlayerResponseNotFoundError('No video ID provided'),
        )
      }

      if (signal?.aborted) {
        return this.errorResult(
          new PlayerResponseNotFoundError('Request was cancelled'),
        )
      }

      const lang = options?.language || 'en'

      if (!forceRefresh) {
        const cached = this.memoryCache.get(videoId, lang)
        if (cached) return { ok: true, data: cached, source: 'cache' }
      }

      if (!forceRefresh && this.persistentCache) {
        const persistentCached = await this.persistentCache.get(videoId, lang)
        if (persistentCached && !signal?.aborted) {
          const transcript = this.toDomainTranscript(persistentCached)
          this.memoryCache.set(videoId, lang, transcript)
          return { ok: true, data: transcript, source: 'cache' }
        }
      }

      if (signal?.aborted) {
        return this.errorResult(
          new PlayerResponseNotFoundError('Request was cancelled'),
        )
      }

      const transcript = await this.repository.fetch(videoId, options)

      this.memoryCache.set(videoId, transcript.language, transcript)

      if (this.persistentCache) {
        this.persistentCache
          .set(videoId, transcript.language, this.toStorageFormat(transcript))
          .catch(() => {})
      }

      return { ok: true, data: transcript, source: 'network' }
    } catch (err) {
      if (err instanceof TranscriptError) {
        log('TranscriptError:', err.code, err.message)
        return this.errorResult(err)
      }

      if (err instanceof DOMException && err.name === 'AbortError') {
        return this.errorResult(
          new PlayerResponseNotFoundError('Request was cancelled'),
        )
      }

      console.error(
        'apps/extension/src/youtube-learning/infrastructure/youtube/transcript/TranscriptService.ts error:',
        err,
      )
      log('getTranscript UNCAUGHT error:', err)
      return this.errorResult(
        new TranscriptError(
          'UNKNOWN',
          `Internal error: ${err instanceof Error ? err.message : String(err)}`,
          false,
        ),
      )
    }
  }

  clearCache(videoId?: string): void {
    this.memoryCache.clear(videoId)
  }

  private errorResult(error: TranscriptError): Extract<TranscriptResult, { ok: false }> {
    return { ok: false, error }
  }

  private toDomainTranscript(data: TranscriptData): import('./types').Transcript {
    return {
      videoId: data.videoId,
      language: data.language,
      isAutoGenerated: data.source === 'auto-generated',
      segments: data.segments.map(s => ({
        text: s.text,
        start: s.start,
        end: s.end,
        duration: s.end - s.start,
      })),
      fullText: data.fullText,
    }
  }

  private toStorageFormat(transcript: import('./types').Transcript): TranscriptData {
    return {
      videoId: transcript.videoId,
      language: transcript.language,
      source: transcript.isAutoGenerated ? 'auto-generated' : 'manual',
      segments: transcript.segments.map((s, i) => ({
        id: `${transcript.videoId}-seg-${i}`,
        text: s.text,
        start: s.start,
        end: s.end,
      })),
      fullText: transcript.fullText,
    }
  }
}
