export type TranscriptErrorCode =
  | 'INVALID_VIDEO_ID'
  | 'PLAYER_RESPONSE_NOT_FOUND'
  | 'PLAYER_INIT_TIMEOUT'
  | 'AD_PLAYING'
  | 'VIDEO_CHANGED'
  | 'CAPTION_TRACK_NOT_FOUND'
  | 'TRANSCRIPT_DOWNLOAD_FAILED'
  | 'TRANSCRIPT_PARSE_FAILED'
  | 'TRANSCRIPT_UNAVAILABLE'
  | 'NETWORK_ERROR'
  | 'REQUEST_CANCELLED'
  | 'UNKNOWN'

export class TranscriptError extends Error {
  public readonly code: TranscriptErrorCode
  public readonly retryable: boolean
  public readonly detail?: string

  constructor(code: TranscriptErrorCode, message: string, retryable: boolean, detail?: string) {
    super(message)
    this.name = 'TranscriptError'
    this.code = code
    this.retryable = retryable
    this.detail = detail
  }
}

export class PlayerInitTimeoutError extends TranscriptError {
  constructor(message = 'Timed out waiting for the YouTube player to initialize.') {
    super('PLAYER_INIT_TIMEOUT', message, true)
    this.name = 'PlayerInitTimeoutError'
  }
}

export class AdPlayingError extends TranscriptError {
  constructor(message = 'An advertisement is currently playing.') {
    super('AD_PLAYING', message, true)
    this.name = 'AdPlayingError'
  }
}

export class VideoChangedError extends TranscriptError {
  constructor(message = 'The video changed while waiting for captions.') {
    super('VIDEO_CHANGED', message, false)
    this.name = 'VideoChangedError'
  }
}

export class PlayerResponseNotFoundError extends TranscriptError {
  constructor(message = 'The YouTube player response could not be found. The page may still be loading.') {
    super('PLAYER_RESPONSE_NOT_FOUND', message, true)
    this.name = 'PlayerResponseNotFoundError'
  }
}

export class CaptionTrackNotFoundError extends TranscriptError {
  constructor(message = 'No suitable caption track was found for this video.') {
    super('CAPTION_TRACK_NOT_FOUND', message, false)
    this.name = 'CaptionTrackNotFoundError'
  }
}

export class TranscriptDownloadError extends TranscriptError {
  constructor(message = 'Failed to download the transcript. The captions may not be available.') {
    super('TRANSCRIPT_DOWNLOAD_FAILED', message, true)
    this.name = 'TranscriptDownloadError'
  }
}

export class NoCaptionDataForLanguageError extends TranscriptError {
  public readonly language: string
  constructor(language: string) {
    super('CAPTION_TRACK_NOT_FOUND', `No caption data available for language: ${language}`, false)
    this.name = 'NoCaptionDataForLanguageError'
    this.language = language
  }
}

export class TranscriptParseError extends TranscriptError {
  constructor(message = 'Failed to parse the transcript XML. The caption format may have changed.') {
    super('TRANSCRIPT_PARSE_FAILED', message, false)
    this.name = 'TranscriptParseError'
  }
}

export class TranscriptUnavailableError extends TranscriptError {
  constructor(message = 'Could not load transcript. The video may not have captions, or the download failed. Try again.') {
    super('TRANSCRIPT_UNAVAILABLE', message, true)
    this.name = 'TranscriptUnavailableError'
  }
}

export interface TranscriptSegment {
  readonly text: string
  readonly start: number
  readonly end: number
  readonly duration: number
}

export interface Transcript {
  readonly videoId: string
  readonly language: string
  readonly isAutoGenerated: boolean
  readonly segments: readonly TranscriptSegment[]
  readonly fullText: string
}

export interface TranscriptOptions {
  readonly signal?: AbortSignal
  readonly language?: string
  readonly forceRefresh?: boolean
}

export type TranscriptResult =
  | { readonly ok: true; readonly data: Transcript; readonly source: 'cache' | 'network' }
  | { readonly ok: false; readonly error: TranscriptError }

export interface CaptionTrack {
  readonly baseUrl: string
  readonly languageCode: string
  readonly kind: 'manual' | 'auto'
  readonly name: string
  readonly vssId: string
  readonly isTranslatable: boolean
}

export interface YouTubePlayerResponse {
  readonly captionTracks: readonly CaptionTrack[]
}
