export const ROUTES = {
  tutor: '/ai-tutor',
  dashboard: '/dashboard',
  roadmap: '/study-roadmap',
  vocabulary: '/vocabulary',
  review: '/review',
  reviewCenter: '/review-center',
  reading: '/practice/reading',
  listening: '/practice/listening',
  writing: '/writing',
  speaking: '/speaking',
  grammar: '/grammar',
  mistakes: '/mistakes',
  mockTests: '/mock-tests',
  artifacts: '/artifacts',
  search: '/search',
  books: '/books',
  publicApi: '/public-api',
  settings: '/settings',
  settingsAi: '/settings/ai',
  settingsData: '/settings/data',
  importExport: '/import-export',
  info: '/info',
  privacy: '/privacy',
  landing: '/',
  feedback: '/feedback',
} as const
