export type { LearningSession, LearningSessionStatus, LearningSessionSource, LearningMode, LearningGenerationMetadata, CreateLearningSessionRequest, CreateLearningSessionResult, ResumeLearningSessionResult, CompleteLearningSessionRequest, CompleteLearningSessionResult, LearningSessionSummaryResult } from './learning-session'
export type { LearningObjective, LearningObjectiveType, LearningObjectiveSource, TaskPriority, LearningSuccessCriterion } from './learning-objective'
export type { LearningActivity, ActivityType, GenerateLearningActivityRequest, GenerateLearningActivityResult, LearningSourceContent } from './learning-activity'
export type { Exercise, ExerciseType, ExerciseSourceType, ExplanationPolicy, EvaluationPolicy, LearningContentPayload, ExerciseTemplate, ExerciseTemplateInput } from './exercise'
export type { ExerciseQuestion, ExerciseQuestionType, MultipleChoiceQuestion, GapFillQuestion, TrueFalseNotGivenQuestion, ShortAnswerQuestion, MatchingQuestion, ErrorCorrectionQuestion, EssayQuestion, SpeakingResponseQuestion } from '@ielts/shared'
export type { LearningAttempt, LearningAttemptStatus, LearningAnswer, StartAttemptRequest, SubmitLearningAnswerRequest, SubmitLearningAnswerResult } from './learning-attempt'
export type { AnswerEvaluation, EvaluationStatus, EvaluationMethod, RubricScore, WritingEvaluation, SpeakingEvaluation } from './evaluation'
export type { MistakeEvidence, MistakeSeverity, MistakeReviewStatus } from './mistake-evidence'
export type { SkillEvidence, SkillEvidenceType, SkillProgress, SkillEvidenceBuilderInput } from './skill-evidence'
export type { ProgressEvidence } from './progress-evidence'
export type { LearningOutcome, VocabularyEvidence } from './learning-outcome'
export type { LearningRecommendation, RecommendationAction, LearningRecommendationRequest, LearningRecommendationResult } from './learning-recommendation'
export type { LearningFeedback, FeedbackExplanationRequest, FeedbackExplanationResult } from './feedback'
export type { LearningLesson, LearningExample } from './learning-lesson'
