export interface ColorTokens {
  background: string
  surface: string
  surfaceAlt: string
  surfaceSecondary: string
  primary: string
  primaryHover: string
  primaryLight: string
  primaryDark: string
  onPrimary: string
  text: string
  textSecondary: string
  muted: string
  textInverse: string
  border: string
  borderLight: string
  success: string
  successLight: string
  successDark: string
  warning: string
  warningLight: string
  warningDark: string
  danger: string
  dangerLight: string
  dangerDark: string
  info: string
  infoLight: string
  infoDark: string
  skillListening: string
  skillListeningLight: string
  skillListeningDark: string
  skillReading: string
  skillReadingLight: string
  skillReadingDark: string
  skillWriting: string
  skillWritingLight: string
  skillWritingDark: string
  skillSpeaking: string
  skillSpeakingLight: string
  skillSpeakingDark: string
  tutorBackground: string
  tutorText: string
  tutorBorder: string
  tutorAccent: string
  tutorAccentLight: string
  overlay: string
  skeleton: string
  highlight: string
}

export const COLORS: ColorTokens = {
  background: '#f8fafc',
  surface: '#ffffff',
  surfaceAlt: '#f1f5f9',
  surfaceSecondary: '#f1f5f9',
  primary: '#2563eb',
  primaryHover: '#1d4ed8',
  primaryLight: '#dbeafe',
  primaryDark: '#1e40af',
  onPrimary: '#ffffff',
  text: '#0f172a',
  textSecondary: '#475569',
  muted: '#94a3b8',
  textInverse: '#ffffff',
  border: '#e2e8f0',
  borderLight: '#f1f5f9',
  success: '#22c55e',
  successLight: '#dcfce7',
  successDark: '#15803d',
  warning: '#f59e0b',
  warningLight: '#fef3c7',
  warningDark: '#b45309',
  danger: '#ef4444',
  dangerLight: '#fee2e2',
  dangerDark: '#b91c1c',
  info: '#3b82f6',
  infoLight: '#dbeafe',
  infoDark: '#1d4ed8',
  skillListening: '#06b6d4',
  skillListeningLight: '#cffafe',
  skillListeningDark: '#0e7490',
  skillReading: '#8b5cf6',
  skillReadingLight: '#ede9fe',
  skillReadingDark: '#6d28d9',
  skillWriting: '#f59e0b',
  skillWritingLight: '#fef3c7',
  skillWritingDark: '#b45309',
  skillSpeaking: '#ec4899',
  skillSpeakingLight: '#fce7f3',
  skillSpeakingDark: '#be185d',
  tutorBackground: '#f0f9ff',
  tutorText: '#0c4a6e',
  tutorBorder: '#bae6fd',
  tutorAccent: '#0ea5e9',
  tutorAccentLight: '#e0f2fe',
  overlay: 'rgba(0, 0, 0, 0.4)',
  skeleton: '#e2e8f0',
  highlight: '#fef9c3',
}

export const DARK_COLORS: Partial<ColorTokens> = {
  background: '#0f172a',
  surface: '#1e293b',
  surfaceAlt: '#0f172a',
  surfaceSecondary: '#334155',
  primary: '#3b82f6',
  primaryHover: '#60a5fa',
  primaryLight: '#1e3a5f',
  primaryDark: '#93c5fd',
  onPrimary: '#ffffff',
  text: '#f1f5f9',
  textSecondary: '#94a3b8',
  muted: '#64748b',
  textInverse: '#0f172a',
  border: '#334155',
  borderLight: '#1e293b',
  success: '#22c55e',
  successLight: '#14532d',
  successDark: '#86efac',
  warning: '#f59e0b',
  warningLight: '#78350f',
  warningDark: '#fde68a',
  danger: '#ef4444',
  dangerLight: '#7f1d1d',
  dangerDark: '#fca5a5',
  info: '#3b82f6',
  infoLight: '#1e3a5f',
  infoDark: '#93c5fd',
  skillListening: '#22d3ee',
  skillListeningLight: '#164e63',
  skillListeningDark: '#a5f3fc',
  skillReading: '#a78bfa',
  skillReadingLight: '#3b0764',
  skillReadingDark: '#ddd6fe',
  skillWriting: '#fbbf24',
  skillWritingLight: '#78350f',
  skillWritingDark: '#fde68a',
  skillSpeaking: '#f472b6',
  skillSpeakingLight: '#831843',
  skillSpeakingDark: '#fbcfe8',
  tutorBackground: '#0c4a6e',
  tutorText: '#e0f2fe',
  tutorBorder: '#0e7490',
  tutorAccent: '#38bdf8',
  tutorAccentLight: '#0c4a6e',
  overlay: 'rgba(0, 0, 0, 0.6)',
  skeleton: '#334155',
  highlight: '#713f12',
}
