import type { SaveCategory, LearningEntry } from '../types'
import {
  updateDailyProgress,
  setVideoPageInfo,
  setPendingVideoInfo,
  incrementDailyProgress,
} from '../services/storage'
import { saveEntry } from '../storage/indexedDB'
import { saveVocabularyEntry, type ExtensionVocabEntry } from '../storage/vocabularyStore'
import { emitFromBackground } from './eventEmitters'
import { vocabularyRepo, passageEntryRepo } from '../services/repositories'

const DEBUG = typeof process !== 'undefined' && process.env?.NODE_ENV === 'development'

function bgLog(...args: unknown[]): void {
  if (DEBUG) console.debug('[BG Transcript]', ...args)
}

export interface SaveItemPayload {
  category: SaveCategory
  text: string
  pageTitle: string
  pageUrl: string
  topic?: string
  skill?: string
  difficulty?: string
  tags?: string[]
  note?: string
}

export interface UpdateProgressPayload {
  wordsAdded?: number
  notesAdded?: number
  articlesSaved?: number
}

export interface VideoPagePayload {
  isVideoPage: boolean
  platform: string
  videoTitle: string
  videoUrl: string
  videoId: string
}

export interface MiniTutorSavePayload {
  id: string
  text: string
  category: SaveCategory
  pageTitle?: string
  pageUrl?: string
}

export interface MiniTutorOpenPayload {
  action: string
  text: string
}

export interface AiExplainPayload {
  text: string
  action: string
  systemPrompt?: string
  userPrompt?: string
}

export interface FetchTranscriptPayload {
  videoId: string
}

export interface FetchTranscriptResponse {
  tracks?: Array<{ languageCode: string; baseUrl: string; isAutoGenerated: boolean }>
  error?: string
}

let ytPlayerApiKey: string | undefined

export function setYouTubePlayerApiKey(key: string | undefined) {
  ytPlayerApiKey = key
}

export function getYouTubePlayerApiKey(): string | undefined {
  return ytPlayerApiKey
}

async function fetchYoutubePlayerResponse(videoId: string): Promise<Record<string, unknown> | null> {
  try {
    // Try the internal YouTube API first (no API key needed, uses session)
    const url = `https://www.youtube.com/youtubei/v1/player?key=${getYouTubePlayerApiKey() ?? ''}`
    const response = await fetch(url, {
      method: 'POST',
      credentials: 'include',
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json',
      },
      body: JSON.stringify({
        videoId,
        contentCheckOk: true,
        racyCheckOk: true,
        context: {
          client: {
            clientName: 'WEB',
            clientVersion: '2.20240101.00.00',
            hl: 'en',
            gl: 'US',
          },
        },
      }),
    })
    if (!response.ok) {
      bgLog('YouTube API response not ok:', response.status)
      return null
    }
    const data = await response.json()
    return data as Record<string, unknown>
  } catch (e) {
    console.error('apps/extension/src/background/messaging.ts error:', e);
    bgLog('fetchYoutubePlayerResponse error:', e)
    return null
  }
}

function parseCaptionTracksFromPlayerResponse(
  data: Record<string, unknown>,
): Array<{ languageCode: string; baseUrl: string; isAutoGenerated: boolean }> | null {
  try {
    const captions = (data as any)?.captions?.playerCaptionsTracklistRenderer?.captionTracks
    if (!captions?.length) return null
    return captions.map((t: { languageCode: string; baseUrl: string; kind?: string }) => ({
      languageCode: t.languageCode,
      baseUrl: t.baseUrl,
      isAutoGenerated: t.kind === 'asr',
    }))
  } catch (error) {
    console.error('apps/extension/src/background/messaging.ts error:', error);
    return null
  }
}

async function backgroundFetchTranscript(videoId: string): Promise<FetchTranscriptResponse> {
  // Strategy 1: Try YouTube internal API
  bgLog('Fetching player response for', videoId)
  const playerData = await fetchYoutubePlayerResponse(videoId)
  if (playerData) {
    const tracks = parseCaptionTracksFromPlayerResponse(playerData)
    if (tracks?.length) {
      bgLog('Found', tracks.length, 'caption tracks via YouTube API')
      return { tracks }
    }
  }

  // Strategy 2: Try fetching the watch page directly
  try {
    const htmlResponse = await fetch(`https://www.youtube.com/watch?v=${videoId}&gl=US&hl=en`, {
      credentials: 'include',
      headers: {
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8',
        'Accept-Language': 'en-US,en;q=0.9',
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
      },
    })
    if (htmlResponse.ok) {
      const html = await htmlResponse.text()
      const searches = [
        'ytInitialPlayerResponse =',
        'ytInitialPlayerResponse=',
        'window.ytInitialPlayerResponse=',
        'window.ytInitialPlayerResponse =',
        'var ytInitialPlayerResponse=',
        'var ytInitialPlayerResponse =',
      ]
      for (const search of searches) {
        const idx = html.indexOf(search)
        if (idx === -1) continue
        const valueStart = idx + search.length
        const bracePos = html.indexOf('{', valueStart)
        if (bracePos === -1) continue
        let depth = 0
        let inString = false
        let escape = false
        for (let i = bracePos; i < html.length; i++) {
          const ch = html[i]
          if (escape) { escape = false; continue }
          if (ch === '\\') { escape = true; continue }
          if (ch === '"') { inString = !inString; continue }
          if (inString) continue
          if (ch === '{') depth++
          if (ch === '}') depth--
          if (depth === 0) {
            try {
              const parsed = JSON.parse(html.slice(bracePos, i + 1)) as Record<string, unknown>
              const tracks = parseCaptionTracksFromPlayerResponse(parsed)
              if (tracks?.length) {
                bgLog('Found tracks via page HTML fetch')
                return { tracks }
              }
            } catch (error) {
            console.error('apps/extension/src/background/messaging.ts error:', error);
            }
            break
          }
        }
      }
    }
  } catch (e) {
    console.error('apps/extension/src/background/messaging.ts error:', e);
    bgLog('Page fetch error:', e)
  }

  return { error: 'NO_CAPTIONS_EXIST' }
}

interface MessageMap {
  GET_DAILY_PROGRESS: undefined
  UPDATE_PROGRESS: UpdateProgressPayload
  OPEN_OPTIONS: undefined
  VIDEO_PAGE_DETECTED: VideoPagePayload
  VIDEO_HELPER_OPEN: VideoPagePayload
  MINI_TUTOR_SAVE_RESULT: MiniTutorSavePayload
  MINI_TUTOR_OPEN_PAGE: MiniTutorOpenPayload
  SAVE_SELECTION_FULL: SaveItemPayload
  AI_EXPLAIN: AiExplainPayload
  MINI_TUTOR_TRIGGER: MiniTutorOpenPayload
  FETCH_TRANSCRIPT: FetchTranscriptPayload
  FETCH_TRANSCRIPT_XML: { baseUrl: string; videoId: string }
}

export type ExtensionMessage<K extends keyof MessageMap = keyof MessageMap> = {
  [P in K]: { type: P; payload: MessageMap[P] }
}[K]

export type MessageHandler = (
  message: ExtensionMessage,
  sender: chrome.runtime.MessageSender,
) => Promise<unknown> | unknown

export type SyncMessageHandler = (
  message: ExtensionMessage,
  sendResponse: (response: unknown) => void,
) => void

const handlers = new Map<string, MessageHandler>()

export function registerHandler(type: string, handler: MessageHandler): void {
  handlers.set(type, handler)
}

export function unregisterHandler(type: string): void {
  handlers.delete(type)
}

function isKnownMessage(msg: unknown): msg is ExtensionMessage {
  if (!msg || typeof msg !== 'object') return false
  const m = msg as Record<string, unknown>
  return typeof m.type === 'string' && handlers.has(m.type)
}

export function handleMessage(
  message: unknown,
  sender: chrome.runtime.MessageSender,
  sendResponse: (response: unknown) => void,
): boolean {
  if (!isKnownMessage(message)) {
    return false
  }

  const handler = handlers.get(message.type)!
  try {
    const result = handler(message, sender)

    if (result instanceof Promise) {
      result
        .then((data) => {
          sendResponse({ success: true, data })
        })
        .catch((err) => {
          console.error(`[messaging] Handler error for ${message.type}:`, err)
          sendResponse({
            success: false,
            error: 'HANDLER_ERROR',
            message: err instanceof Error ? err.message : 'Unknown error',
          })
        })
      return true
    }

    sendResponse({ success: true, data: result })
    return false
  } catch (err) {
    console.error(`[messaging] Sync handler error for ${message.type}:`, err)
    sendResponse({
      success: false,
      error: 'HANDLER_ERROR',
      message: err instanceof Error ? err.message : 'Unknown error',
    })
    return false
  }
}

export function initMessaging(): void {
  registerHandler('GET_DAILY_PROGRESS', async () => {
    const result = await chrome.storage.local.get(['dailyProgress'])
    return (
      result.dailyProgress || {
        wordsAdded: 0,
        notesAdded: 0,
        articlesSaved: 0,
        notesSaved: 0,
        reviewDue: 0,
        streak: 0,
      }
    )
  })

  registerHandler('UPDATE_PROGRESS', async (_msg, _sender) => {
    const msg = _msg as ExtensionMessage<'UPDATE_PROGRESS'>
    await updateDailyProgress(msg.payload)
  })

  registerHandler('OPEN_OPTIONS', () => {
    chrome.runtime.openOptionsPage()
  })

  registerHandler('VIDEO_PAGE_DETECTED', async (_msg) => {
    const msg = _msg as ExtensionMessage<'VIDEO_PAGE_DETECTED'>
    if (msg.payload?.isVideoPage) {
      await setVideoPageInfo(msg.payload)
    }
  })

  registerHandler('VIDEO_HELPER_OPEN', async (_msg, sender) => {
    const tabId = sender.tab?.id
    if (tabId) {
      try {
        await chrome.tabs.sendMessage(tabId, { type: 'TOGGLE_YOUTUBE_LEARNING', payload: true })
      } catch (error) {
        console.error('apps/extension/src/background/messaging.ts error:', error);
        // Content script not ready — fall back to popup
        const msg = _msg as ExtensionMessage<'VIDEO_HELPER_OPEN'>
        await setPendingVideoInfo(msg.payload)
        try {
          await chrome.action.openPopup()
        } catch (error) {
 console.error('apps/extension/src/background/messaging.ts error:', error);
 /* ignore */ }
      }
    }
  })

  registerHandler('MINI_TUTOR_SAVE_RESULT', async (_msg) => {
    const msg = _msg as ExtensionMessage<'MINI_TUTOR_SAVE_RESULT'>
    const now = new Date().toISOString()
    try {
      const learningEntry: LearningEntry = {
        id: msg.payload.id,
        text: msg.payload.text,
        category: msg.payload.category,
        topic: 'general',
        skill: 'vocabulary',
        difficulty: '',
        tags: [],
        personalNote: '',
        pageTitle: msg.payload.pageTitle || '',
        pageUrl: msg.payload.pageUrl || '',
        status: 'new',
        createdAt: now,
        updatedAt: now,
      }
      await saveEntry(learningEntry)
      passageEntryRepo.bulkUpsert([{ id: msg.payload.id || `ext-${Date.now()}`, title: 'Extension Entry', content: JSON.stringify(learningEntry), topic: msg.payload.category || 'general', createdAt: now, updatedAt: now }]).catch(() => {})
      await incrementDailyProgress('wordsAdded', 1)

      const sourceUrl = msg.payload.pageUrl || ''
      if (msg.payload.category === 'vocabulary') {
        emitFromBackground({
          eventType: 'extension_vocabulary_saved',
          source: 'extension_popup',
          payload: {
            eventType: 'extension_vocabulary_saved',
            word: msg.payload.text.split(/\s+/)[0] || msg.payload.text,
            contextSnippet: msg.payload.text,
            sourceUrl,
          },
          entityType: 'vocabulary',
          page: sourceUrl,
        })
      } else {
        emitFromBackground({
          eventType: 'extension_selected_text_saved',
          source: 'extension_popup',
          payload: {
            eventType: 'extension_selected_text_saved',
            textSnippet: msg.payload.text,
            sourceUrl,
          },
          entityType: 'selected_text',
          page: sourceUrl,
        })
      }
    } catch (error) {
      console.error('apps/extension/src/background/messaging.ts error:', error);
      /* non-critical */
    }
  })

  registerHandler('SAVE_SELECTION_FULL', async (_msg) => {
    const msg = _msg as ExtensionMessage<'SAVE_SELECTION_FULL'>
    const now = new Date().toISOString()
    try {
      const entry: LearningEntry = {
        id: crypto.randomUUID(),
        text: msg.payload.text,
        category: msg.payload.category,
        topic: msg.payload.topic || 'general',
        skill: (msg.payload.skill || 'general') as LearningEntry['skill'],
        difficulty: (msg.payload.difficulty || '') as LearningEntry['difficulty'],
        tags: msg.payload.tags || [],
        personalNote: msg.payload.note || '',
        pageTitle: msg.payload.pageTitle,
        pageUrl: msg.payload.pageUrl,
        status: 'new',
        createdAt: now,
        updatedAt: now,
      }
      await saveEntry(entry)

      if (msg.payload.category === 'vocabulary') {
        await saveVocabularyEntry({
          id: crypto.randomUUID(),
          word: msg.payload.text.split(/\s+/)[0].replace(/[.,!?;:'"()\-]/g, ''),
          sourceSentence: msg.payload.text,
          pageTitle: msg.payload.pageTitle || '',
          pageUrl: msg.payload.pageUrl || '',
          topic: (msg.payload.topic as string) || 'general',
          personalNote: msg.payload.note || '',
          tags: (msg.payload.tags as string[]) || [],
          meaning: '',
          translation: '',
          partOfSpeech: '',
          pronunciation: '',
          exampleSentence: '',
          synonyms: [],
          antonyms: [],
          collocations: [],
          wordFamily: [],
          difficulty: (msg.payload.difficulty as ExtensionVocabEntry['difficulty']) || '',
          status: 'new',
          addedToReview: true,
          reviewId: '',
          createdAt: now,
          updatedAt: now,
        }).catch(() => {})
      }

      await incrementDailyProgress('wordsAdded', msg.payload.category === 'vocabulary' ? 1 : 0)
    } catch (err) {
      console.error('[messaging] SAVE_SELECTION_FULL handler error:', err)
    }
  })

  registerHandler('MINI_TUTOR_OPEN_PAGE', async (_msg, _sender) => {
    const msg = _msg as ExtensionMessage<'MINI_TUTOR_OPEN_PAGE'>
    const { action, text } = msg.payload
    const [tab] = await chrome.tabs.query({ active: true, currentWindow: true })
    if (tab?.id) {
      await chrome.tabs.sendMessage(tab.id, {
        type: 'MINI_TUTOR_TRIGGER',
        payload: { action, text },
      })
    }
  })

  registerHandler('SAVE_YOUTUBE_VOCAB_TO_IDB', async (_msg) => {
    const msg = _msg as { type: string; payload: Record<string, unknown> }
    const { word, sentence, videoTitle, videoUrl } = msg.payload
    const now = new Date().toISOString()
    await saveVocabularyEntry({
      id: crypto.randomUUID(),
      word: (word as string) ?? '',
      sourceSentence: (sentence as string) ?? '',
      pageTitle: (videoTitle as string) ?? '',
      pageUrl: (videoUrl as string) ?? '',
      topic: '',
      personalNote: '',
      tags: [],
      meaning: '',
      translation: '',
      partOfSpeech: '',
      pronunciation: '',
      exampleSentence: '',
      synonyms: [],
      antonyms: [],
      collocations: [],
      wordFamily: [],
      difficulty: '',
      status: 'new',
      addedToReview: false,
      reviewId: '',
      createdAt: now,
      updatedAt: now,
    }).catch(() => {})
    return { success: true }
  })

  registerHandler('SYNC_ALL_TO_WEB', async () => {
    try {
      const { getAllVocabulary } = await import('../storage/vocabularyStore')
      const allVocab = await getAllVocabulary()
      if (allVocab.length === 0) {
        return { ok: true, count: 0 }
      }

      const tabs = await chrome.tabs.query({})
      const ieltsTabs = tabs.filter(t => {
        if (!t.id || !t.url) return false
        try { return new URL(t.url).hostname === 'ieltsjourney.dev' }
        catch (error) {
 console.error('apps/extension/src/background/messaging.ts error:', error);
 return false }
      })
      const targets = ieltsTabs.length > 0 ? ieltsTabs : tabs.filter(t => t.id)

      const batchPayload = allVocab.map(vocab => ({
        entityType: 'vocabulary' as const,
        operation: 'created' as const,
        entityId: vocab.id,
        entity: vocab as unknown as Record<string, unknown>,
        timestamp: new Date().toISOString(),
        messageId: `sync-all-${vocab.id}-${Date.now()}`,
      }))

      await Promise.all(targets.map(tab =>
        chrome.tabs.sendMessage(tab.id!, {
          type: 'FORWARD_DATA_SYNC_BATCH',
          payload: batchPayload,
        }).catch(() => {})
      ))

      return { ok: true, count: allVocab.length }
    } catch (err) {
      console.error('[messaging] SYNC_ALL_TO_WEB handler error:', err)
      return { ok: false, error: String(err) }
    }
  })

  registerHandler('FETCH_TRANSCRIPT', async (_msg, sender) => {
    const msg = _msg as { type: 'FETCH_TRANSCRIPT'; payload: { videoId: string } }
    const { videoId } = msg.payload
    if (!videoId) return { success: false, error: 'NO_VIDEO_ID' }

    // First try: use chrome.scripting.executeScript in MAIN world to access window.ytInitialPlayerResponse
    const tabId = sender.tab?.id
    if (tabId) {
      try {
        const results = await chrome.scripting.executeScript({
          target: { tabId },
          world: 'MAIN',
          func: (vid: string) => {
            try {
              const w = window as any
              let data = w.ytInitialPlayerResponse
              if (!data && w.ytplayer?.config?.args?.player_response) {
                const raw = w.ytplayer.config.args.player_response
                data = typeof raw === 'string' ? JSON.parse(raw) : raw
              }
              if (!data) return null
              const tracks = data.captions?.playerCaptionsTracklistRenderer?.captionTracks
              if (!tracks?.length) return null
              return {
                videoId: data.videoDetails?.videoId || vid,
                playabilityStatus: data.playabilityStatus?.status || null,
                captionTracks: tracks.map((t: any) => ({
                  baseUrl: t.baseUrl || '',
                  languageCode: t.languageCode || '',
                  name: (t.name?.simpleText) || t.languageCode || '',
                  kind: t.kind === 'asr' ? 'auto' : 'manual',
                  isTranslatable: !!t.isTranslatable,
                  vssId: t.vssId || undefined,
                })),
              }
            } catch (error) {
 console.error('apps/extension/src/background/messaging.ts error:', error);
 return null }
          },
          args: [videoId],
        })
        const playerResult = results?.[0]?.result as { videoId: string | null; playabilityStatus: string | null; captionTracks: Array<{ baseUrl: string; languageCode: string; name: string; kind: string; isTranslatable: boolean; vssId?: string }> } | null
        if (playerResult?.captionTracks?.length) {
          bgLog('Found caption tracks via scripting MAIN world')
          return { success: true, data: { tracks: playerResult.captionTracks, playabilityStatus: playerResult.playabilityStatus } }
        }
      } catch (e) {
        console.error('apps/extension/src/background/messaging.ts error:', e);
        bgLog('Scripting executeScript error:', e)
      }
    }

    // Fallback: use YouTube internal API
    const result = await backgroundFetchTranscript(videoId)
    return { success: !result.error, data: result }
  })

  registerHandler('FETCH_TRANSCRIPT_DIRECT', async (_msg) => {
    const msg = _msg as unknown as { type: 'FETCH_TRANSCRIPT_DIRECT'; payload: { videoId: string; language: string } }
    const { videoId, language } = msg.payload
    if (!videoId) return { success: false, error: 'INVALID_VIDEO_ID' }

    const urls = [
      `https://youtubetranscript.com/?v=${videoId}`,
      `https://youtubetranscriptapi.vercel.app/api/transcript?videoId=${videoId}`,
    ]

    for (const url of urls) {
      try {
        const response = await fetch(url, { headers: { 'Accept': 'application/json,text/xml,*/*' } })
        if (!response.ok) continue
        const text = await response.text()
        if (!text || text.length < 20) continue
        if (text.trim().startsWith('<')) {
          const parser = new DOMParser()
          const xmlDoc = parser.parseFromString(text, 'text/xml')
          const textElements = xmlDoc.querySelectorAll('text')
          if (!textElements.length) continue
          const segments: Array<{ id: string; start: number; end: number; text: string }> = []
          textElements.forEach((el, index) => {
            const start = parseFloat(el.getAttribute('start') || '0')
            const dur = parseFloat(el.getAttribute('dur') || '0')
            const t = el.textContent?.trim() || ''
            if (!t) return
            segments.push({ id: `${videoId}-bg-${index}`, start, end: start + dur, text: t })
          })
          if (segments.length) {
            return { success: true, data: { videoId, language, source: 'auto-generated', segments, fullText: segments.map(s => s.text).join(' ') } }
          }
        } else {
          const json = JSON.parse(text)
          const raw = Array.isArray(json) ? json : (json as any).segments || (json as any).captions || (json as any).transcript || []
          if (!raw.length) continue
          const segments = raw.map((s: any, i: number) => {
            const start = typeof s.start === 'number' ? s.start : parseFloat(s.start || s.offset || '0')
            const dur = typeof s.duration === 'number' ? s.duration : parseFloat(s.duration || '0')
            return { id: `${videoId}-bg-${i}`, start, end: start + dur, text: (s.text || '').trim() }
          }).filter((s: { text: string }) => s.text)
          if (segments.length) {
            const detectedLang = (json as any).language || language
            return { success: true, data: { videoId, language: detectedLang, source: 'auto-generated', segments, fullText: segments.map((s: { text: string }) => s.text).join(' ') } }
          }
        }
      } catch (error) {
 console.error('apps/extension/src/background/messaging.ts error:', error);
 continue }
    }
    return { success: false, error: 'ALL_FAILED' }
  })

  chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    return handleMessage(message, sender, sendResponse)
  })
}
