import { YouTubeDOMObserver, type YouTubeDOMObserverCallbacks } from './YouTubeDOMObserver'
import { YouTubePlayerController, type PlayerControllerCallbacks, type PlayerState } from './YouTubePlayerController'
import { YouTubeTranscriptProvider, type TranscriptData, type TranscriptResult } from './YouTubeTranscriptProvider'
import { FocusMode } from './FocusMode'
import { detectVideoPage, isYouTubeWatchPage, type VideoPageInfo } from './YouTubePageDetector'

export type { TranscriptData, TranscriptResult }

export interface YouTubeAdapterCallbacks {
  onVideoChange?: (videoId: string) => void
  onPlayerReady?: () => void
  onPlayerStateChange?: (state: PlayerState) => void
  onTimeUpdate?: (time: number) => void
  onLayoutChange?: () => void
}

export class YouTubeAdapter {
  private observer: YouTubeDOMObserver
  private player: YouTubePlayerController
  private transcriptProvider: YouTubeTranscriptProvider
  private focusMode: FocusMode
  private currentVideoId: string = ''
  private callbacks: YouTubeAdapterCallbacks
  private initialized = false

  constructor(callbacks: YouTubeAdapterCallbacks = {}) {
    this.callbacks = callbacks
    this.observer = new YouTubeDOMObserver(this.createObserverCallbacks())
    this.player = new YouTubePlayerController(this.createPlayerCallbacks())
    this.transcriptProvider = new YouTubeTranscriptProvider()
    this.focusMode = new FocusMode()
  }

  init(): boolean {
    if (this.initialized) return true
    const info = detectVideoPage()
    if (!info.isVideoPage) return false
    this.currentVideoId = info.videoId
    this.observer.start()
    this.player.connect()
    this.initialized = true
    return true
  }

  destroy(): void {
    this.observer.destroy()
    this.player.destroy()
    this.focusMode.destroy()
    this.initialized = false
    this.currentVideoId = ''
  }

  reinit(): boolean {
    this.destroy()
    return this.init()
  }

  getVideoInfo(): VideoPageInfo {
    return detectVideoPage()
  }

  getCurrentVideoId(): string {
    return this.currentVideoId
  }

  isOnWatchPage(): boolean {
    return isYouTubeWatchPage()
  }

  getPlayer(): YouTubePlayerController {
    return this.player
  }

  getTranscriptProvider(): YouTubeTranscriptProvider {
    return this.transcriptProvider
  }

  getFocusMode(): FocusMode {
    return this.focusMode
  }

  async fetchTranscript(
    videoId?: string,
    options?: { signal?: AbortSignal; language?: string },
  ): Promise<TranscriptResult> {
    return this.transcriptProvider.getTranscript(videoId || this.currentVideoId, options)
  }

  async checkTranscriptAvailability(): Promise<{ available: boolean; hasManual: boolean; hasAutoGenerated: boolean; languages: string[]; error?: string }> {
    return this.transcriptProvider.checkAvailability()
  }

  private createObserverCallbacks(): YouTubeDOMObserverCallbacks {
    return {
      onVideoChange: (videoId: string) => {
        this.currentVideoId = videoId
        this.player.reconnect()
        this.callbacks.onVideoChange?.(videoId)
      },
      onPlayerReady: () => {
        this.player.reconnect()
        this.callbacks.onPlayerReady?.()
      },
      onLayoutChange: () => {
        this.callbacks.onLayoutChange?.()
      },
      onPageLayoutChange: () => {
        this.callbacks.onLayoutChange?.()
      },
    }
  }

  private createPlayerCallbacks(): PlayerControllerCallbacks {
    return {
      onTimeUpdate: (time: number) => {
        this.callbacks.onTimeUpdate?.(time)
      },
      onStateChange: (state: PlayerState) => {
        this.callbacks.onPlayerStateChange?.(state)
      },
    }
  }
}
