import { YouTubeDOMObserver, type YouTubeDOMObserverCallbacks } from './YouTubeDOMObserver'
import { YouTubePlayerController, type PlayerControllerCallbacks, type PlayerState } from './YouTubePlayerController'
import { FocusMode } from './FocusMode'
import { detectVideoPage, isYouTubeWatchPage, type VideoPageInfo } from './YouTubePageDetector'
import {
  TranscriptService,
  YoutubeTranscriptRepository,
  PlayerReadinessDetector,
  PlayerResponseProvider,
  PlayerResponseExtractor,
  CaptionTrackSelector,
  CaptionResolver,
  TranscriptParser,
  MemoryTranscriptCache,
} from './transcript'
import { TranscriptCacheService } from '../persistence/TranscriptCacheService'
import type { TranscriptResult, TranscriptOptions } from './transcript'
import type { ITranscriptService } from './transcript'

export type { TranscriptResult, TranscriptOptions }

export interface YouTubeAdapterCallbacks {
  onVideoChange?: (videoId: string) => void
  onPlayerReady?: () => void
  onPlay?: () => void
  onPause?: () => void
  onSeek?: (time: number) => void
  onPlayerStateChange?: (state: PlayerState) => void
  onTimeUpdate?: (time: number) => void
  onLayoutChange?: () => void
}

export class YouTubeAdapter {
  private observer: YouTubeDOMObserver
  private player: YouTubePlayerController
  private transcriptService: TranscriptService
  private focusMode: FocusMode
  private currentVideoId: string = ''
  private callbacks: YouTubeAdapterCallbacks
  private initialized = false

  constructor(callbacks: YouTubeAdapterCallbacks = {}) {
    this.callbacks = callbacks
    this.observer = new YouTubeDOMObserver(this.createObserverCallbacks())
    this.player = new YouTubePlayerController(this.createPlayerCallbacks())
    this.focusMode = new FocusMode()

    const extractor = new PlayerResponseExtractor()
    const repository = new YoutubeTranscriptRepository(
      new PlayerReadinessDetector(),
      new PlayerResponseProvider(extractor),
      new CaptionTrackSelector(),
      new CaptionResolver(),
      new TranscriptParser(),
    )
    const memoryCache = new MemoryTranscriptCache()
    const persistentCache = new TranscriptCacheService()

    this.transcriptService = new TranscriptService(repository, memoryCache, {
      get: (videoId, lang) => persistentCache.get(videoId, lang),
      set: (videoId, lang, data) => persistentCache.set(videoId, lang, data),
    })
  }

  init(): boolean {
    if (this.initialized) return true
    const info = detectVideoPage()
    if (!info.isVideoPage) return false
    this.currentVideoId = info.videoId
    this.observer.start()
    this.player.connect()
    this.initialized = true
    return true
  }

  destroy(): void {
    this.observer.destroy()
    this.player.destroy()
    this.focusMode.destroy()
    this.initialized = false
    this.currentVideoId = ''
  }

  reinit(): boolean {
    this.destroy()
    return this.init()
  }

  getVideoInfo(): VideoPageInfo {
    return detectVideoPage()
  }

  getCurrentVideoId(): string {
    return this.currentVideoId
  }

  isOnWatchPage(): boolean {
    return isYouTubeWatchPage()
  }

  getPlayer(): YouTubePlayerController {
    return this.player
  }

  getTranscriptProvider(): ITranscriptService {
    return this.transcriptService
  }

  getFocusMode(): FocusMode {
    return this.focusMode
  }

  async fetchTranscript(
    videoId?: string,
    options?: { signal?: AbortSignal; language?: string },
  ): Promise<TranscriptResult> {
    return this.transcriptService.getTranscript(videoId || this.currentVideoId, options)
  }

  async checkTranscriptAvailability(): Promise<{ available: boolean; hasManual: boolean; hasAutoGenerated: boolean; languages: string[]; error?: string }> {
    return { available: false, hasManual: false, hasAutoGenerated: false, languages: [] }
  }

  private createObserverCallbacks(): YouTubeDOMObserverCallbacks {
    return {
      onVideoChange: (videoId: string) => {
        this.currentVideoId = videoId
        this.player.reconnect()
        this.callbacks.onVideoChange?.(videoId)
      },
      onPlayerReady: () => {
        this.player.reconnect()
        this.callbacks.onPlayerReady?.()
      },
      onLayoutChange: () => {
        this.callbacks.onLayoutChange?.()
      },
      onPageLayoutChange: () => {
        this.callbacks.onLayoutChange?.()
      },
    }
  }

  private createPlayerCallbacks(): PlayerControllerCallbacks {
    return {
      onTimeUpdate: (time: number) => {
        this.callbacks.onTimeUpdate?.(time)
      },
      onPlay: () => {
        this.callbacks.onPlay?.()
      },
      onPause: () => {
        this.callbacks.onPause?.()
      },
      onSeek: (time: number) => {
        this.callbacks.onSeek?.(time)
      },
      onStateChange: (state: PlayerState) => {
        this.callbacks.onPlayerStateChange?.(state)
      },
    }
  }
}
