import { describe, it, expect } from 'vitest'
import { MemoryTranscriptCache } from '../MemoryTranscriptCache'
import type { Transcript } from '../types'

function makeTranscript(videoId: string, language: string): Transcript {
  return {
    videoId,
    language,
    isAutoGenerated: true,
    segments: [{ text: 'Hello', start: 0, end: 1, duration: 1 }],
    fullText: 'Hello',
  }
}

describe('MemoryTranscriptCache', () => {
  it('returns null for cache miss', () => {
    const cache = new MemoryTranscriptCache(60000)
    expect(cache.get('abc', 'en')).toBeNull()
  })

  it('returns cached transcript for exact key match', () => {
    const cache = new MemoryTranscriptCache(60000)
    const transcript = makeTranscript('abc', 'en')
    cache.set('abc', 'en', transcript)
    expect(cache.get('abc', 'en')).toEqual(transcript)
  })

  it('returns null for different language', () => {
    const cache = new MemoryTranscriptCache(60000)
    cache.set('abc', 'en', makeTranscript('abc', 'en'))
    expect(cache.get('abc', 'vi')).toBeNull()
  })

  it('returns null for different videoId', () => {
    const cache = new MemoryTranscriptCache(60000)
    cache.set('abc', 'en', makeTranscript('abc', 'en'))
    expect(cache.get('xyz', 'en')).toBeNull()
  })

  it('returns null after TTL expires', async () => {
    const cache = new MemoryTranscriptCache(1) // 1ms TTL
    cache.set('abc', 'en', makeTranscript('abc', 'en'))
    await new Promise(resolve => setTimeout(resolve, 5))
    expect(cache.get('abc', 'en')).toBeNull()
  })

  it('clear() removes all entries', () => {
    const cache = new MemoryTranscriptCache(60000)
    cache.set('a', 'en', makeTranscript('a', 'en'))
    cache.set('b', 'en', makeTranscript('b', 'en'))
    cache.clear()
    expect(cache.get('a', 'en')).toBeNull()
    expect(cache.get('b', 'en')).toBeNull()
  })

  it('clear(videoId) removes only matching entries', () => {
    const cache = new MemoryTranscriptCache(60000)
    cache.set('a', 'en', makeTranscript('a', 'en'))
    cache.set('a', 'vi', makeTranscript('a', 'vi'))
    cache.set('b', 'en', makeTranscript('b', 'en'))
    cache.clear('a')
    expect(cache.get('a', 'en')).toBeNull()
    expect(cache.get('a', 'vi')).toBeNull()
    expect(cache.get('b', 'en')).not.toBeNull()
  })

  it('evicts oldest entry when exceeding maxEntries', () => {
    const cache = new MemoryTranscriptCache(60000, 2)
    cache.set('a', 'en', makeTranscript('a', 'en'))
    cache.set('b', 'en', makeTranscript('b', 'en'))
    cache.set('c', 'en', makeTranscript('c', 'en'))
    expect(cache.get('a', 'en')).toBeNull()
    expect(cache.get('b', 'en')).not.toBeNull()
    expect(cache.get('c', 'en')).not.toBeNull()
  })
})
