import { describe, it, expect, vi, beforeEach } from 'vitest'
import { TranscriptService } from '../TranscriptService'
import { MemoryTranscriptCache } from '../MemoryTranscriptCache'
import {
  PlayerResponseNotFoundError,
  CaptionTrackNotFoundError,
  TranscriptError,
} from '../types'
import type { IYoutubeTranscriptRepository, IMemoryTranscriptCache } from '../interfaces'
import type { Transcript, TranscriptSegment } from '../types'

function makeTranscript(videoId: string, language = 'en'): Transcript {
  return {
    videoId,
    language,
    isAutoGenerated: true,
    segments: [{ text: 'Test', start: 0, end: 1, duration: 1 }],
    fullText: 'Test',
  }
}

describe('TranscriptService', () => {
  let mockRepo: IYoutubeTranscriptRepository
  let memoryCache: IMemoryTranscriptCache

  beforeEach(() => {
    mockRepo = {
      fetch: vi.fn().mockResolvedValue(makeTranscript('abc')),
    }
    memoryCache = new MemoryTranscriptCache(60000)
  })

  it('rejects empty videoId', async () => {
    const service = new TranscriptService(mockRepo, memoryCache)
    const result = await service.getTranscript('')
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.error.code).toBe('PLAYER_RESPONSE_NOT_FOUND')
  })

  it('returns cached transcript on hit', async () => {
    const transcript = makeTranscript('abc')
    memoryCache.set('abc', 'en', transcript)
    const service = new TranscriptService(mockRepo, memoryCache)
    const result = await service.getTranscript('abc')
    expect(result.ok).toBe(true)
    if (result.ok) {
      expect(result.data).toEqual(transcript)
      expect(result.source).toBe('cache')
    }
  })

  it('fetches and caches on cache miss', async () => {
    const service = new TranscriptService(mockRepo, memoryCache)
    const result = await service.getTranscript('abc')
    expect(result.ok).toBe(true)
    if (result.ok) {
      expect(result.data.videoId).toBe('abc')
      expect(result.source).toBe('network')
    }
    expect(mockRepo.fetch).toHaveBeenCalledWith('abc', undefined)
  })

  it('skips cache with forceRefresh', async () => {
    memoryCache.set('abc', 'en', makeTranscript('abc'))
    const service = new TranscriptService(mockRepo, memoryCache)
    const result = await service.getTranscript('abc', { forceRefresh: true })
    expect(result.ok).toBe(true)
    if (result.ok) expect(result.source).toBe('network')
    expect(mockRepo.fetch).toHaveBeenCalled()
  })

  it('maps repository errors to error results', async () => {
    mockRepo.fetch = vi.fn().mockRejectedValue(new CaptionTrackNotFoundError())
    const service = new TranscriptService(mockRepo, memoryCache)
    const result = await service.getTranscript('abc')
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.error.code).toBe('CAPTION_TRACK_NOT_FOUND')
  })

  it('maps unknown errors to UNKNOWN', async () => {
    mockRepo.fetch = vi.fn().mockRejectedValue(new Error('Something weird'))
    const service = new TranscriptService(mockRepo, memoryCache)
    const result = await service.getTranscript('abc')
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.error.code).toBe('UNKNOWN')
  })

  it('clearCache clears memory cache', () => {
    memoryCache.set('a', 'en', makeTranscript('a'))
    memoryCache.set('b', 'en', makeTranscript('b'))
    const service = new TranscriptService(mockRepo, memoryCache)
    service.clearCache('a')
    expect(memoryCache.get('a', 'en')).toBeNull()
    expect(memoryCache.get('b', 'en')).not.toBeNull()
  })

  it('clearCache without argument clears all', () => {
    memoryCache.set('a', 'en', makeTranscript('a'))
    memoryCache.set('b', 'en', makeTranscript('b'))
    const service = new TranscriptService(mockRepo, memoryCache)
    service.clearCache()
    expect(memoryCache.get('a', 'en')).toBeNull()
    expect(memoryCache.get('b', 'en')).toBeNull()
  })

  it('passes language option to repository', async () => {
    const service = new TranscriptService(mockRepo, memoryCache)
    await service.getTranscript('abc', { language: 'vi' })
    expect(mockRepo.fetch).toHaveBeenCalledWith('abc', { language: 'vi' })
  })

  it('handles aborted signal', async () => {
    const controller = new AbortController()
    controller.abort()
    const service = new TranscriptService(mockRepo, memoryCache)
    const result = await service.getTranscript('abc', { signal: controller.signal })
    expect(result.ok).toBe(false)
    if (!result.ok) expect(result.error.code).toBe('PLAYER_RESPONSE_NOT_FOUND')
  })
})
