import { describe, it, expect } from 'vitest'
import { YoutubeTranscriptRepository } from '../YoutubeTranscriptRepository'
import {
  PlayerResponseNotFoundError,
  CaptionTrackNotFoundError,
  TranscriptDownloadError,
  TranscriptParseError,
  PlayerInitTimeoutError,
} from '../types'
import type { CaptionTrack, TranscriptSegment } from '../types'
import type {
  IPlayerReadinessDetector,
  IPlayerResponseProvider,
  ICaptionTrackSelector,
  ICaptionResolver,
  ITranscriptParser,
} from '../interfaces'

function makeTrack(o: Partial<CaptionTrack> & { languageCode: string }): CaptionTrack {
  return { baseUrl: `https://x.com/${o.languageCode}`, languageCode: o.languageCode, kind: 'auto', name: o.languageCode, isTranslatable: false, vssId: '', ...o }
}

function readyPass(): IPlayerReadinessDetector {
  return { waitUntilReady: async () => {} }
}

function readyThrows(err: Error): IPlayerReadinessDetector {
  return { waitUntilReady: async () => { throw err } }
}

function providerReturns(tracks: CaptionTrack[]): IPlayerResponseProvider {
  return { getFreshResponse: async () => ({ captionTracks: tracks }) }
}

function repo(
  readiness: IPlayerReadinessDetector = readyPass(),
  provider: IPlayerResponseProvider = providerReturns([]),
  selector: ICaptionTrackSelector = { select: () => null },
  resolver: ICaptionResolver = { resolve: async () => '' },
  parser: ITranscriptParser = { parse: () => [] },
) {
  return new YoutubeTranscriptRepository(readiness, provider, selector, resolver, parser)
}

describe('YoutubeTranscriptRepository', () => {
  it('throws on readiness timeout', async () => {
    await expect(repo(readyThrows(new PlayerInitTimeoutError())).fetch('abc')).rejects.toThrow(PlayerInitTimeoutError)
  })

  it('throws when provider returns null', async () => {
    await expect(repo(readyPass(), { getFreshResponse: async () => null }).fetch('abc')).rejects.toThrow(PlayerResponseNotFoundError)
  })

  it('throws when no tracks', async () => {
    await expect(repo(readyPass(), providerReturns([])).fetch('abc')).rejects.toThrow(PlayerResponseNotFoundError)
  })

  it('throws when selector returns null', async () => {
    const s: ICaptionTrackSelector = { select: () => null }
    await expect(repo(readyPass(), providerReturns([makeTrack({ languageCode: 'en' })]), s).fetch('abc')).rejects.toThrow(CaptionTrackNotFoundError)
  })

  it('throws on resolve failure', async () => {
    const t = makeTrack({ languageCode: 'en' })
    const r: ICaptionResolver = { resolve: async () => { throw new Error('fail') } }
    await expect(repo(readyPass(), providerReturns([t]), { select: () => t }, r).fetch('abc')).rejects.toThrow(TranscriptDownloadError)
  })

  it('throws on parse failure', async () => {
    const t = makeTrack({ languageCode: 'en' })
    await expect(repo(readyPass(), providerReturns([t]), { select: () => t }, { resolve: async () => '<x/>' }, { parse: () => [] }).fetch('abc')).rejects.toThrow(TranscriptParseError)
  })

  it('succeeds', async () => {
    const t = makeTrack({ languageCode: 'en', kind: 'manual' })
    const segs: TranscriptSegment[] = [{ text: 'Hi', start: 0, end: 1, duration: 1 }]
    const r = repo(readyPass(), providerReturns([t]), { select: () => t }, { resolve: async () => '<xml/>' }, { parse: () => segs })
    const result = await r.fetch('abc')
    expect(result.videoId).toBe('abc')
    expect(result.isAutoGenerated).toBe(false)
    expect(result.fullText).toBe('Hi')
  })

  it('rejects empty videoId', async () => {
    await expect(repo().fetch('')).rejects.toThrow(PlayerResponseNotFoundError)
  })
})
