import { describe, it, expect, vi, beforeEach } from 'vitest'
import { ProactiveEventBus } from '../services/proactiveEventBus'
import { ProactiveMessageStorage } from '../services/proactiveMessageStorage'
import {
  onLessonCompleted,
  onRepeatedMistakes,
  onInactivityDetected,
  onVocabularySaved,
  onTextSelected,
  onWeeklyReviewReady,
  onMonthlyReviewReady,
  onDailyPlanReady,
  onUnfinishedLesson,
  onMockTestReady,
  onStreakMilestone,
  triggerDailyCheck,
  isTriggerOnCooldown,
  canTrigger,
  resetRecentTriggers,
  type TriggerResult,
} from '../services/proactiveMessageTriggers'
import type { ProactiveMessageSettings } from '../types/proactiveMessage'

beforeEach(() => {
  localStorage.clear()
  resetRecentTriggers()
})

function setMaxMessages(n: number): void {
  const s = ProactiveMessageStorage.getDefaultSettings()
  s.maxMessagesPerDay = n
  ProactiveMessageStorage.saveSettings(s)
}

function setLearnerProfileData(profile: Record<string, unknown>): void {
  localStorage.setItem('ielts-learner-profile', JSON.stringify(profile))
}

function hasTriggerType(result: TriggerResult, triggerType: string): boolean {
  return result.messages.some(m => m.triggerType === triggerType)
}

function findTriggerType(result: TriggerResult, triggerType: string) {
  return result.messages.find(m => m.triggerType === triggerType)
}

// ─── onLessonCompleted ─────────────────────────────────────────────────────────

describe('onLessonCompleted', () => {
  it('generates a lesson_completed message', () => {
    const result = onLessonCompleted('IELTS Writing Task 2')
    expect(result.generated).toBeGreaterThanOrEqual(1)
    expect(hasTriggerType(result, 'lesson_completed')).toBe(true)
    const msg = findTriggerType(result, 'lesson_completed')!
    expect(msg.message).toContain('IELTS Writing Task 2')
  })

  it('emits the message via event bus', () => {
    const handler = vi.fn()
    const unsub = ProactiveEventBus.onNewMessage(handler)

    onLessonCompleted('Reading Practice 3')

    expect(handler).toHaveBeenCalled()
    const emittedTypes = handler.mock.calls.map((c: unknown[]) => (c[0] as { triggerType: string }).triggerType)
    expect(emittedTypes).toContain('lesson_completed')
    unsub()
  })

  it('returns empty result when throttled (simulate max messages reached)', () => {
    const today = new Date().toISOString()
    for (let i = 0; i < 5; i++) {
      ProactiveMessageStorage.addMessage({
        triggerType: 'due_review',
        category: 'vocabulary-review',
        title: `Existing ${i}`,
        message: 'Fill messages for today',
        priority: 'low',
        autoGenerated: true,
      })
    }
    const result = onLessonCompleted('Speaking Part 2')
    expect(result.generated).toBe(0)
  })
})

// ─── onRepeatedMistakes ────────────────────────────────────────────────────────

describe('onRepeatedMistakes', () => {
  it('generates a mistake_pattern_detected message for many mistakes', () => {
    const result = onRepeatedMistakes(8)
    expect(result.generated).toBeGreaterThanOrEqual(1)
    expect(hasTriggerType(result, 'mistake_pattern_detected')).toBe(true)
  })

  it('returns empty for few mistakes', () => {
    const result = onRepeatedMistakes(2)
    expect(hasTriggerType(result, 'mistake_pattern_detected')).toBe(false)
  })

  it('emits messages via event bus', () => {
    const handler = vi.fn()
    const unsub = ProactiveEventBus.onNewMessage(handler)

    onRepeatedMistakes(10)

    const mistakeMsgs = handler.mock.calls.filter(
      (c: unknown[]) => (c[0] as { triggerType: string }).triggerType === 'mistake_pattern_detected',
    )
    expect(mistakeMsgs.length).toBeGreaterThanOrEqual(1)
    unsub()
  })
})

// ─── onInactivityDetected ──────────────────────────────────────────────────────

describe('onInactivityDetected', () => {
  it('generates low_activity message for 2+ inactive days', () => {
    const result = onInactivityDetected(3)
    expect(result.generated).toBeGreaterThanOrEqual(1)
    expect(hasTriggerType(result, 'low_activity')).toBe(true)
  })

  it('generates inactive_days message for missed study days', () => {
    const result = onInactivityDetected(5)
    expect(hasTriggerType(result, 'inactive_days')).toBe(true)
  })

  it('returns empty for 0-1 inactive days', () => {
    const result = onInactivityDetected(1)
    expect(hasTriggerType(result, 'low_activity')).toBe(false)
    expect(hasTriggerType(result, 'inactive_days')).toBe(false)
  })
})

// ─── onVocabularySaved ─────────────────────────────────────────────────────────

describe('onVocabularySaved', () => {
  it('generates saved_word_exercise for 3+ saved words', () => {
    const result = onVocabularySaved(8)
    expect(result.generated).toBeGreaterThanOrEqual(1)
    expect(hasTriggerType(result, 'saved_word_exercise')).toBe(true)
  })

  it('does not generate for fewer than 3 words', () => {
    const result = onVocabularySaved(2)
    expect(hasTriggerType(result, 'saved_word_exercise')).toBe(false)
  })
})

// ─── onTextSelected ────────────────────────────────────────────────────────────

describe('onTextSelected', () => {
  it('generates new_content_saved message', () => {
    const text = 'The IELTS Academic Reading test is designed to assess a wide range of reading skills. These include reading for gist, reading for main ideas, reading for detail, skimming, understanding logical argument and recognising writers opinions attitudes and purpose.'
    const result = onTextSelected(text, 'IELTS Reading Overview')
    expect(result.generated).toBeGreaterThanOrEqual(1)
    expect(hasTriggerType(result, 'new_content_saved')).toBe(true)
  })

  it('works with article title', () => {
    const result = onTextSelected('Some short text', 'Vocabulary Builder')
    expect(result.generated).toBeGreaterThanOrEqual(1)
  })
})

// ─── onWeeklyReviewReady ──────────────────────────────────────────────────────

describe('onWeeklyReviewReady', () => {
  it('generates weekly_review message', () => {
    const result = onWeeklyReviewReady('improving')
    expect(result.generated).toBeGreaterThanOrEqual(1)
    expect(hasTriggerType(result, 'weekly_review')).toBe(true)
  })

  it('includes accuracy trend in message for improving trend', () => {
    setLearnerProfileData({ averageAccuracy: 78 })
    const result = onWeeklyReviewReady('improving')
    const msg = findTriggerType(result, 'weekly_review')
    expect(msg?.message).toContain('up')
    expect(msg?.message).toContain('78')
  })

  it('works with declining trend', () => {
    const result = onWeeklyReviewReady('declining')
    const msg = findTriggerType(result, 'weekly_review')
    expect(msg).toBeDefined()
  })

  it('stores the review date in localStorage', () => {
    onWeeklyReviewReady()
    const stored = localStorage.getItem('ielts-last-weekly-review-date')
    expect(stored).toBeTruthy()
  })
})

// ─── onMonthlyReviewReady ──────────────────────────────────────────────────────

describe('onMonthlyReviewReady', () => {
  it('generates monthly_review message', () => {
    const result = onMonthlyReviewReady()
    expect(result.generated).toBeGreaterThanOrEqual(1)
    expect(hasTriggerType(result, 'monthly_review')).toBe(true)
  })
})

// ─── onDailyPlanReady ──────────────────────────────────────────────────────────

describe('onDailyPlanReady', () => {
  it('generates daily_plan_ready message', () => {
    const result = onDailyPlanReady()
    expect(result.generated).toBeGreaterThanOrEqual(1)
    expect(hasTriggerType(result, 'daily_plan_ready')).toBe(true)
  })
})

// ─── onUnfinishedLesson ───────────────────────────────────────────────────────

describe('onUnfinishedLesson', () => {
  it('generates unfinished_lesson message', () => {
    const result = onUnfinishedLesson('Vocabulary Builder 3')
    expect(result.generated).toBeGreaterThanOrEqual(1)
    expect(hasTriggerType(result, 'unfinished_lesson')).toBe(true)
    const msg = findTriggerType(result, 'unfinished_lesson')!
    expect(msg.message).toContain('Vocabulary Builder 3')
  })
})

// ─── onMockTestReady ─────────────────────────────────────────────────────────

describe('onMockTestReady', () => {
  it('generates mock_test_ready message', () => {
    const result = onMockTestReady()
    expect(result.generated).toBeGreaterThanOrEqual(1)
    expect(hasTriggerType(result, 'mock_test_ready')).toBe(true)
  })
})

// ─── onStreakMilestone ─────────────────────────────────────────────────────────

describe('onStreakMilestone', () => {
  it('generates study_streak message for 3+ day streak', () => {
    const result = onStreakMilestone(7)
    expect(result.generated).toBeGreaterThanOrEqual(1)
    expect(hasTriggerType(result, 'study_streak')).toBe(true)
  })

  it('does not generate for short streaks', () => {
    const result = onStreakMilestone(2)
    expect(hasTriggerType(result, 'study_streak')).toBe(false)
  })
})

// ─── triggerDailyCheck ─────────────────────────────────────────────────────────

describe('triggerDailyCheck', () => {
  it('generates daily_plan_ready message', () => {
    const result = triggerDailyCheck()
    expect(result.generated).toBeGreaterThanOrEqual(1)
  })

  it('generates multiple messages when multiple conditions met', () => {
    localStorage.setItem('ielts-due-vocabulary-count', '10')
    localStorage.setItem('ielts-due-mistake-count', '5')
    const result = triggerDailyCheck()
    expect(result.generated).toBeGreaterThanOrEqual(2)
  })
})

// ─── Trigger cooldown ──────────────────────────────────────────────────────────

describe('isTriggerOnCooldown', () => {
  it('returns false for unknown trigger name', () => {
    expect(isTriggerOnCooldown('unknown_trigger')).toBe(false)
  })

  it('returns false for a trigger that was never called', () => {
    expect(isTriggerOnCooldown('onLessonCompleted')).toBe(false)
  })

  it('returns true for a trigger recently called via canTrigger', () => {
    expect(canTrigger('onRepeatedMistakes')).toBe(true)
    expect(isTriggerOnCooldown('onRepeatedMistakes')).toBe(true)
  })

  it('returns false after reset', () => {
    canTrigger('onRepeatedMistakes')
    resetRecentTriggers()
    expect(isTriggerOnCooldown('onRepeatedMistakes')).toBe(false)
  })
})

// ─── canTrigger ────────────────────────────────────────────────────────────────

describe('canTrigger', () => {
  it('returns true when settings enabled and no cooldown', () => {
    const result = canTrigger('onLessonCompleted')
    expect(result).toBe(true)
  })

  it('returns false when called again within cooldown', () => {
    canTrigger('onLessonCompleted')
    expect(canTrigger('onLessonCompleted')).toBe(false)
  })

  it('allows different triggers independently', () => {
    canTrigger('onLessonCompleted')
    expect(canTrigger('onRepeatedMistakes')).toBe(true)
  })
})

// ─── Emitted messages are persisted ──────────────────────────────────────────

describe('message persistence', () => {
  it('messages from triggers are stored in ProactiveMessageStorage', () => {
    const before = ProactiveMessageStorage.loadMessages().length
    onLessonCompleted('Listening Test 1')
    const after = ProactiveMessageStorage.loadMessages().length
    expect(after).toBeGreaterThan(before)
  })

  it('storage contains the correct trigger type', () => {
    onMockTestReady()
    const stored = ProactiveMessageStorage.getMessagesByTriggerType('mock_test_ready')
    expect(stored.length).toBeGreaterThanOrEqual(1)
  })

  it('messages are retrievable after multiple triggers', () => {
    setMaxMessages(10)
    onLessonCompleted('Writing Task 1')
    onVocabularySaved(5)
    onRepeatedMistakes(10)
    const all = ProactiveMessageStorage.loadMessages()
    const types = new Set(all.map(m => m.triggerType))
    expect(types.has('lesson_completed')).toBe(true)
    expect(types.has('saved_word_exercise')).toBe(true)
    expect(types.has('mistake_pattern_detected')).toBe(true)
  })
})

// ─── No excessive/duplicate message generation ─────────────────────────────────

describe('duplicate prevention', () => {
  it('cooldown prevents duplicate triggers within time window', () => {
    const first = onLessonCompleted('Lesson 1')
    expect(first.generated).toBeGreaterThanOrEqual(1)

    const second = onLessonCompleted('Lesson 1 again')
    expect(second.generated).toBe(0)
  })

  it('different trigger types are not blocked by each other', () => {
    onLessonCompleted('Lesson 1')
    const vocabResult = onVocabularySaved(10)
    expect(vocabResult.generated).toBeGreaterThanOrEqual(1)
  })
})

// ─── TriggerResult shape ──────────────────────────────────────────────────────

describe('TriggerResult shape', () => {
  it('returns expected fields', () => {
    const result = onVocabularySaved(5)
    expect(result).toHaveProperty('generated')
    expect(result).toHaveProperty('throttled')
    expect(result).toHaveProperty('messages')
    expect(Array.isArray(result.messages)).toBe(true)
  })

  it('generated count matches messages.length', () => {
    const result = onDailyPlanReady()
    expect(result.generated).toBe(result.messages.length)
  })
})
