import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest'
import {
  canSendProactiveMessage,
  getQuietHoursRemainingMs,
  shouldDelayToQuietHours,
  getNextAllowedTime,
  isCurrentlyQuietHours,
  generateProactiveMessagesWithSettings,
} from '../services/proactiveMessageEngine'
import {
  DEFAULT_PROACTIVE_SETTINGS,
} from '../types/proactiveMessage'
import type { ProactiveMessageSettings, ProactiveMessage } from '../types/proactiveMessage'

const defaultSettings: ProactiveMessageSettings = { ...DEFAULT_PROACTIVE_SETTINGS }

function makeMessage(overrides: Partial<ProactiveMessage> = {}): ProactiveMessage {
  return {
    id: 'msg-1',
    triggerType: 'due_review',
    category: 'vocabulary-review',
    title: 'Test message',
    message: 'Test body',
    priority: 'medium',
    isRead: false,
    isDismissed: false,
    isSnoozed: false,
    autoGenerated: true,
    createdAt: new Date().toISOString(),
    ...overrides,
  }
}

function todayAt(hours: number, minutes: number = 0): Date {
  const d = new Date()
  d.setHours(hours, minutes, 0, 0)
  return d
}

// ─── getQuietHoursRemainingMs ─────────────────────────────────────────────────

describe('getQuietHoursRemainingMs', () => {
  beforeEach(() => {
    vi.useFakeTimers()
  })

  afterEach(() => {
    vi.useRealTimers()
  })

  it('returns 0 when not in quiet hours', () => {
    vi.setSystemTime(todayAt(12, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '22:00',
      quietHoursEnd: '08:00',
    }
    expect(getQuietHoursRemainingMs(settings)).toBe(0)
  })

  it('returns remaining ms during overnight quiet hours', () => {
    vi.setSystemTime(todayAt(1, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '22:00',
      quietHoursEnd: '08:00',
    }
    const remaining = getQuietHoursRemainingMs(settings)
    expect(remaining).toBe(7 * 60 * 60 * 1000)
  })

  it('returns remaining ms during same-day quiet hours', () => {
    vi.setSystemTime(todayAt(14, 30))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '13:00',
      quietHoursEnd: '15:00',
    }
    const remaining = getQuietHoursRemainingMs(settings)
    expect(remaining).toBe(30 * 60 * 1000)
  })

  it('returns 0 when quiet hours are disabled (0-0 range)', () => {
    vi.setSystemTime(todayAt(12, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '00:00',
      quietHoursEnd: '00:00',
    }
    expect(getQuietHoursRemainingMs(settings)).toBe(0)
  })

  it('handles quiet hours that span midnight at the boundary', () => {
    vi.setSystemTime(todayAt(22, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '22:00',
      quietHoursEnd: '06:00',
    }
    const remaining = getQuietHoursRemainingMs(settings)
    expect(remaining).toBe(8 * 60 * 60 * 1000)
  })
})

// ─── shouldDelayToQuietHours ─────────────────────────────────────────────────

describe('shouldDelayToQuietHours', () => {
  beforeEach(() => {
    vi.useFakeTimers()
  })

  afterEach(() => {
    vi.useRealTimers()
  })

  it('returns null when not in quiet hours', () => {
    vi.setSystemTime(todayAt(12, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '22:00',
      quietHoursEnd: '08:00',
    }
    expect(shouldDelayToQuietHours(settings)).toBeNull()
  })

  it('returns delay info when in quiet hours', () => {
    vi.setSystemTime(todayAt(23, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '22:00',
      quietHoursEnd: '07:00',
    }
    const result = shouldDelayToQuietHours(settings)
    expect(result).not.toBeNull()
    expect(result!.isInQuietHours).toBe(true)
    expect(result!.remainingMs).toBe(8 * 60 * 60 * 1000)
    expect(result!.endsAt).toBeTruthy()
  })
})

// ─── canSendProactiveMessage ──────────────────────────────────────────────────

describe('canSendProactiveMessage', () => {
  beforeEach(() => {
    vi.useFakeTimers()
  })

  afterEach(() => {
    vi.useRealTimers()
  })

  it('returns cannot send when tutor is disabled', () => {
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      enabled: false,
    }
    const result = canSendProactiveMessage(settings, [])
    expect(result.canSend).toBe(false)
    expect(result.reason).toContain('disabled')
    expect(result.delayUntil).toBeUndefined()
  })

  it('returns cannot send during quiet hours with delay info', () => {
    vi.setSystemTime(todayAt(23, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '22:00',
      quietHoursEnd: '07:00',
    }
    const result = canSendProactiveMessage(settings, [])
    expect(result.canSend).toBe(false)
    expect(result.reason).toContain('Quiet hours')
    expect(result.delayUntil).toBeTruthy()
  })

  it('returns cannot send when max messages per day reached', () => {
    vi.setSystemTime(todayAt(12, 0))
    const pastDate = new Date()
    pastDate.setHours(pastDate.getHours() - 1)
    const existingMessages = Array.from({ length: 5 }, (_, i) =>
      makeMessage({ id: `existing-${i}`, createdAt: pastDate.toISOString() }),
    )
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      maxMessagesPerDay: 5,
    }
    const result = canSendProactiveMessage(settings, existingMessages)
    expect(result.canSend).toBe(false)
    expect(result.reason).toContain('Max messages')
    expect(result.messagesToday).toBe(5)
    expect(result.maxPerDay).toBe(5)
  })

  it('returns can send when under daily limit and not in quiet hours', () => {
    vi.setSystemTime(todayAt(12, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      maxMessagesPerDay: 5,
      quietHoursStart: '22:00',
      quietHoursEnd: '08:00',
    }
    const result = canSendProactiveMessage(settings, [])
    expect(result.canSend).toBe(true)
    expect(result.reason).toBeUndefined()
    expect(result.messagesToday).toBe(0)
    expect(result.maxPerDay).toBe(5)
  })

  it('returns can send when some messages already sent but under limit', () => {
    vi.setSystemTime(todayAt(12, 0))
    const pastDate = new Date()
    pastDate.setHours(pastDate.getHours() - 2)
    const existingMessages = [
      makeMessage({ id: 'm1', createdAt: pastDate.toISOString() }),
      makeMessage({ id: 'm2', createdAt: pastDate.toISOString() }),
    ]
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      maxMessagesPerDay: 5,
    }
    const result = canSendProactiveMessage(settings, existingMessages)
    expect(result.canSend).toBe(true)
    expect(result.messagesToday).toBe(2)
  })

  it('daily limit of 0 means no messages can be sent', () => {
    vi.setSystemTime(todayAt(12, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      maxMessagesPerDay: 0,
    }
    const result = canSendProactiveMessage(settings, [])
    expect(result.canSend).toBe(false)
    expect(result.reason).toContain('Max messages')
  })

  it('does not count yesterday messages toward today limit', () => {
    vi.setSystemTime(todayAt(12, 0))
    const yesterday = new Date()
    yesterday.setDate(yesterday.getDate() - 1)
    const existingMessages = Array.from({ length: 10 }, (_, i) =>
      makeMessage({ id: `old-${i}`, createdAt: yesterday.toISOString() }),
    )
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      maxMessagesPerDay: 5,
    }
    const result = canSendProactiveMessage(settings, existingMessages)
    expect(result.canSend).toBe(true)
    expect(result.messagesToday).toBe(0)
  })
})

// ─── getNextAllowedTime ───────────────────────────────────────────────────────

describe('getNextAllowedTime', () => {
  beforeEach(() => {
    vi.useFakeTimers()
  })

  afterEach(() => {
    vi.useRealTimers()
  })

  it('returns quiet hours end time when in quiet hours', () => {
    vi.setSystemTime(todayAt(23, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '22:00',
      quietHoursEnd: '07:00',
    }
    const next = getNextAllowedTime(settings, [])
    expect(next).toBeTruthy()
    const nextDate = new Date(next!)
    expect(nextDate.getHours()).toBe(7)
    expect(nextDate.getMinutes()).toBe(0)
  })

  it('returns tomorrow midnight when daily limit reached', () => {
    vi.setSystemTime(todayAt(12, 0))
    const pastDate = new Date()
    pastDate.setHours(pastDate.getHours() - 1)
    const existingMessages = Array.from({ length: 5 }, (_, i) =>
      makeMessage({ id: `m-${i}`, createdAt: pastDate.toISOString() }),
    )
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      maxMessagesPerDay: 5,
    }
    const next = getNextAllowedTime(settings, existingMessages)
    expect(next).toBeTruthy()
    const nextDate = new Date(next!)
    const tomorrow = new Date()
    tomorrow.setDate(tomorrow.getDate() + 1)
    tomorrow.setHours(0, 0, 0, 0)
    expect(nextDate.getTime()).toBe(tomorrow.getTime())
  })

  it('returns undefined when can send now', () => {
    vi.setSystemTime(todayAt(12, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      maxMessagesPerDay: 5,
      quietHoursStart: '22:00',
      quietHoursEnd: '08:00',
    }
    expect(getNextAllowedTime(settings, [])).toBeUndefined()
  })
})

// ─── isCurrentlyQuietHours (edge cases) ──────────────────────────────────────

describe('isCurrentlyQuietHours', () => {
  beforeEach(() => {
    vi.useFakeTimers()
  })

  afterEach(() => {
    vi.useRealTimers()
  })

  it('returns true for overnight quiet hours at 3 AM', () => {
    vi.setSystemTime(todayAt(3, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '22:00',
      quietHoursEnd: '08:00',
    }
    expect(isCurrentlyQuietHours(settings)).toBe(true)
  })

  it('returns false just outside quiet hours at 8:01 AM', () => {
    vi.setSystemTime(todayAt(8, 1))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '22:00',
      quietHoursEnd: '08:00',
    }
    expect(isCurrentlyQuietHours(settings)).toBe(false)
  })

  it('returns true at exact quiet hours start boundary', () => {
    vi.setSystemTime(todayAt(22, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '22:00',
      quietHoursEnd: '08:00',
    }
    expect(isCurrentlyQuietHours(settings)).toBe(true)
  })

  it('returns false for same-day quiet hours when outside', () => {
    vi.setSystemTime(todayAt(10, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '13:00',
      quietHoursEnd: '15:00',
    }
    expect(isCurrentlyQuietHours(settings)).toBe(false)
  })

  it('returns true for same-day quiet hours when inside', () => {
    vi.setSystemTime(todayAt(14, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '13:00',
      quietHoursEnd: '15:00',
    }
    expect(isCurrentlyQuietHours(settings)).toBe(true)
  })
})

// ─── generateProactiveMessagesWithSettings (frequency extensions) ────────────

describe('generateProactiveMessagesWithSettings frequency enforcement', () => {
  beforeEach(() => {
    vi.useFakeTimers()
  })

  afterEach(() => {
    vi.useRealTimers()
  })

  it('returns delayUntil and nextAllowedTime during quiet hours', () => {
    vi.setSystemTime(todayAt(23, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '22:00',
      quietHoursEnd: '07:00',
    }
    const result = generateProactiveMessagesWithSettings(
      { dueVocabularyCount: 10 },
      settings,
      [],
    )
    expect(result.messages).toEqual([])
    expect(result.reason).toContain('Quiet hours')
    expect(result.delayUntil).toBeTruthy()
    expect(result.nextAllowedTime).toBeTruthy()
  })

  it('returns nextAllowedTime when daily limit reached', () => {
    vi.setSystemTime(todayAt(12, 0))
    const pastDate = new Date()
    pastDate.setHours(pastDate.getHours() - 1)
    const existingMessages = Array.from({ length: 3 }, (_, i) =>
      makeMessage({ id: `m-${i}`, createdAt: pastDate.toISOString() }),
    )
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      maxMessagesPerDay: 3,
    }
    const result = generateProactiveMessagesWithSettings(
      { dueVocabularyCount: 10 },
      settings,
      existingMessages,
    )
    expect(result.messages).toEqual([])
    expect(result.reason).toContain('Max messages')
    expect(result.nextAllowedTime).toBeTruthy()
  })

  it('sends messages when all checks pass and returns no nextAllowedTime', () => {
    vi.setSystemTime(todayAt(12, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      maxMessagesPerDay: 5,
      quietHoursStart: '22:00',
      quietHoursEnd: '08:00',
    }
    const result = generateProactiveMessagesWithSettings(
      { dueVocabularyCount: 10 },
      settings,
      [],
    )
    expect(result.messages.length).toBeGreaterThanOrEqual(1)
    expect(result.reason).toBeUndefined()
    expect(result.delayUntil).toBeUndefined()
    expect(result.nextAllowedTime).toBeUndefined()
  })
})

// ─── canSendProactiveMessage edge cases ──────────────────────────────────────

describe('canSendProactiveMessage edge cases', () => {
  beforeEach(() => {
    vi.useFakeTimers()
  })

  afterEach(() => {
    vi.useRealTimers()
  })

  it('handles empty settings defaults correctly', () => {
    vi.setSystemTime(todayAt(12, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      maxMessagesPerDay: 1,
    }
    const result = canSendProactiveMessage(settings, [])
    expect(result.canSend).toBe(true)
    expect(result.maxPerDay).toBe(1)
  })

  it('quiet hours start equals end means no quiet hours', () => {
    vi.setSystemTime(todayAt(12, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '00:00',
      quietHoursEnd: '00:00',
    }
    expect(isCurrentlyQuietHours(settings)).toBe(false)
    const result = canSendProactiveMessage(settings, [])
    expect(result.canSend).toBe(true)
  })

  it('quiet hours covering the entire day blocks all messages', () => {
    vi.setSystemTime(todayAt(12, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '00:00',
      quietHoursEnd: '23:59',
    }
    expect(isCurrentlyQuietHours(settings)).toBe(true)
    const result = canSendProactiveMessage(settings, [])
    expect(result.canSend).toBe(false)
    expect(result.reason).toContain('Quiet hours')
  })

  it('quiet hours end boundary at midnight works correctly', () => {
    vi.setSystemTime(todayAt(23, 30))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '23:00',
      quietHoursEnd: '06:00',
    }
    const result = canSendProactiveMessage(settings, [])
    expect(result.canSend).toBe(false)
    expect(result.delayUntil).toBeTruthy()
  })

  it('quiet hours start at midnight end at 6 AM works at 3 AM', () => {
    vi.setSystemTime(todayAt(3, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '00:00',
      quietHoursEnd: '06:00',
    }
    const result = canSendProactiveMessage(settings, [])
    expect(result.canSend).toBe(false)
    expect(result.reason).toContain('Quiet hours')
  })

  it('quiet hours start at midnight end at 6 AM works at 7 AM', () => {
    vi.setSystemTime(todayAt(7, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '00:00',
      quietHoursEnd: '06:00',
    }
    const result = canSendProactiveMessage(settings, [])
    expect(result.canSend).toBe(true)
  })
})

// ─── getQuietHoursRemainingMs edge cases ──────────────────────────────────────

describe('getQuietHoursRemainingMs edge cases', () => {
  beforeEach(() => {
    vi.useFakeTimers()
  })

  afterEach(() => {
    vi.useRealTimers()
  })

  it('returns correct remaining for quiet hours ending at midnight', () => {
    vi.setSystemTime(todayAt(22, 30))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '22:00',
      quietHoursEnd: '00:00',
    }
    const remaining = getQuietHoursRemainingMs(settings)
    expect(remaining).toBe(90 * 60 * 1000)
  })

  it('returns correct remaining for quiet hours starting at midnight', () => {
    vi.setSystemTime(todayAt(0, 30))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '00:00',
      quietHoursEnd: '06:00',
    }
    const remaining = getQuietHoursRemainingMs(settings)
    expect(remaining).toBe(5.5 * 60 * 60 * 1000)
  })

  it('returns correct remaining at the very start of quiet hours', () => {
    vi.setSystemTime(todayAt(22, 0))
    const settings: ProactiveMessageSettings = {
      ...defaultSettings,
      quietHoursStart: '22:00',
      quietHoursEnd: '06:00',
    }
    const remaining = getQuietHoursRemainingMs(settings)
    expect(remaining).toBe(8 * 60 * 60 * 1000)
  })
})
