import type {
  ProactiveMessage,
  ProactiveMessageInput,
  ProactiveMessageSettings,
  ProactiveMessageTriggerType,
  ProactiveMessageUpdate,
} from '../types/proactiveMessage'
import {
  proactiveMessageSchema,
  proactiveMessageSettingsSchema,
  DEFAULT_PROACTIVE_SETTINGS,
} from '../types/proactiveMessage'
import { generateId } from '../utils/id'

const MESSAGES_KEY = 'ielts-proactive-messages-v2'
const SETTINGS_KEY = 'ielts-proactive-settings-v2'
const MAX_MESSAGES = 500

function safeJsonParse<T>(raw: string | null, fallback: T): T {
  if (!raw) return fallback
  try {
    return JSON.parse(raw) as T
  } catch {
    return fallback
  }
}

function safeJsonSet(key: string, value: unknown): void {
  try {
    localStorage.setItem(key, JSON.stringify(value))
  } catch {
    /* storage full or unavailable */
  }
}

// ─── Settings ────────────────────────────────────────────────────────────────

function loadSettingsRaw(): ProactiveMessageSettings {
  const raw = localStorage.getItem(SETTINGS_KEY)
  if (!raw) return { ...DEFAULT_PROACTIVE_SETTINGS }
  const parsed = safeJsonParse<Partial<ProactiveMessageSettings>>(raw, {})
  const result = proactiveMessageSettingsSchema.safeParse({
    ...DEFAULT_PROACTIVE_SETTINGS,
    ...parsed,
  })
  if (result.success) return result.data
  return { ...DEFAULT_PROACTIVE_SETTINGS }
}

function saveSettingsRaw(settings: ProactiveMessageSettings): void {
  safeJsonSet(SETTINGS_KEY, settings)
}

// ─── Messages ────────────────────────────────────────────────────────────────

function loadMessagesRaw(): ProactiveMessage[] {
  const raw = localStorage.getItem(MESSAGES_KEY)
  if (!raw) return []
  const parsed = safeJsonParse<unknown>(raw, [])
  if (!Array.isArray(parsed)) return []
  const valid: ProactiveMessage[] = []
  for (const item of parsed) {
    const result = proactiveMessageSchema.safeParse(item)
    if (result.success) {
      valid.push(result.data)
    }
  }
  return valid
}

function saveMessagesRaw(messages: ProactiveMessage[]): void {
  safeJsonSet(MESSAGES_KEY, messages)
}

// ─── Service ─────────────────────────────────────────────────────────────────

export const ProactiveMessageStorage = {
  // ── Settings ────────────────────────────────────────────────────────────

  loadSettings(): ProactiveMessageSettings {
    return loadSettingsRaw()
  },

  saveSettings(settings: ProactiveMessageSettings): void {
    const withTimestamp = { ...settings, updatedAt: new Date().toISOString() }
    const result = proactiveMessageSettingsSchema.safeParse(withTimestamp)
    if (!result.success) {
      console.warn('[ProactiveMessageStorage] Invalid settings schema', result.error.issues)
      return
    }
    saveSettingsRaw(result.data)
  },

  resetSettings(): ProactiveMessageSettings {
    const defaults = { ...DEFAULT_PROACTIVE_SETTINGS }
    saveSettingsRaw(defaults)
    return defaults
  },

  getDefaultSettings(): ProactiveMessageSettings {
    return { ...DEFAULT_PROACTIVE_SETTINGS }
  },

  // ── Message CRUD ────────────────────────────────────────────────────────

  loadMessages(): ProactiveMessage[] {
    return loadMessagesRaw()
  },

  getMessage(id: string): ProactiveMessage | undefined {
    const messages = loadMessagesRaw()
    return messages.find(m => m.id === id)
  },

  addMessage(input: ProactiveMessageInput): ProactiveMessage {
    const messages = loadMessagesRaw()
    const now = new Date().toISOString()
    const message: ProactiveMessage = {
      ...input,
      id: generateId(),
      isRead: false,
      isDismissed: false,
      isSnoozed: false,
      autoGenerated: false,
      createdAt: now,
    }
    const result = proactiveMessageSchema.safeParse(message)
    if (!result.success) {
      console.warn('[ProactiveMessageStorage] Invalid message schema', result.error.issues)
      throw new Error('Failed to create proactive message: invalid data')
    }
    messages.push(result.data)
    saveMessagesRaw(messages.slice(-MAX_MESSAGES))
    return result.data
  },

  updateMessage(id: string, updates: ProactiveMessageUpdate): ProactiveMessage | undefined {
    const messages = loadMessagesRaw()
    const index = messages.findIndex(m => m.id === id)
    if (index === -1) return undefined
    const now = new Date().toISOString()
    const withTimestamps = {
      ...updates,
      readAt: updates.isRead && !updates.readAt ? now : updates.readAt,
      dismissedAt: updates.isDismissed && !updates.dismissedAt ? now : updates.dismissedAt,
    }
    messages[index] = { ...messages[index], ...withTimestamps }
    const result = proactiveMessageSchema.safeParse(messages[index])
    if (!result.success) return undefined
    messages[index] = result.data
    saveMessagesRaw(messages)
    return result.data
  },

  deleteMessage(id: string): boolean {
    const messages = loadMessagesRaw()
    const index = messages.findIndex(m => m.id === id)
    if (index === -1) return false
    messages.splice(index, 1)
    saveMessagesRaw(messages)
    return true
  },

  clearMessages(): void {
    try {
      localStorage.removeItem(MESSAGES_KEY)
    } catch { /* noop */ }
  },

  // ── Query ───────────────────────────────────────────────────────────────

  getUnreadCount(): number {
    return loadMessagesRaw().filter(m => !m.isRead && !m.isDismissed && !m.isSnoozed).length
  },

  getMessagesByStatus(filters: {
    isRead?: boolean
    isDismissed?: boolean
    isSnoozed?: boolean
  }): ProactiveMessage[] {
    return loadMessagesRaw().filter(m => {
      return (
        (filters.isRead === undefined || m.isRead === filters.isRead) &&
        (filters.isDismissed === undefined || m.isDismissed === filters.isDismissed) &&
        (filters.isSnoozed === undefined || m.isSnoozed === filters.isSnoozed)
      )
    })
  },

  getMessagesByTriggerType(type: ProactiveMessageTriggerType): ProactiveMessage[] {
    return loadMessagesRaw().filter(m => m.triggerType === type)
  },

  getMessagesByDateRange(from: string, to: string): ProactiveMessage[] {
    return loadMessagesRaw().filter(m => {
      const date = new Date(m.createdAt).getTime()
      return date >= new Date(from).getTime() && date <= new Date(to).getTime()
    })
  },

  getTodayMessages(): ProactiveMessage[] {
    const today = new Date().toDateString()
    return loadMessagesRaw().filter(m => new Date(m.createdAt).toDateString() === today)
  },

  getPendingMessages(): ProactiveMessage[] {
    const now = Date.now()
    return loadMessagesRaw().filter(m => {
      if (m.isDismissed) return false
      if (m.isRead) return false
      if (m.isSnoozed && m.snoozedUntil && new Date(m.snoozedUntil).getTime() > now) return false
      if (m.expiresAt && new Date(m.expiresAt).getTime() < now) return false
      return true
    })
  },

  getExpiredMessages(): ProactiveMessage[] {
    const now = Date.now()
    return loadMessagesRaw().filter(m => m.expiresAt && new Date(m.expiresAt).getTime() < now)
  },

  // ── Mark shortcuts ──────────────────────────────────────────────────────

  markAsRead(id: string): ProactiveMessage | undefined {
    return this.updateMessage(id, { isRead: true, readAt: new Date().toISOString() })
  },

  markAsDismissed(id: string): ProactiveMessage | undefined {
    return this.updateMessage(id, { isDismissed: true, dismissedAt: new Date().toISOString() })
  },

  markAsSnoozed(id: string, until: string): ProactiveMessage | undefined {
    return this.updateMessage(id, { isSnoozed: true, snoozedUntil: until })
  },

  markAllAsRead(): void {
    const messages = loadMessagesRaw()
    const now = new Date().toISOString()
    for (const m of messages) {
      if (!m.isRead) {
        m.isRead = true
        m.readAt = now
      }
    }
    saveMessagesRaw(messages)
  },

  // ── Cleanup ─────────────────────────────────────────────────────────────

  cleanup(maxMessages: number = MAX_MESSAGES): number {
    const messages = loadMessagesRaw()
    if (messages.length <= maxMessages) return 0
    const sorted = messages.sort(
      (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
    )
    const removed = sorted.length - maxMessages
    saveMessagesRaw(sorted.slice(0, maxMessages))
    return removed
  },

  clearExpired(): number {
    const messages = loadMessagesRaw()
    const before = messages.length
    const remaining = messages.filter(
      m => !m.expiresAt || new Date(m.expiresAt).getTime() >= Date.now(),
    )
    const removed = before - remaining.length
    if (removed > 0) saveMessagesRaw(remaining)
    return removed
  },

  // ── Export / Import ─────────────────────────────────────────────────────

  exportToJson(): string {
    const data = {
      version: 2,
      messages: loadMessagesRaw(),
      settings: loadSettingsRaw(),
      exportedAt: new Date().toISOString(),
    }
    return JSON.stringify(data, null, 2)
  },

  importFromJson(json: string): { success: boolean; error?: string; messagesImported: number } {
    try {
      const parsed = JSON.parse(json)
      if (!parsed || typeof parsed !== 'object') {
        return { success: false, error: 'Invalid format', messagesImported: 0 }
      }
      let importedCount = 0
      if (Array.isArray(parsed.messages)) {
        const valid: ProactiveMessage[] = []
        for (const item of parsed.messages) {
          const result = proactiveMessageSchema.safeParse(item)
          if (result.success) {
            valid.push(result.data)
            importedCount++
          }
        }
        saveMessagesRaw(valid)
      }
      if (parsed.settings && typeof parsed.settings === 'object') {
        const result = proactiveMessageSettingsSchema.safeParse({
          ...DEFAULT_PROACTIVE_SETTINGS,
          ...parsed.settings,
        })
        if (result.success) {
          saveSettingsRaw(result.data)
        }
      }
      return { success: true, messagesImported: importedCount }
    } catch {
      return { success: false, error: 'Invalid JSON', messagesImported: 0 }
    }
  },
}

export default ProactiveMessageStorage
