import type { ProactiveMessage, ProactiveMessageInput, ProactiveMessageTriggerType } from '../types/proactiveMessage'
import { ProactiveMessageStorage } from './proactiveMessageStorage'
import { ProactiveEventBus } from './proactiveEventBus'
import { generateProactiveMessages } from './proactiveMessageEngine'
import type { ProactiveEngineInput, LearnerProfile } from './proactiveMessageEngine'
import { generateId } from '../utils/id'

// ─── Data types ──────────────────────────────────────────────────────────────

export interface WeeklyReviewData {
  studyMinutes: number
  tasksCompleted: number
  sessionsCompleted: number
  daysActive: number
  streak: number
  accuracy: number
  vocabularyReviewed: number
  mistakesReviewed: number
  weakSkills: string[]
  trend: 'improving' | 'declining' | 'stable'
}

export interface MonthlyReviewData {
  studyMinutes: number
  tasksCompleted: number
  totalSessions: number
  daysActive: number
  longestStreak: number
  averageAccuracy: number
  vocabularySaved: number
  vocabularyMastered: number
  mistakesResolved: number
  weakSkills: string[]
  strongestSkill: string
  trend: 'improving' | 'declining' | 'stable'
  targetBand?: number
  currentBand?: number
  examDate?: string
}

export interface ReviewSchedule {
  lastWeeklyReview?: string
  lastMonthlyReview?: string
}

export interface ReviewGenerationResult {
  weekly: ProactiveMessage[]
  monthly: ProactiveMessage[]
  weeklyGenerated: boolean
  monthlyGenerated: boolean
}

// ─── Constants ───────────────────────────────────────────────────────────────

const SCHEDULE_KEY = 'ielts-progress-review-schedule'
const WEEKLY_INTERVAL_MS = 7 * 24 * 60 * 60 * 1000
const MONTHLY_INTERVAL_MS = 30 * 24 * 60 * 60 * 1000

// ─── Schedule management ────────────────────────────────────────────────────

function loadSchedule(): ReviewSchedule {
  try {
    const raw = localStorage.getItem(SCHEDULE_KEY)
    if (!raw) return {}
    return JSON.parse(raw) as ReviewSchedule
  } catch {
    return {}
  }
}

function saveSchedule(schedule: ReviewSchedule): void {
  try {
    localStorage.setItem(SCHEDULE_KEY, JSON.stringify(schedule))
  } catch { /* noop */ }
}

// ─── Review schedule queries ────────────────────────────────────────────────

export function isWeeklyReviewDue(schedule?: ReviewSchedule): boolean {
  const s = schedule ?? loadSchedule()
  if (!s.lastWeeklyReview) return true
  return Date.now() - new Date(s.lastWeeklyReview).getTime() >= WEEKLY_INTERVAL_MS
}

export function isMonthlyReviewDue(schedule?: ReviewSchedule): boolean {
  const s = schedule ?? loadSchedule()
  if (!s.lastMonthlyReview) return true
  return Date.now() - new Date(s.lastMonthlyReview).getTime() >= MONTHLY_INTERVAL_MS
}

export function getDaysSinceLastWeeklyReview(): number {
  const s = loadSchedule()
  if (!s.lastWeeklyReview) return -1
  return Math.floor((Date.now() - new Date(s.lastWeeklyReview).getTime()) / (1000 * 60 * 60 * 24))
}

export function getDaysSinceLastMonthlyReview(): number {
  const s = loadSchedule()
  if (!s.lastMonthlyReview) return -1
  return Math.floor((Date.now() - new Date(s.lastMonthlyReview).getTime()) / (1000 * 60 * 60 * 24))
}

// ─── Message creation ────────────────────────────────────────────────────────

function createReviewMessage(
  triggerType: 'weekly_review' | 'monthly_review',
  title: string,
  message: string,
  priority: 'high' | 'medium' | 'low',
  sourceData?: string,
): ProactiveMessage {
  return {
    id: generateId(),
    triggerType,
    category: 'progress-report',
    title,
    message,
    priority,
    isRead: false,
    isDismissed: false,
    isSnoozed: false,
    autoGenerated: true,
    createdAt: new Date().toISOString(),
    sourceData,
  }
}

function buildWeeklyReviewMessage(data: WeeklyReviewData): ProactiveMessage {
  const weakSkillNote = data.weakSkills.length > 0
    ? ` Your weakest area${data.weakSkills.length > 1 ? 's are' : ' is'} ${data.weakSkills.slice(0, 3).join(', ')} — focus on ${data.weakSkills[0]} practice this week.`
    : ''

  let trendMessage: string
  if (data.trend === 'improving') {
    trendMessage = `Your accuracy is ${data.accuracy}% and trending up — great progress!`
  } else if (data.trend === 'declining') {
    trendMessage = `Your accuracy is ${data.accuracy}%. Let's identify what needs extra attention.`
  } else {
    trendMessage = `Your accuracy is ${data.accuracy}%. Keep practicing to build momentum.`
  }

  const message = [
    `This week you studied for ${data.studyMinutes} minutes across ${data.daysActive} active days, completing ${data.tasksCompleted} tasks and ${data.sessionsCompleted} sessions.`,
    data.streak > 0 ? ` You maintained a ${data.streak}-day streak.` : '',
    ` ${trendMessage}`,
    data.vocabularyReviewed > 0 ? ` You reviewed ${data.vocabularyReviewed} vocabulary words.` : '',
    data.mistakesReviewed > 0 ? ` ${data.mistakesReviewed} mistakes were reviewed.` : '',
    weakSkillNote,
  ].join('')

  return createReviewMessage(
    'weekly_review',
    `Weekly progress review — Week ${getWeekNumber()}`,
    message,
    data.trend === 'declining' ? 'medium' : 'low',
    `weekly:minutes=${data.studyMinutes},tasks=${data.tasksCompleted},days=${data.daysActive},streak=${data.streak},accuracy=${data.accuracy},trend=${data.trend}`,
  )
}

function buildMonthlyReviewMessage(data: MonthlyReviewData): ProactiveMessage {
  const weakSkillNote = data.weakSkills.length > 0
    ? ` Your weakest area${data.weakSkills.length > 1 ? 's are' : ' is'} ${data.weakSkills.slice(0, 3).join(', ')}, while your strongest is ${data.strongestSkill}.`
    : ''

  const bandNote = data.targetBand && data.currentBand
    ? ` You're currently at band ${data.currentBand}, working toward ${data.targetBand}. ${data.currentBand >= data.targetBand ? 'You\'ve reached your target!' : `That's a gap of ${(data.targetBand - data.currentBand).toFixed(1)} bands to close.`}`
    : ''

  const vocabNote = data.vocabularyMastered > 0
    ? ` You've mastered ${data.vocabularyMastered} of ${data.vocabularySaved} saved vocabulary words (${Math.round((data.vocabularyMastered / data.vocabularySaved) * 100)}% mastery).`
    : data.vocabularySaved > 0
      ? ` You've saved ${data.vocabularySaved} vocabulary words — keep reviewing to master them.`
      : ''

  let trendMessage: string
  if (data.trend === 'improving') {
    trendMessage = `Your overall trend is improving with ${data.averageAccuracy}% average accuracy — excellent dedication!`
  } else if (data.trend === 'declining') {
    trendMessage = `Your overall trend shows some decline at ${data.averageAccuracy}% average accuracy. Let's focus on strengthening your foundation.`
  } else {
    trendMessage = `Your overall trend is stable at ${data.averageAccuracy}% average accuracy. Consistent effort will drive improvement.`
  }

  const message = [
    `Over the past 30 days, you studied for ${data.studyMinutes} minutes across ${data.daysActive} active days, completing ${data.tasksCompleted} tasks in ${data.totalSessions} sessions.`,
    data.longestStreak > 0 ? ` Your longest streak was ${data.longestStreak} days.` : '',
    ` ${trendMessage}`,
    bandNote,
    vocabNote,
    data.mistakesResolved > 0 ? ` You resolved ${data.mistakesResolved} mistakes this month.` : '',
    weakSkillNote,
  ].join('')

  return createReviewMessage(
    'monthly_review',
    `Monthly progress review — ${getMonthLabel()}`,
    message,
    'medium',
    `monthly:minutes=${data.studyMinutes},tasks=${data.tasksCompleted},sessions=${data.totalSessions},days=${data.daysActive},streak=${data.longestStreak},accuracy=${data.averageAccuracy},trend=${data.trend}`,
  )
}

function getWeekNumber(): number {
  const now = new Date()
  const start = new Date(now.getFullYear(), 0, 1)
  const diff = now.getTime() - start.getTime()
  return Math.ceil((diff / (1000 * 60 * 60 * 24) + start.getDay() + 1) / 7)
}

function getMonthLabel(): string {
  return new Date().toLocaleString('en-US', { month: 'long', year: 'numeric' })
}

function buildEngineInputForReview(
  data: WeeklyReviewData | MonthlyReviewData,
  isMonthly: boolean,
): ProactiveEngineInput {
  const isMonthlyData = 'averageAccuracy' in data
  const profile: LearnerProfile = {
    averageAccuracy: isMonthlyData ? data.averageAccuracy : data.accuracy,
    weakSkills: data.weakSkills,
    studyStreak: isMonthlyData ? data.longestStreak : data.streak,
    targetBand: isMonthlyData ? data.targetBand : undefined,
    currentBand: isMonthlyData ? data.currentBand : undefined,
    examDate: isMonthlyData ? data.examDate : undefined,
  }

  return {
    isWeeklyReviewReady: !isMonthly,
    isMonthlyReviewReady: isMonthly,
    recentAccuracyTrend: data.trend,
    learnerProfile: profile,
  }
}

// ─── Main service ────────────────────────────────────────────────────────────

export const ProactiveProgressReview = {
  loadSchedule,
  saveSchedule,

  isWeeklyReviewDue,
  isMonthlyReviewDue,
  getDaysSinceLastWeeklyReview,
  getDaysSinceLastMonthlyReview,

  generateWeeklyReview(data: WeeklyReviewData): ProactiveMessage {
    return buildWeeklyReviewMessage(data)
  },

  generateMonthlyReview(data: MonthlyReviewData): ProactiveMessage {
    return buildMonthlyReviewMessage(data)
  },

  checkAndGenerate(
    weeklyData?: WeeklyReviewData,
    monthlyData?: MonthlyReviewData,
  ): ReviewGenerationResult {
    const schedule = loadSchedule()
    const result: ReviewGenerationResult = {
      weekly: [],
      monthly: [],
      weeklyGenerated: false,
      monthlyGenerated: false,
    }

    function persist(msg: ProactiveMessage, target: ProactiveMessage[]): void {
      const input: ProactiveMessageInput = {
        triggerType: msg.triggerType as ProactiveMessageTriggerType,
        category: msg.category,
        title: msg.title,
        message: msg.message,
        priority: msg.priority,
        action: msg.action,
        skill: msg.skill,
        sourceData: msg.sourceData,
        expiresAt: msg.expiresAt,
      }
      const stored = ProactiveMessageStorage.addMessage(input)
      target.push(stored)
      ProactiveEventBus.emitNewMessage(stored as never)
    }

    if (isWeeklyReviewDue(schedule) && weeklyData) {
      const msg = buildWeeklyReviewMessage(weeklyData)
      const engineInput = buildEngineInputForReview(weeklyData, false)
      const engineMsgs = generateProactiveMessages(engineInput) as ProactiveMessage[]
      const now = new Date().toISOString()
      persist({ ...msg, id: generateId(), autoGenerated: true, createdAt: now }, result.weekly)
      for (const e of engineMsgs) {
        if (e.triggerType === 'weekly_review') {
          persist(e, result.weekly)
        }
      }
      schedule.lastWeeklyReview = now
      result.weeklyGenerated = true
    }

    if (isMonthlyReviewDue(schedule) && monthlyData) {
      const msg = buildMonthlyReviewMessage(monthlyData)
      const engineInput = buildEngineInputForReview(monthlyData, true)
      const engineMsgs = generateProactiveMessages(engineInput) as ProactiveMessage[]
      const now = new Date().toISOString()
      persist({ ...msg, id: generateId(), autoGenerated: true, createdAt: now }, result.monthly)
      for (const e of engineMsgs) {
        if (e.triggerType === 'monthly_review') {
          persist(e, result.monthly)
        }
      }
      schedule.lastMonthlyReview = now
      result.monthlyGenerated = true
    }

    saveSchedule(schedule)
    return result
  },

  forceWeeklyReview(data: WeeklyReviewData): ProactiveMessage {
    const msg = buildWeeklyReviewMessage(data)
    const engineInput = buildEngineInputForReview(data, false)
    const engineMsgs = generateProactiveMessages(engineInput) as ProactiveMessage[]
    const now = new Date().toISOString()

    function persist(m: ProactiveMessage): ProactiveMessage {
      const input: ProactiveMessageInput = {
        triggerType: m.triggerType as ProactiveMessageTriggerType,
        category: m.category,
        title: m.title,
        message: m.message,
        priority: m.priority,
        action: m.action,
        skill: m.skill,
        sourceData: m.sourceData,
        expiresAt: m.expiresAt,
      }
      const stored = ProactiveMessageStorage.addMessage(input)
      ProactiveEventBus.emitNewMessage(stored as never)
      return stored
    }

    let lastStored = persist({ ...msg, id: generateId(), autoGenerated: true, createdAt: now })
    for (const e of engineMsgs) {
      if (e.triggerType === 'weekly_review') {
        lastStored = persist(e)
      }
    }

    const schedule = loadSchedule()
    schedule.lastWeeklyReview = now
    saveSchedule(schedule)
    return lastStored
  },

  forceMonthlyReview(data: MonthlyReviewData): ProactiveMessage {
    const msg = buildMonthlyReviewMessage(data)
    const engineInput = buildEngineInputForReview(data, true)
    const engineMsgs = generateProactiveMessages(engineInput) as ProactiveMessage[]
    const now = new Date().toISOString()

    function persist(m: ProactiveMessage): ProactiveMessage {
      const input: ProactiveMessageInput = {
        triggerType: m.triggerType as ProactiveMessageTriggerType,
        category: m.category,
        title: m.title,
        message: m.message,
        priority: m.priority,
        action: m.action,
        skill: m.skill,
        sourceData: m.sourceData,
        expiresAt: m.expiresAt,
      }
      const stored = ProactiveMessageStorage.addMessage(input)
      ProactiveEventBus.emitNewMessage(stored as never)
      return stored
    }

    let lastStored = persist({ ...msg, id: generateId(), autoGenerated: true, createdAt: now })
    for (const e of engineMsgs) {
      if (e.triggerType === 'monthly_review') {
        lastStored = persist(e)
      }
    }

    const schedule = loadSchedule()
    schedule.lastMonthlyReview = now
    saveSchedule(schedule)
    return lastStored
  },

  getSchedule(): ReviewSchedule {
    return loadSchedule()
  },

  resetSchedule(): void {
    try {
      localStorage.removeItem(SCHEDULE_KEY)
    } catch { /* noop */ }
  },

  getDefaultWeeklyData(): WeeklyReviewData {
    return {
      studyMinutes: 240,
      tasksCompleted: 12,
      sessionsCompleted: 8,
      daysActive: 5,
      streak: 4,
      accuracy: 72,
      vocabularyReviewed: 18,
      mistakesReviewed: 6,
      weakSkills: ['writing', 'speaking'],
      trend: 'improving',
    }
  },

  getDefaultMonthlyData(): MonthlyReviewData {
    return {
      studyMinutes: 960,
      tasksCompleted: 48,
      totalSessions: 32,
      daysActive: 20,
      longestStreak: 7,
      averageAccuracy: 70,
      vocabularySaved: 45,
      vocabularyMastered: 22,
      mistakesResolved: 15,
      weakSkills: ['writing', 'listening'],
      strongestSkill: 'reading',
      trend: 'stable',
      targetBand: 7,
      currentBand: 6,
    }
  },
}

export default ProactiveProgressReview
