import { z } from 'zod'

// ─── Trigger types ───────────────────────────────────────────────────────────

export const proactiveMessageTriggerTypeSchema = z.enum([
  'due_review',
  'missed_task',
  'weak_skill_warning',
  'exam_countdown',
  'new_content_saved',
  'study_streak',
  'low_activity',
  'daily_plan_ready',
  'mistake_pattern_detected',
  'topic_practice_suggestion',
  'lesson_completed',
  'inactive_days',
  'weekly_review',
  'monthly_review',
  'unfinished_lesson',
  'saved_word_exercise',
  'daily_tip',
  'mock_test_ready',
  'exam_date_reminder',
  'progress_celebration',
  'study_session_suggestion',
])

export type ProactiveMessageTriggerType = z.infer<typeof proactiveMessageTriggerTypeSchema>

// ─── Categories ──────────────────────────────────────────────────────────────

export const proactiveMessageCategorySchema = z.enum([
  'vocabulary-review',
  'mistake-review',
  'study-plan',
  'speaking-practice',
  'writing-practice',
  'reading-practice',
  'listening-practice',
  'exam-countdown',
  'motivation',
  'saved-content',
  'daily-tip',
  'progress-report',
  'suggestion',
])

export type ProactiveMessageCategory = z.infer<typeof proactiveMessageCategorySchema>

// ─── Priority ────────────────────────────────────────────────────────────────

export const proactiveMessagePrioritySchema = z.enum(['high', 'medium', 'low'])
export type ProactiveMessagePriority = z.infer<typeof proactiveMessagePrioritySchema>

// ─── Action ──────────────────────────────────────────────────────────────────

export const proactiveMessageActionSchema = z.object({
  type: z.string().min(1),
  label: z.string().min(1),
  payload: z.record(z.string(), z.unknown()).optional(),
})

export type ProactiveMessageAction = z.infer<typeof proactiveMessageActionSchema>

// ─── Interaction types ───────────────────────────────────────────────────────

export const interactionTypeSchema = z.enum(['dismiss', 'snooze', 'action_click', 'feedback'])
export type InteractionType = z.infer<typeof interactionTypeSchema>

export const feedbackRatingSchema = z.enum(['helpful', 'not-helpful', 'none'])
export type FeedbackRating = z.infer<typeof feedbackRatingSchema>

export const interactionRecordSchema = z.object({
  type: interactionTypeSchema,
  timestamp: z.string().refine(v => !isNaN(Date.parse(v)), { message: 'Invalid ISO date string' }),
  detail: z.string().optional(),
  metadata: z.record(z.string(), z.unknown()).optional(),
})

export type InteractionRecord = z.infer<typeof interactionRecordSchema>

// ─── Reason metadata ─────────────────────────────────────────────────────────

export const proactiveMessageReasonSchema = z.object({
  triggerEvent: z.string().min(1),
  relatedData: z.record(z.string(), z.unknown()).optional(),
  explanation: z.string().min(1),
})

export type ProactiveMessageReason = z.infer<typeof proactiveMessageReasonSchema>

// ─── ProactiveMessage ────────────────────────────────────────────────────────

export const proactiveMessageSchema = z.object({
  id: z.string().min(1),
  triggerType: proactiveMessageTriggerTypeSchema,
  category: proactiveMessageCategorySchema,
  title: z.string().min(1),
  message: z.string().min(1),
  priority: proactiveMessagePrioritySchema,
  action: proactiveMessageActionSchema.optional(),
  reason: proactiveMessageReasonSchema.optional(),
  skill: z.string().optional(),
  sourceData: z.string().optional(),
  expiresAt: z.string().optional(),
  isRead: z.boolean(),
  isDismissed: z.boolean(),
  isSnoozed: z.boolean(),
  snoozedUntil: z.string().optional(),
  autoGenerated: z.boolean(),
  createdAt: z.string().refine(v => !isNaN(Date.parse(v)), { message: 'Invalid ISO date string' }),
  readAt: z.string().optional(),
  dismissedAt: z.string().optional(),
  interactionHistory: z.array(interactionRecordSchema).optional(),
  feedback: feedbackRatingSchema.optional(),
  dismissReason: z.string().optional(),
  actionClicked: z.string().optional(),
  lastInteractedAt: z.string().optional(),
})

export type ProactiveMessage = z.infer<typeof proactiveMessageSchema>

// ─── Settings ────────────────────────────────────────────────────────────────

export const tutorToneSchema = z.enum(['friendly', 'strict', 'motivational', 'simple', 'vietnamese'])
export type TutorTone = z.infer<typeof tutorToneSchema>

export const notificationChannelSchema = z.enum(['in-app', 'browser', 'extension'])
export type NotificationChannel = z.infer<typeof notificationChannelSchema>

export const automationLevelSchema = z.enum(['manual', 'semi-automatic', 'automatic'])
export type AutomationLevel = z.infer<typeof automationLevelSchema>

export const reminderFrequencySchema = z.enum(['daily', 'every-other-day', 'weekly', 'smart'])
export type ReminderFrequency = z.infer<typeof reminderFrequencySchema>

export const proactiveMessageSettingsSchema = z.object({
  enabled: z.boolean(),
  tone: tutorToneSchema,
  preferredStudyTime: z.string(),
  dailyReminderTime: z.string(),
  weakSkillPriority: z.array(z.string()),
  notificationChannels: z.array(notificationChannelSchema),
  automationLevel: automationLevelSchema,
  autoSuggestExercises: z.boolean(),
  autoWeeklyReview: z.boolean(),
  reminderFrequency: reminderFrequencySchema,
  categories: z.record(z.string(), z.boolean()),
  quietHoursStart: z.string(),
  quietHoursEnd: z.string(),
  maxMessagesPerDay: z.number().int().positive(),
  lastRemindedAt: z.string().optional(),
  updatedAt: z.string().refine(v => !isNaN(Date.parse(v)), { message: 'Invalid ISO date string' }),
})

export type ProactiveMessageSettings = z.infer<typeof proactiveMessageSettingsSchema>

// ─── Defaults ────────────────────────────────────────────────────────────────

export const DEFAULT_PROACTIVE_SETTINGS: ProactiveMessageSettings = {
  enabled: true,
  tone: 'friendly',
  preferredStudyTime: '09:00',
  dailyReminderTime: '09:00',
  weakSkillPriority: [],
  notificationChannels: ['in-app'],
  automationLevel: 'semi-automatic',
  autoSuggestExercises: true,
  autoWeeklyReview: true,
  reminderFrequency: 'smart',
  categories: {
    'vocabulary-review': true,
    'mistake-review': true,
    'study-plan': true,
    'speaking-practice': true,
    'writing-practice': true,
    'reading-practice': true,
    'listening-practice': true,
    'exam-countdown': true,
    'motivation': true,
    'saved-content': true,
    'daily-tip': true,
    'progress-report': true,
    'suggestion': true,
  },
  quietHoursStart: '22:00',
  quietHoursEnd: '08:00',
  maxMessagesPerDay: 5,
  updatedAt: new Date().toISOString(),
}

// ─── Input types (for creating messages) ─────────────────────────────────────

export type ProactiveMessageInput = Omit<
  ProactiveMessage,
  'id' | 'createdAt' | 'isRead' | 'isDismissed' | 'isSnoozed' | 'autoGenerated'
>

export type ProactiveMessageUpdate = Partial<
  Pick<ProactiveMessage, 'isRead' | 'isDismissed' | 'isSnoozed' | 'snoozedUntil' | 'readAt' | 'dismissedAt' | 'interactionHistory' | 'feedback' | 'dismissReason' | 'actionClicked' | 'lastInteractedAt'>
>

export type ProactiveMessageInteractionResult = {
  message: ProactiveMessage | undefined
  success: boolean
  interaction: InteractionRecord
}

export interface InteractionStats {
  totalMessages: number
  totalDismissed: number
  totalSnoozed: number
  totalActionClicks: number
  totalFeedback: number
  helpfulCount: number
  notHelpfulCount: number
  dismissReasonCounts: Record<string, number>
  actionClickCounts: Record<string, number>
  interactionRate: number
}
