import type { Exercise, ReadingExercise, ListeningExercise, WritingExercise, SpeakingExercise, GrammarExercise, VocabularyExercise, SavedContentExercise, MistakeReviewExercise } from '../domain/types'
import { createDefaultDifficultyProfile } from '../domain/types'

const NOW = new Date().toISOString()

export function createSeedFullReadingTest(): ReadingExercise {
  return {
    id: 'seed-reading-full-test-001',
    schemaVersion: 1,
    blueprintVersion: '1.0.0',
    module: 'reading',
    mode: 'full_test',
    family: 'objective_questions',
    title: 'Academic Reading Full Test',
    description: 'Complete IELTS Academic Reading test with 3 passages and 40 questions',
    instructions: ['You have 60 minutes to complete all three sections.', 'Write your answers on the answer sheet.'],
    source: 'seed_data',
    status: 'active',
    estimatedDurationSeconds: 3600,
    difficulty: createDefaultDifficultyProfile(),
    learningObjectives: [],
    tags: ['ielts', 'academic', 'full-test'],
    ieltsVariant: 'academic',
    createdAt: NOW,
    updatedAt: NOW,
    passages: [
      {
        id: 'passage-1',
        title: 'The Rise of Urban Farming',
        content: 'Urban farming has become increasingly popular in cities around the world...',
        wordCount: 900,
        questionGroups: [
          {
            id: 'rg-1-1',
            type: 'true_false_not_given',
            startNumber: 1,
            endNumber: 5,
            instructions: ['Do the following statements agree with the information given in Reading Passage 1?'],
            questions: Array.from({ length: 5 }, (_, i) => ({
              id: `q-rt-p1-${i + 1}`,
              number: i + 1,
              type: 'true_false_not_given' as const,
              prompt: `Statement ${i + 1} about urban farming`,
              statement: `Statement ${i + 1} about urban farming`,
              correctAnswer: (['true', 'false', 'not_given'] as const)[i % 3],
              points: 1,
              difficulty: { difficulty: 0.5 },
              learningObjectiveIds: [],
            })),
          },
          {
            id: 'rg-1-2',
            type: 'matching_headings',
            startNumber: 6,
            endNumber: 13,
            instructions: ['Reading Passage 1 has paragraphs A-H. Choose the correct heading for each paragraph.'],
            questions: Array.from({ length: 8 }, (_, i) => ({
              id: `q-mh-p1-${i + 1}`,
              number: i + 6,
              type: 'matching' as const,
              subtype: 'matching_headings' as const,
              prompt: `Match heading for paragraph ${String.fromCharCode(65 + i)}`,
              leftItems: [{ id: `para-${i}`, content: `Paragraph ${String.fromCharCode(65 + i)}` }],
              rightItems: Array.from({ length: 10 }, (_, j) => ({ id: `heading-${j}`, content: `Heading ${j + 1}` })),
              correctMatches: { [`para-${i}`]: `heading-${i}` },
              points: 1,
              difficulty: { difficulty: 0.5 },
              learningObjectiveIds: [],
            })),
          },
        ],
      },
      {
        id: 'passage-2',
        title: 'The Psychology of Decision Making',
        content: 'Every day, humans make thousands of decisions...',
        wordCount: 950,
        questionGroups: [
          {
            id: 'rg-2-1',
            type: 'multiple_choice',
            startNumber: 14,
            endNumber: 26,
            instructions: ['Choose the correct letter, A, B, C or D.'],
            questions: Array.from({ length: 13 }, (_, i) => ({
              id: `q-mc-p2-${i + 1}`,
              number: i + 14,
              type: 'multiple_choice' as const,
              prompt: `Question ${i + 14} about decision making`,
              options: ['Option A', 'Option B', 'Option C', 'Option D'],
              correctIndex: i % 4,
              points: 1,
              difficulty: { difficulty: 0.5 },
              learningObjectiveIds: [],
            })),
          },
        ],
      },
      {
        id: 'passage-3',
        title: 'Climate Change and Marine Ecosystems',
        content: 'The oceans are absorbing more carbon dioxide than previously thought...',
        wordCount: 1000,
        questionGroups: [
          {
            id: 'rg-3-1',
            type: 'completion',
            startNumber: 27,
            endNumber: 40,
            instructions: ['Complete the sentences below. Write NO MORE THAN TWO WORDS from the passage for each answer.'],
            questions: Array.from({ length: 14 }, (_, i) => ({
              id: `q-comp-p3-${i + 1}`,
              number: i + 27,
              type: 'completion' as const,
              subtype: 'sentence_completion' as const,
              prompt: `Complete: The marine ecosystem _____`,
              text: `The marine ecosystem _____`,
              gaps: [{
                id: `gap-p3-${i}`,
                position: 0,
                correctAnswer: `answer ${i + 27}`,
                acceptableAlternatives: [],
                caseSensitive: false,
              }],
              wordLimit: 2,
              points: 1,
              difficulty: { difficulty: 0.6 },
              learningObjectiveIds: [],
            })),
          },
        ],
      },
    ],
    totalQuestionCount: 40,
  }
}

export function createSeedFullListeningTest(): ListeningExercise {
  return {
    id: 'seed-listening-full-test-001',
    schemaVersion: 1,
    blueprintVersion: '1.0.0',
    module: 'listening',
    mode: 'full_test',
    family: 'interactive_listening',
    title: 'IELTS Listening Full Test',
    description: 'Complete IELTS Listening test with 4 parts and 40 questions',
    instructions: ['You will hear a number of recordings.', 'Answer the questions as you listen.'],
    source: 'seed_data',
    status: 'active',
    estimatedDurationSeconds: 2400,
    difficulty: createDefaultDifficultyProfile(),
    learningObjectives: [],
    tags: ['ielts', 'full-test'],
    createdAt: NOW,
    updatedAt: NOW,
    parts: Array.from({ length: 4 }, (_, partIdx) => ({
      id: `listening-part-${partIdx + 1}`,
      partNumber: partIdx + 1,
      description: `Part ${partIdx + 1}`,
      audioDurationSeconds: 480,
      questionGroups: [
        {
          id: `lg-${partIdx + 1}-1`,
          type: 'completion',
          startNumber: partIdx * 10 + 1,
          endNumber: (partIdx + 1) * 10,
          instructions: ['Complete the notes below. Write NO MORE THAN TWO WORDS AND/OR A NUMBER for each answer.'],
          questions: Array.from({ length: 10 }, (_, qIdx) => ({
            id: `q-l-p${partIdx + 1}-${qIdx + 1}`,
            number: partIdx * 10 + qIdx + 1,
            type: 'completion' as const,
            subtype: 'note_completion' as const,
            prompt: `Note: _____`,
            text: `Note: _____`,
            gaps: [{
              id: `gap-l-${partIdx}-${qIdx}`,
              position: 0,
              correctAnswer: `answer ${partIdx * 10 + qIdx + 1}`,
              acceptableAlternatives: [],
              caseSensitive: false,
            }],
            wordLimit: 3,
            points: 1,
            difficulty: { difficulty: 0.4 + partIdx * 0.1 },
            learningObjectiveIds: [],
          })),
        },
      ],
    })),
    totalQuestionCount: 40,
    audioSegments: Array.from({ length: 4 }, (_, i) => ({
      id: `audio-seg-${i + 1}`,
      partId: `listening-part-${i + 1}`,
      durationSeconds: 480,
    })),
  }
}

export function createSeedFullWritingTest(): WritingExercise {
  return {
    id: 'seed-writing-full-test-001',
    schemaVersion: 1,
    blueprintVersion: '1.0.0',
    module: 'writing',
    mode: 'full_test',
    family: 'writing_task',
    title: 'Academic Writing Full Test',
    description: 'Complete IELTS Academic Writing test with Task 1 and Task 2',
    instructions: ['You have 60 minutes to complete both tasks.', 'Task 2 contributes twice as much as Task 1 to your Writing score.'],
    source: 'seed_data',
    status: 'active',
    estimatedDurationSeconds: 3600,
    difficulty: createDefaultDifficultyProfile(),
    learningObjectives: [],
    tags: ['ielts', 'academic', 'full-test'],
    ieltsVariant: 'academic',
    createdAt: NOW,
    updatedAt: NOW,
    tasks: [
      {
        id: 'writing-task-1',
        taskNumber: 1,
        taskType: 'task_1',
        prompt: 'The chart below shows the percentage of households in owned and rented accommodation in England and Wales between 1918 and 2011.',
        instructions: ['Summarise the information by selecting and reporting the main features, and make comparisons where relevant.', 'Write at least 150 words.'],
        recommendedWordCount: { min: 150 },
        recommendedMinutes: 20,
        weight: 1,
        rubric: [
          { id: 'wr-ta', name: 'Task Achievement', description: 'How well the response addresses the task', maxScore: 9 },
          { id: 'wr-cc', name: 'Coherence and Cohesion', description: 'Organization and linking', maxScore: 9 },
          { id: 'wr-lr', name: 'Lexical Resource', description: 'Range and accuracy of vocabulary', maxScore: 9 },
          { id: 'wr-gr', name: 'Grammatical Range and Accuracy', description: 'Range and accuracy of grammar', maxScore: 9 },
        ],
      },
      {
        id: 'writing-task-2',
        taskNumber: 2,
        taskType: 'task_2',
        prompt: 'Some people believe that technology has made our lives more complex. To what extent do you agree or disagree?',
        instructions: ['Give reasons for your answer and include any relevant examples from your own knowledge or experience.', 'Write at least 250 words.'],
        recommendedWordCount: { min: 250 },
        recommendedMinutes: 40,
        weight: 2,
        rubric: [
          { id: 'wr-tr', name: 'Task Response', description: 'How well the response addresses the task', maxScore: 9 },
          { id: 'wr-cc', name: 'Coherence and Cohesion', description: 'Organization and linking', maxScore: 9 },
          { id: 'wr-lr', name: 'Lexical Resource', description: 'Range and accuracy of vocabulary', maxScore: 9 },
          { id: 'wr-gr', name: 'Grammatical Range and Accuracy', description: 'Range and accuracy of grammar', maxScore: 9 },
        ],
      },
    ],
  }
}

export function createSeedFullSpeakingSimulation(): SpeakingExercise {
  return {
    id: 'seed-speaking-full-test-001',
    schemaVersion: 1,
    blueprintVersion: '1.0.0',
    module: 'speaking',
    mode: 'full_test',
    family: 'speaking_session',
    title: 'IELTS Speaking Full Simulation',
    description: 'Complete IELTS Speaking simulation with 3 parts',
    instructions: ['This is a simulation of the IELTS Speaking test.', 'The examiner will ask you questions.'],
    source: 'seed_data',
    status: 'active',
    estimatedDurationSeconds: 840,
    difficulty: createDefaultDifficultyProfile(),
    learningObjectives: [],
    tags: ['ielts', 'full-test'],
    createdAt: NOW,
    updatedAt: NOW,
    parts: [
      {
        id: 'speaking-part-1',
        partNumber: 1,
        description: 'Introduction and Interview',
        prompts: ['Tell me about your hometown.', 'Do you work or study?', 'What do you like about your daily routine?'],
        preparationSeconds: 0,
        responseSeconds: 300,
        examinerScript: "Good afternoon. My name is [examiner]. Can you tell me your full name please?",
      },
      {
        id: 'speaking-part-2',
        partNumber: 2,
        description: 'Long Turn',
        prompts: ['Describe a book that had a major influence on you. You should say: what the book was, when you read it, what it was about, and explain how it influenced you.'],
        preparationSeconds: 60,
        responseSeconds: 120,
      },
      {
        id: 'speaking-part-3',
        partNumber: 3,
        description: 'Two-way Discussion',
        prompts: ['How do you think reading habits have changed in recent years?', 'Do you think printed books will eventually disappear?', 'What role do libraries play in modern society?'],
        preparationSeconds: 0,
        responseSeconds: 300,
      },
    ],
    totalDurationSeconds: 840,
  }
}

export function createSeedGrammarExercise(): GrammarExercise {
  return {
    id: 'seed-grammar-conditionals-001',
    schemaVersion: 1,
    blueprintVersion: '1.0.0',
    module: 'grammar',
    mode: 'focused_practice',
    family: 'grammar_activity',
    title: 'Grammar: Conditionals',
    description: 'Practice conditional sentences (zero, first, second, third)',
    instructions: ['Choose the correct option to complete each sentence.'],
    source: 'seed_data',
    status: 'active',
    estimatedDurationSeconds: 600,
    difficulty: createDefaultDifficultyProfile(),
    learningObjectives: [{ id: 'obj-conditionals', name: 'Conditional Sentences' }],
    tags: ['grammar', 'conditionals'],
    createdAt: NOW,
    updatedAt: NOW,
    grammarType: 'multiple_choice',
    items: [
      {
        id: 'grammar-item-1',
        grammarConcept: 'first_conditional',
        question: {
          id: 'gq-1',
          type: 'multiple_choice',
          prompt: 'If it _____ tomorrow, we will cancel the picnic.',
          options: ['rains', 'will rain', 'rained', 'would rain'],
          correctIndex: 0,
          points: 1,
          difficulty: { difficulty: 0.4 },
          learningObjectiveIds: ['obj-conditionals'],
        },
        acceptedVariants: ['rains'],
        autoScoringReliable: true,
      },
      {
        id: 'grammar-item-2',
        grammarConcept: 'second_conditional',
        question: {
          id: 'gq-2',
          type: 'multiple_choice',
          prompt: 'If I _____ more time, I would learn another language.',
          options: ['have', 'had', 'will have', 'would have'],
          correctIndex: 1,
          points: 1,
          difficulty: { difficulty: 0.5 },
          learningObjectiveIds: ['obj-conditionals'],
        },
        acceptedVariants: ['had'],
        autoScoringReliable: true,
      },
      {
        id: 'grammar-item-3',
        grammarConcept: 'third_conditional',
        question: {
          id: 'gq-3',
          type: 'multiple_choice',
          prompt: 'If she _____ earlier, she would have caught the train.',
          options: ['left', 'had left', 'would leave', 'has left'],
          correctIndex: 1,
          points: 1,
          difficulty: { difficulty: 0.6 },
          learningObjectiveIds: ['obj-conditionals'],
        },
        acceptedVariants: ['had left'],
        autoScoringReliable: true,
      },
    ],
  }
}

export function createSeedVocabularyExercise(): VocabularyExercise {
  return {
    id: 'seed-vocabulary-collocations-001',
    schemaVersion: 1,
    blueprintVersion: '1.0.0',
    module: 'vocabulary',
    mode: 'focused_practice',
    family: 'vocabulary_activity',
    title: 'Vocabulary: Academic Collocations',
    description: 'Practice common academic collocations',
    instructions: ['Match each word with its most common collocation partner.'],
    source: 'seed_data',
    status: 'active',
    estimatedDurationSeconds: 450,
    difficulty: createDefaultDifficultyProfile(),
    learningObjectives: [{ id: 'obj-collocations', name: 'Academic Collocations' }],
    tags: ['vocabulary', 'collocations'],
    createdAt: NOW,
    updatedAt: NOW,
    vocabularyType: 'collocation_matching',
    terms: [
      { id: 'term-1', lemma: 'conduct', partOfSpeech: 'verb', meaning: 'to carry out', collocations: ['research', 'study', 'experiment'], wordFamily: ['conductor', 'conduction'], acceptedForms: ['conduct', 'conducts', 'conducted', 'conducting'] },
      { id: 'term-2', lemma: 'significant', partOfSpeech: 'adjective', meaning: 'important or notable', collocations: ['impact', 'difference', 'role'], wordFamily: ['significance', 'significantly'], acceptedForms: ['significant'] },
      { id: 'term-3', lemma: 'evidence', partOfSpeech: 'noun', meaning: 'information indicating whether something is true', collocations: ['suggest', 'show', 'provide'], wordFamily: ['evident', 'evidently'], acceptedForms: ['evidence'] },
    ],
    activities: [
      {
        id: 'vocab-activity-1',
        type: 'matching',
        instructions: ['Match each word with its collocation partner.'],
        questions: [
          {
            id: 'vq-1',
            type: 'matching',
            subtype: 'general_matching',
            prompt: 'Match collocations',
            leftItems: [{ id: 'left-1', content: 'conduct' }, { id: 'left-2', content: 'significant' }, { id: 'left-3', content: 'evidence' }],
            rightItems: [{ id: 'right-1', content: 'research' }, { id: 'right-2', content: 'impact' }, { id: 'right-3', content: 'suggest' }],
            correctMatches: { 'left-1': 'right-1', 'left-2': 'right-2', 'left-3': 'right-3' },
            points: 3,
            difficulty: { difficulty: 0.5 },
            learningObjectiveIds: ['obj-collocations'],
          },
        ],
      },
    ],
  }
}

export function createSeedSavedContentExercise(): SavedContentExercise {
  return {
    id: 'seed-saved-content-001',
    schemaVersion: 1,
    blueprintVersion: '1.0.0',
    module: 'saved_content',
    mode: 'focused_practice',
    family: 'content_comprehension',
    title: 'Comprehension: The Future of Remote Work',
    instructions: ['Read the article and answer the comprehension questions.'],
    source: 'seed_data',
    status: 'active',
    estimatedDurationSeconds: 900,
    difficulty: createDefaultDifficultyProfile(),
    learningObjectives: [],
    tags: ['reading', 'comprehension'],
    createdAt: NOW,
    updatedAt: NOW,
    contentReference: {
      contentId: 'content-001',
      contentType: 'article',
      title: 'The Future of Remote Work',
      excerpt: 'Remote work has transformed how millions of people approach their careers...',
    },
    activities: [
      {
        id: 'sc-activity-1',
        type: 'multiple_choice',
        instructions: ['Choose the correct answer based on the article.'],
        questions: [
          {
            id: 'scq-1',
            type: 'multiple_choice',
            prompt: 'According to the article, what is the main benefit of remote work?',
            options: ['Higher salary', 'Better work-life balance', 'More meetings', 'Less technology'],
            correctIndex: 1,
            points: 1,
            difficulty: { difficulty: 0.4 },
            learningObjectiveIds: [],
          },
          {
            id: 'scq-2',
            type: 'short_answer',
            prompt: 'What percentage of workers surveyed preferred hybrid work?',
            correctAnswer: '65',
            acceptableAlternatives: ['65%', 'sixty-five', 'sixty five percent'],
            caseSensitive: false,
            points: 1,
            difficulty: { difficulty: 0.5 },
            learningObjectiveIds: [],
          },
        ],
      },
    ],
  }
}

export function createSeedMistakeReviewExercise(): MistakeReviewExercise {
  return {
    id: 'seed-mistake-review-001',
    schemaVersion: 1,
    blueprintVersion: '1.0.0',
    module: 'mistake_review',
    mode: 'review',
    family: 'review_activity',
    title: 'Mistake Review: Reading Comprehension',
    instructions: ['Review your previous mistakes and try similar questions.'],
    source: 'seed_data',
    status: 'active',
    estimatedDurationSeconds: 600,
    difficulty: createDefaultDifficultyProfile(),
    learningObjectives: [],
    tags: ['review'],
    createdAt: NOW,
    updatedAt: NOW,
    mistakes: [
      {
        sourceExerciseId: 'seed-reading-full-test-001',
        sourceAttemptId: 'attempt-001',
        itemId: 'q-rt-p1-3',
        module: 'reading',
        errorType: 'true_false_not_given_confusion',
        learnerAnswer: 'true',
        expectedAnswer: 'not_given',
        explanation: 'The passage does not provide enough information to determine if this statement is true or false.',
        occurredAt: NOW,
      },
    ],
    reviewActivities: [
      {
        id: 'review-activity-1',
        type: 'true_false_not_given',
        instructions: ['Decide if the statements are True, False, or Not Given based on the passage.'],
        questions: [
          {
            id: 'rev-q-1',
            type: 'true_false_not_given',
            prompt: 'The government invested $2 billion in urban farming initiatives in 2020.',
            statement: 'The government invested $2 billion in urban farming initiatives in 2020.',
            correctAnswer: 'not_given',
            referenceText: 'Urban farming has grown significantly, though government funding details are not specified.',
            points: 1,
            difficulty: { difficulty: 0.6 },
            learningObjectiveIds: [],
            explanation: 'The passage mentions growth but does not specify government investment amounts.',
          },
        ],
      },
    ],
  }
}

export function getAllSeedExercises(): Exercise[] {
  return [
    createSeedFullReadingTest(),
    createSeedFullListeningTest(),
    createSeedFullWritingTest(),
    createSeedFullSpeakingSimulation(),
    createSeedGrammarExercise(),
    createSeedVocabularyExercise(),
    createSeedSavedContentExercise(),
    createSeedMistakeReviewExercise(),
  ]
}
