import { describe, it, expect, beforeEach } from 'vitest'
import { ProactiveMessageStorage } from '../services/proactiveMessageStorage'
import {
  DEFAULT_PROACTIVE_SETTINGS,
  proactiveMessageSchema,
  proactiveMessageSettingsSchema,
} from '../types/proactiveMessage'
import type {
  ProactiveMessage,
  ProactiveMessageInput,
  ProactiveMessageSettings,
} from '../types/proactiveMessage'

beforeEach(() => {
  localStorage.clear()
})

function sampleInput(overrides: Partial<ProactiveMessageInput> = {}): ProactiveMessageInput {
  return {
    triggerType: 'due_review',
    category: 'vocabulary-review',
    title: 'Test Message',
    message: 'This is a test proactive message.',
    priority: 'medium',
    autoGenerated: false,
    ...overrides,
  }
}

function createSampleMessage(overrides: Partial<ProactiveMessageInput> = {}): ProactiveMessage {
  return ProactiveMessageStorage.addMessage(sampleInput(overrides))
}

// ─── Settings ────────────────────────────────────────────────────────────────

describe('ProactiveMessageStorage — Settings', () => {
  it('returns default settings when none stored', () => {
    const settings = ProactiveMessageStorage.loadSettings()
    expect(settings).toMatchObject({
      enabled: true,
      tone: 'friendly',
      maxMessagesPerDay: 5,
    })
  })

  it('saves and loads custom settings', () => {
    const custom: ProactiveMessageSettings = {
      ...DEFAULT_PROACTIVE_SETTINGS,
      enabled: false,
      tone: 'strict',
      maxMessagesPerDay: 10,
    }
    ProactiveMessageStorage.saveSettings(custom)
    const loaded = ProactiveMessageStorage.loadSettings()
    expect(loaded.enabled).toBe(false)
    expect(loaded.tone).toBe('strict')
    expect(loaded.maxMessagesPerDay).toBe(10)
  })

  it('resets settings to defaults', () => {
    ProactiveMessageStorage.saveSettings({
      ...DEFAULT_PROACTIVE_SETTINGS,
      enabled: false,
    })
    const reset = ProactiveMessageStorage.resetSettings()
    expect(reset.enabled).toBe(true)
    expect(ProactiveMessageStorage.loadSettings().enabled).toBe(true)
  })

  it('returns defaults via getDefaultSettings', () => {
    const defaults = ProactiveMessageStorage.getDefaultSettings()
    expect(defaults).toEqual(DEFAULT_PROACTIVE_SETTINGS)
  })

  it('validates settings against schema on save', () => {
    const spy = vi.spyOn(console, 'warn').mockImplementation(() => {})
    ProactiveMessageStorage.saveSettings({
      ...DEFAULT_PROACTIVE_SETTINGS,
      tone: 'invalid-tone' as never,
    })
    expect(spy).toHaveBeenCalled()
    spy.mockRestore()
  })
})

// ─── CRUD ────────────────────────────────────────────────────────────────────

describe('ProactiveMessageStorage — CRUD', () => {
  it('starts with empty messages', () => {
    expect(ProactiveMessageStorage.loadMessages()).toEqual([])
  })

  it('adds a message and returns it with id and createdAt', () => {
    const msg = ProactiveMessageStorage.addMessage(sampleInput())
    expect(msg.id).toBeTruthy()
    expect(msg.title).toBe('Test Message')
    expect(msg.createdAt).toBeTruthy()
    expect(msg.isRead).toBe(false)
    expect(msg.isDismissed).toBe(false)
    expect(msg.isSnoozed).toBe(false)
    expect(msg.autoGenerated).toBe(false)
  })

  it('persists messages in localStorage', () => {
    const msg = createSampleMessage()
    const loaded = ProactiveMessageStorage.loadMessages()
    expect(loaded).toHaveLength(1)
    expect(loaded[0].id).toBe(msg.id)
  })

  it('gets a message by id', () => {
    const msg = createSampleMessage()
    const found = ProactiveMessageStorage.getMessage(msg.id)
    expect(found).toBeDefined()
    expect(found!.title).toBe('Test Message')
  })

  it('returns undefined for unknown id', () => {
    expect(ProactiveMessageStorage.getMessage('nonexistent')).toBeUndefined()
  })

  it('updates a message', () => {
    const msg = createSampleMessage()
    const updated = ProactiveMessageStorage.updateMessage(msg.id, { isRead: true })
    expect(updated).toBeDefined()
    expect(updated!.isRead).toBe(true)
    expect(updated!.readAt).toBeTruthy()
  })

  it('returns undefined when updating nonexistent message', () => {
    const result = ProactiveMessageStorage.updateMessage('nonexistent', { isRead: true })
    expect(result).toBeUndefined()
  })

  it('deletes a message', () => {
    const msg = createSampleMessage()
    const deleted = ProactiveMessageStorage.deleteMessage(msg.id)
    expect(deleted).toBe(true)
    expect(ProactiveMessageStorage.loadMessages()).toHaveLength(0)
  })

  it('returns false when deleting nonexistent message', () => {
    expect(ProactiveMessageStorage.deleteMessage('nonexistent')).toBe(false)
  })

  it('clearMessages removes all messages', () => {
    createSampleMessage()
    createSampleMessage({ title: 'Second' })
    ProactiveMessageStorage.clearMessages()
    expect(ProactiveMessageStorage.loadMessages()).toEqual([])
  })
})

// ─── Queries ─────────────────────────────────────────────────────────────────

describe('ProactiveMessageStorage — Queries', () => {
  it('getUnreadCount returns correct count', () => {
    expect(ProactiveMessageStorage.getUnreadCount()).toBe(0)
    createSampleMessage()
    expect(ProactiveMessageStorage.getUnreadCount()).toBe(1)
    const msg2 = createSampleMessage()
    ProactiveMessageStorage.markAsRead(msg2.id)
    expect(ProactiveMessageStorage.getUnreadCount()).toBe(1)
  })

  it('getMessagesByStatus filters correctly', () => {
    const msg1 = createSampleMessage({ title: 'Unread' })
    const msg2 = createSampleMessage({ title: 'Read' })
    ProactiveMessageStorage.markAsRead(msg2.id)
    const unread = ProactiveMessageStorage.getMessagesByStatus({ isRead: false })
    expect(unread).toHaveLength(1)
    expect(unread[0].id).toBe(msg1.id)
  })

  it('getMessagesByTriggerType filters correctly', () => {
    createSampleMessage({ triggerType: 'due_review' })
    createSampleMessage({ triggerType: 'study_streak', title: 'Streak' })
    const dueMessages = ProactiveMessageStorage.getMessagesByTriggerType('due_review')
    expect(dueMessages).toHaveLength(1)
    expect(dueMessages[0].triggerType).toBe('due_review')
  })

  it('getMessagesByDateRange filters correctly', () => {
    const msg = createSampleMessage()
    const result = ProactiveMessageStorage.getMessagesByDateRange(
      new Date(Date.now() - 86400000).toISOString(),
      new Date(Date.now() + 86400000).toISOString(),
    )
    expect(result).toHaveLength(1)
    expect(result[0].id).toBe(msg.id)
  })

  it('getTodayMessages returns today messages only', () => {
    createSampleMessage()
    const today = ProactiveMessageStorage.getTodayMessages()
    expect(today).toHaveLength(1)
  })

  it('getPendingMessages excludes dismissed, read, snoozed, expired', () => {
    const msg1 = createSampleMessage({ title: 'Pending' })
    const msg2 = createSampleMessage({ title: 'Dismissed' })
    const msg3 = createSampleMessage({ title: 'Read' })
    const msg4 = createSampleMessage({ title: 'Snoozed' })
    const msg5 = createSampleMessage({
      title: 'Expired',
      expiresAt: new Date(Date.now() - 86400000).toISOString(),
    })
    ProactiveMessageStorage.markAsDismissed(msg2.id)
    ProactiveMessageStorage.markAsRead(msg3.id)
    ProactiveMessageStorage.markAsSnoozed(msg4.id, new Date(Date.now() + 86400000).toISOString())
    const pending = ProactiveMessageStorage.getPendingMessages()
    expect(pending).toHaveLength(1)
    expect(pending[0].id).toBe(msg1.id)
  })

  it('getExpiredMessages returns expired messages', () => {
    createSampleMessage({ expiresAt: new Date(Date.now() - 86400000).toISOString() })
    createSampleMessage()
    const expired = ProactiveMessageStorage.getExpiredMessages()
    expect(expired).toHaveLength(1)
  })
})

// ─── Mark shortcuts ──────────────────────────────────────────────────────────

describe('ProactiveMessageStorage — Mark shortcuts', () => {
  it('markAsRead sets isRead and readAt', () => {
    const msg = createSampleMessage()
    const updated = ProactiveMessageStorage.markAsRead(msg.id)
    expect(updated!.isRead).toBe(true)
    expect(updated!.readAt).toBeTruthy()
  })

  it('markAsDismissed sets isDismissed and dismissedAt', () => {
    const msg = createSampleMessage()
    const updated = ProactiveMessageStorage.markAsDismissed(msg.id)
    expect(updated!.isDismissed).toBe(true)
    expect(updated!.dismissedAt).toBeTruthy()
  })

  it('markAsSnoozed sets isSnoozed and snoozedUntil', () => {
    const msg = createSampleMessage()
    const until = new Date(Date.now() + 86400000).toISOString()
    const updated = ProactiveMessageStorage.markAsSnoozed(msg.id, until)
    expect(updated!.isSnoozed).toBe(true)
    expect(updated!.snoozedUntil).toBe(until)
  })

  it('markAllAsRead marks all unread messages', () => {
    createSampleMessage()
    createSampleMessage()
    ProactiveMessageStorage.markAllAsRead()
    expect(ProactiveMessageStorage.getUnreadCount()).toBe(0)
  })
})

// ─── Cleanup ─────────────────────────────────────────────────────────────────

describe('ProactiveMessageStorage — Cleanup', () => {
  it('cleanup removes oldest messages beyond limit', () => {
    for (let i = 0; i < 10; i++) {
      createSampleMessage({ title: `Msg ${i}` })
    }
    const removed = ProactiveMessageStorage.cleanup(5)
    expect(removed).toBe(5)
    expect(ProactiveMessageStorage.loadMessages()).toHaveLength(5)
  })

  it('cleanup does nothing when under limit', () => {
    createSampleMessage()
    const removed = ProactiveMessageStorage.cleanup(5)
    expect(removed).toBe(0)
    expect(ProactiveMessageStorage.loadMessages()).toHaveLength(1)
  })

  it('clearExpired removes only expired messages', () => {
    createSampleMessage({ expiresAt: new Date(Date.now() - 86400000).toISOString() })
    createSampleMessage()
    const removed = ProactiveMessageStorage.clearExpired()
    expect(removed).toBe(1)
    expect(ProactiveMessageStorage.loadMessages()).toHaveLength(1)
  })

  it('clearExpired returns 0 when none expired', () => {
    createSampleMessage()
    const removed = ProactiveMessageStorage.clearExpired()
    expect(removed).toBe(0)
  })
})

// ─── Export / Import ─────────────────────────────────────────────────────────

describe('ProactiveMessageStorage — Export/Import', () => {
  it('exportToJson produces valid JSON with messages and settings', () => {
    createSampleMessage()
    const json = ProactiveMessageStorage.exportToJson()
    const parsed = JSON.parse(json)
    expect(parsed.version).toBe(2)
    expect(parsed.messages).toHaveLength(1)
    expect(parsed.settings).toBeDefined()
    expect(parsed.exportedAt).toBeTruthy()
  })

  it('importFromJson restores messages and settings', () => {
    ProactiveMessageStorage.saveSettings({
      ...DEFAULT_PROACTIVE_SETTINGS,
      tone: 'motivational',
    })
    createSampleMessage()
    const json = ProactiveMessageStorage.exportToJson()
    ProactiveMessageStorage.clearMessages()
    ProactiveMessageStorage.resetSettings()
    const result = ProactiveMessageStorage.importFromJson(json)
    expect(result.success).toBe(true)
    expect(result.messagesImported).toBe(1)
    expect(ProactiveMessageStorage.loadMessages()).toHaveLength(1)
    expect(ProactiveMessageStorage.loadSettings().tone).toBe('motivational')
  })

  it('importFromJson handles invalid JSON gracefully', () => {
    const result = ProactiveMessageStorage.importFromJson('not json')
    expect(result.success).toBe(false)
    expect(result.error).toBe('Invalid JSON')
    expect(result.messagesImported).toBe(0)
  })

  it('importFromJson handles missing messages gracefully', () => {
    const result = ProactiveMessageStorage.importFromJson('{"settings":{}}')
    expect(result.success).toBe(true)
    expect(result.messagesImported).toBe(0)
  })
})

// ─── Schema validation ───────────────────────────────────────────────────────

describe('Schema validation', () => {
  it('proactiveMessageSchema validates a correct message', () => {
    const result = proactiveMessageSchema.safeParse({
      id: 'test-id',
      triggerType: 'due_review',
      category: 'vocabulary-review',
      title: 'Test',
      message: 'Test message',
      priority: 'medium',
      isRead: false,
      isDismissed: false,
      isSnoozed: false,
      autoGenerated: false,
      createdAt: new Date().toISOString(),
    })
    expect(result.success).toBe(true)
  })

  it('proactiveMessageSchema rejects invalid priority', () => {
    const result = proactiveMessageSchema.safeParse({
      id: 'test-id',
      triggerType: 'due_review',
      category: 'vocabulary-review',
      title: 'Test',
      message: 'Test message',
      priority: 'urgent',
      isRead: false,
      isDismissed: false,
      isSnoozed: false,
      autoGenerated: false,
      createdAt: new Date().toISOString(),
    })
    expect(result.success).toBe(false)
  })

  it('proactiveMessageSettingsSchema validates correct settings', () => {
    const result = proactiveMessageSettingsSchema.safeParse(DEFAULT_PROACTIVE_SETTINGS)
    expect(result.success).toBe(true)
  })

  it('proactiveMessageSettingsSchema rejects invalid tone', () => {
    const result = proactiveMessageSettingsSchema.safeParse({
      ...DEFAULT_PROACTIVE_SETTINGS,
      tone: 'angry',
    })
    expect(result.success).toBe(false)
  })
})

// ─── Edge cases ──────────────────────────────────────────────────────────────

describe('ProactiveMessageStorage — Edge cases', () => {
  it('handles localStorage being full gracefully', () => {
    const setItem = vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => {
      throw new Error('QuotaExceededError')
    })
    const spy = vi.spyOn(console, 'warn').mockImplementation(() => {})
    const msg = ProactiveMessageStorage.addMessage(sampleInput({ title: 'Should fail silently' }))
    setItem.mockRestore()
    spy.mockRestore()
    expect(msg.id).toBeTruthy()
  })

  it('handles message with all optional fields', () => {
    const input = sampleInput()
    const msg = ProactiveMessageStorage.addMessage(input)
    const result = proactiveMessageSchema.safeParse(msg)
    expect(result.success).toBe(true)
  })

  it('addMessage throws for invalid input', () => {
    const spy = vi.spyOn(console, 'warn').mockImplementation(() => {})
    expect(() =>
      ProactiveMessageStorage.addMessage({
        triggerType: 'due_review',
        category: 'vocabulary-review',
        title: '',
        message: '',
        priority: 'medium',
        autoGenerated: false,
      }),
    ).toThrow('Failed to create proactive message: invalid data')
    spy.mockRestore()
  })
})
