import { describe, it, expect, beforeEach } from 'vitest'
import {
  ProactiveMessageInteraction,
  DEFAULT_SNOOZE_DURATION_MS,
  SNOOZE_PRESETS,
  FEEDBACK_DISMISS_REASONS,
} from '../services/proactiveMessageInteraction'
import { ProactiveMessageStorage } from '../services/proactiveMessageStorage'
import { DEFAULT_PROACTIVE_SETTINGS } from '../types/proactiveMessage'
import type {
  ProactiveMessage,
  ProactiveMessageInput,
  ProactiveMessageSettings,
  InteractionRecord,
} from '../types/proactiveMessage'

beforeEach(() => {
  localStorage.clear()
})

function sampleInput(overrides: Partial<ProactiveMessageInput> = {}): ProactiveMessageInput {
  return {
    triggerType: 'due_review',
    category: 'vocabulary-review',
    title: 'Test Message',
    message: 'This is a test proactive message.',
    priority: 'medium',
    autoGenerated: false,
    ...overrides,
  }
}

function createSampleMessage(
  overrides: Partial<ProactiveMessageInput> = {},
): ProactiveMessage {
  return ProactiveMessageStorage.addMessage(sampleInput(overrides))
}

function createMessages(count: number): ProactiveMessage[] {
  const ids: string[] = []
  for (let i = 0; i < count; i++) {
    const msg = createSampleMessage({ title: `Message ${i}` })
    ids.push(msg.id)
  }
  return ProactiveMessageStorage.loadMessages()
}

// ─── dismissMessage ──────────────────────────────────────────────────────────

describe('ProactiveMessageInteraction — dismissMessage', () => {
  it('dismisses a message and sets isDismissed', () => {
    const msg = createSampleMessage()
    const result = ProactiveMessageInteraction.dismissMessage(msg.id)
    expect(result.success).toBe(true)
    expect(result.message).toBeDefined()
    expect(result.message!.isDismissed).toBe(true)
    expect(result.message!.dismissedAt).toBeTruthy()
    expect(result.interaction.type).toBe('dismiss')
  })

  it('records dismiss reason', () => {
    const msg = createSampleMessage()
    const result = ProactiveMessageInteraction.dismissMessage(msg.id, 'not-now')
    expect(result.success).toBe(true)
    expect(result.message!.dismissReason).toBe('not-now')
    expect(result.interaction.detail).toBe('not-now')
  })

  it('appends interaction to history', () => {
    const msg = createSampleMessage()
    ProactiveMessageInteraction.dismissMessage(msg.id, 'not-relevant')
    const loaded = ProactiveMessageStorage.getMessage(msg.id)
    expect(loaded!.interactionHistory).toHaveLength(1)
    expect(loaded!.interactionHistory![0].type).toBe('dismiss')
    expect(loaded!.lastInteractedAt).toBeTruthy()
  })

  it('returns success=false for nonexistent message', () => {
    const result = ProactiveMessageInteraction.dismissMessage('nonexistent')
    expect(result.success).toBe(false)
    expect(result.message).toBeUndefined()
  })

  it('passes metadata through to interaction record', () => {
    const msg = createSampleMessage()
    const result = ProactiveMessageInteraction.dismissMessage(msg.id, 'other', {
      source: 'dashboard',
      userId: 'user1',
    })
    expect(result.interaction.metadata).toEqual({
      source: 'dashboard',
      userId: 'user1',
    })
  })
})

// ─── snoozeMessage ───────────────────────────────────────────────────────────

describe('ProactiveMessageInteraction — snoozeMessage', () => {
  it('snoozes a message with default duration', () => {
    const msg = createSampleMessage()
    const result = ProactiveMessageInteraction.snoozeMessage(msg.id)
    expect(result.success).toBe(true)
    expect(result.message!.isSnoozed).toBe(true)
    expect(result.message!.snoozedUntil).toBeTruthy()
    expect(result.interaction.type).toBe('snooze')
    expect(result.interaction.detail).toBe('duration:3600000')
  })

  it('snoozes a message with custom duration', () => {
    const msg = createSampleMessage()
    const threeHours = 3 * 60 * 60 * 1000
    const result = ProactiveMessageInteraction.snoozeMessage(msg.id, threeHours)
    const expectedUntil = new Date(Date.now() + threeHours).getTime()
    const actualUntil = new Date(result.message!.snoozedUntil!).getTime()
    expect(Math.abs(actualUntil - expectedUntil)).toBeLessThan(100)
    expect(result.interaction.detail).toBe('duration:10800000')
  })

  it('appends interaction to history', () => {
    const msg = createSampleMessage()
    ProactiveMessageInteraction.snoozeMessage(msg.id)
    const loaded = ProactiveMessageStorage.getMessage(msg.id)
    expect(loaded!.interactionHistory).toHaveLength(1)
    expect(loaded!.interactionHistory![0].type).toBe('snooze')
    expect(loaded!.lastInteractedAt).toBeTruthy()
  })

  it('returns success=false for nonexistent message', () => {
    const result = ProactiveMessageInteraction.snoozeMessage('nonexistent')
    expect(result.success).toBe(false)
    expect(result.message).toBeUndefined()
  })
})

// ─── handleActionClick ───────────────────────────────────────────────────────

describe('ProactiveMessageInteraction — handleActionClick', () => {
  it('records action click and marks as read', () => {
    const msg = createSampleMessage()
    const result = ProactiveMessageInteraction.handleActionClick(msg.id, 'quiz-me')
    expect(result.success).toBe(true)
    expect(result.message!.isRead).toBe(true)
    expect(result.message!.readAt).toBeTruthy()
    expect(result.message!.actionClicked).toBe('quiz-me')
    expect(result.interaction.type).toBe('action_click')
    expect(result.interaction.detail).toBe('quiz-me')
  })

  it('appends interaction to history', () => {
    const msg = createSampleMessage()
    ProactiveMessageInteraction.handleActionClick(msg.id, 'practice-with-me')
    const loaded = ProactiveMessageStorage.getMessage(msg.id)
    expect(loaded!.interactionHistory).toHaveLength(1)
    expect(loaded!.interactionHistory![0].type).toBe('action_click')
    expect(loaded!.lastInteractedAt).toBeTruthy()
  })

  it('returns success=false for nonexistent message', () => {
    const result = ProactiveMessageInteraction.handleActionClick('nonexistent', 'quiz-me')
    expect(result.success).toBe(false)
    expect(result.message).toBeUndefined()
  })
})

// ─── provideFeedback ─────────────────────────────────────────────────────────

describe('ProactiveMessageInteraction — provideFeedback', () => {
  it('records helpful feedback', () => {
    const msg = createSampleMessage()
    const result = ProactiveMessageInteraction.provideFeedback(msg.id, 'helpful')
    expect(result.success).toBe(true)
    expect(result.message!.feedback).toBe('helpful')
    expect(result.interaction.type).toBe('feedback')
    expect(result.interaction.detail).toBe('helpful')
  })

  it('records not-helpful feedback', () => {
    const msg = createSampleMessage()
    const result = ProactiveMessageInteraction.provideFeedback(msg.id, 'not-helpful')
    expect(result.success).toBe(true)
    expect(result.message!.feedback).toBe('not-helpful')
  })

  it('appends interaction to history', () => {
    const msg = createSampleMessage()
    ProactiveMessageInteraction.provideFeedback(msg.id, 'helpful', 'Great tip!')
    const loaded = ProactiveMessageStorage.getMessage(msg.id)
    expect(loaded!.interactionHistory).toHaveLength(1)
    expect(loaded!.interactionHistory![0].type).toBe('feedback')
    expect(loaded!.interactionHistory![0].metadata).toEqual({ comment: 'Great tip!' })
    expect(loaded!.lastInteractedAt).toBeTruthy()
  })

  it('returns success=false for nonexistent message', () => {
    const result = ProactiveMessageInteraction.provideFeedback('nonexistent', 'helpful')
    expect(result.success).toBe(false)
    expect(result.message).toBeUndefined()
  })
})

// ─── readAndFeedback ─────────────────────────────────────────────────────────

describe('ProactiveMessageInteraction — readAndFeedback', () => {
  it('marks as read and records feedback in one call', () => {
    const msg = createSampleMessage()
    const result = ProactiveMessageInteraction.readAndFeedback(msg.id, 'helpful', 'Useful reminder')
    expect(result.success).toBe(true)
    const loaded = ProactiveMessageStorage.getMessage(msg.id)
    expect(loaded!.isRead).toBe(true)
    expect(loaded!.readAt).toBeTruthy()
    expect(loaded!.feedback).toBe('helpful')
    expect(loaded!.interactionHistory).toHaveLength(2)
    expect(loaded!.interactionHistory![0].type).toBe('dismiss')
    expect(loaded!.interactionHistory![1].type).toBe('feedback')
    expect(loaded!.interactionHistory![1].metadata).toEqual({ comment: 'Useful reminder' })
    expect(loaded!.lastInteractedAt).toBeTruthy()
  })

  it('returns success=false for nonexistent message', () => {
    const result = ProactiveMessageInteraction.readAndFeedback('nonexistent', 'helpful')
    expect(result.success).toBe(false)
    expect(result.message).toBeUndefined()
  })
})

// ─── Compound interaction history ────────────────────────────────────────────

describe('ProactiveMessageInteraction — compound interactions', () => {
  it('accumulates multiple interactions on the same message', () => {
    const msg = createSampleMessage()
    ProactiveMessageInteraction.handleActionClick(msg.id, 'quiz-me')
    ProactiveMessageInteraction.provideFeedback(msg.id, 'helpful', 'Good exercise')
    const loaded = ProactiveMessageStorage.getMessage(msg.id)
    expect(loaded!.interactionHistory).toHaveLength(2)
    expect(loaded!.interactionHistory![0].type).toBe('action_click')
    expect(loaded!.interactionHistory![0].detail).toBe('quiz-me')
    expect(loaded!.interactionHistory![1].type).toBe('feedback')
    expect(loaded!.interactionHistory![1].detail).toBe('helpful')
  })

  it('dismiss then feedback overwrites feedback', () => {
    const msg = createSampleMessage()
    ProactiveMessageInteraction.dismissMessage(msg.id, 'not-now')
    ProactiveMessageInteraction.provideFeedback(msg.id, 'not-helpful')
    const loaded = ProactiveMessageStorage.getMessage(msg.id)
    expect(loaded!.interactionHistory).toHaveLength(2)
    expect(loaded!.isDismissed).toBe(true)
    expect(loaded!.feedback).toBe('not-helpful')
    expect(loaded!.dismissReason).toBe('not-now')
  })
})

// ─── getInteractionStats ─────────────────────────────────────────────────────

describe('ProactiveMessageInteraction — getInteractionStats', () => {
  it('returns zero stats for empty messages', () => {
    const stats = ProactiveMessageInteraction.getInteractionStats([])
    expect(stats.totalMessages).toBe(0)
    expect(stats.totalDismissed).toBe(0)
    expect(stats.totalSnoozed).toBe(0)
    expect(stats.totalActionClicks).toBe(0)
    expect(stats.totalFeedback).toBe(0)
    expect(stats.interactionRate).toBe(0)
  })

  it('counts dismissed messages', () => {
    const messages = createMessages(5)
    ProactiveMessageInteraction.dismissMessage(messages[0].id, 'not-now')
    ProactiveMessageInteraction.dismissMessage(messages[1].id, 'not-relevant')
    const allMessages = ProactiveMessageStorage.loadMessages()
    const stats = ProactiveMessageInteraction.getInteractionStats(allMessages)
    expect(stats.totalMessages).toBe(5)
    expect(stats.totalDismissed).toBe(2)
    expect(stats.dismissReasonCounts).toEqual({
      'not-now': 1,
      'not-relevant': 1,
    })
  })

  it('counts snoozed messages', () => {
    const messages = createMessages(3)
    ProactiveMessageInteraction.snoozeMessage(messages[0].id)
    const allMessages = ProactiveMessageStorage.loadMessages()
    const stats = ProactiveMessageInteraction.getInteractionStats(allMessages)
    expect(stats.totalSnoozed).toBe(1)
  })

  it('counts action clicks', () => {
    const messages = createMessages(4)
    ProactiveMessageInteraction.handleActionClick(messages[0].id, 'quiz-me')
    ProactiveMessageInteraction.handleActionClick(messages[1].id, 'practice-with-me')
    const allMessages = ProactiveMessageStorage.loadMessages()
    const stats = ProactiveMessageInteraction.getInteractionStats(allMessages)
    expect(stats.totalActionClicks).toBe(2)
    expect(stats.actionClickCounts).toEqual({
      'quiz-me': 1,
      'practice-with-me': 1,
    })
  })

  it('counts feedback ratings', () => {
    const messages = createMessages(3)
    ProactiveMessageInteraction.provideFeedback(messages[0].id, 'helpful')
    ProactiveMessageInteraction.provideFeedback(messages[1].id, 'helpful')
    ProactiveMessageInteraction.provideFeedback(messages[2].id, 'not-helpful')
    const allMessages = ProactiveMessageStorage.loadMessages()
    const stats = ProactiveMessageInteraction.getInteractionStats(allMessages)
    expect(stats.totalFeedback).toBe(3)
    expect(stats.helpfulCount).toBe(2)
    expect(stats.notHelpfulCount).toBe(1)
  })

  it('calculates interaction rate', () => {
    const messages = createMessages(4)
    ProactiveMessageInteraction.dismissMessage(messages[0].id)
    ProactiveMessageInteraction.handleActionClick(messages[1].id, 'quiz-me')
    const allMessages = ProactiveMessageStorage.loadMessages()
    const stats = ProactiveMessageInteraction.getInteractionStats(allMessages)
    expect(stats.totalMessages).toBe(4)
    expect(stats.interactionRate).toBe(0.5)
  })

  it('handles no-reason dismissals', () => {
    const messages = createMessages(1)
    ProactiveMessageInteraction.dismissMessage(messages[0].id)
    const allMessages = ProactiveMessageStorage.loadMessages()
    const stats = ProactiveMessageInteraction.getInteractionStats(allMessages)
    expect(stats.dismissReasonCounts).toEqual({ 'no-reason': 1 })
  })
})

// ─── generateAdjustmentSignals ──────────────────────────────────────────────

describe('ProactiveMessageInteraction — generateAdjustmentSignals', () => {
  const defaultSettings: ProactiveMessageSettings = { ...DEFAULT_PROACTIVE_SETTINGS }

  it('recommends reducing frequency when feedback is poor and frequent dismissals', () => {
    const messages = createMessages(5)
    ProactiveMessageInteraction.dismissMessage(messages[0].id, 'too-frequent')
    ProactiveMessageInteraction.dismissMessage(messages[1].id, 'too-frequent')
    ProactiveMessageInteraction.provideFeedback(messages[0].id, 'not-helpful')
    ProactiveMessageInteraction.provideFeedback(messages[1].id, 'not-helpful')
    ProactiveMessageInteraction.provideFeedback(messages[2].id, 'not-helpful')
    const allMessages = ProactiveMessageStorage.loadMessages()
    const stats = ProactiveMessageInteraction.getInteractionStats(allMessages)
    const signals = ProactiveMessageInteraction.generateAdjustmentSignals(stats, defaultSettings)
    expect(signals.shouldReduceFrequency).toBe(true)
  })

  it('recommends increasing frequency when feedback is consistently positive', () => {
    const messages = createMessages(5)
    ProactiveMessageInteraction.provideFeedback(messages[0].id, 'helpful')
    ProactiveMessageInteraction.provideFeedback(messages[1].id, 'helpful')
    ProactiveMessageInteraction.provideFeedback(messages[2].id, 'helpful')
    const allMessages = ProactiveMessageStorage.loadMessages()
    const stats = ProactiveMessageInteraction.getInteractionStats(allMessages)
    const signals = ProactiveMessageInteraction.generateAdjustmentSignals(stats, defaultSettings)
    expect(signals.shouldIncreaseFrequency).toBe(true)
  })

  it('does not recommend changes with insufficient feedback', () => {
    const messages = createMessages(2)
    ProactiveMessageInteraction.provideFeedback(messages[0].id, 'helpful')
    const allMessages = ProactiveMessageStorage.loadMessages()
    const stats = ProactiveMessageInteraction.getInteractionStats(allMessages)
    const signals = ProactiveMessageInteraction.generateAdjustmentSignals(stats, defaultSettings)
    expect(signals.shouldReduceFrequency).toBe(false)
    expect(signals.shouldIncreaseFrequency).toBe(false)
  })

  it('returns neutral feedback ratio with no feedback', () => {
    const stats = ProactiveMessageInteraction.getInteractionStats([])
    const signals = ProactiveMessageInteraction.generateAdjustmentSignals(stats, defaultSettings)
    expect(signals.feedbackRatio).toBe(0.5)
  })

  it('computes correct feedback ratio', () => {
    const messages = createMessages(5)
    ProactiveMessageInteraction.provideFeedback(messages[0].id, 'helpful')
    ProactiveMessageInteraction.provideFeedback(messages[1].id, 'helpful')
    ProactiveMessageInteraction.provideFeedback(messages[2].id, 'helpful')
    ProactiveMessageInteraction.provideFeedback(messages[3].id, 'not-helpful')
    const allMessages = ProactiveMessageStorage.loadMessages()
    const stats = ProactiveMessageInteraction.getInteractionStats(allMessages)
    const signals = ProactiveMessageInteraction.generateAdjustmentSignals(stats, defaultSettings)
    expect(signals.feedbackRatio).toBe(0.75)
  })

  it('identifies blocked categories from dismiss reasons', () => {
    const messages = createMessages(5)
    ProactiveMessageInteraction.dismissMessage(messages[0].id, 'vocabulary-review')
    ProactiveMessageInteraction.dismissMessage(messages[1].id, 'vocabulary-review')
    const allMessages = ProactiveMessageStorage.loadMessages()
    const stats = ProactiveMessageInteraction.getInteractionStats(allMessages)
    const signals = ProactiveMessageInteraction.generateAdjustmentSignals(stats, defaultSettings)
    expect(signals.blockedCategories.length).toBeGreaterThan(0)
  })

  it('identifies preferred categories from action clicks', () => {
    const messages = createMessages(5)
    ProactiveMessageInteraction.handleActionClick(messages[0].id, 'quiz-me')
    ProactiveMessageInteraction.handleActionClick(messages[1].id, 'quiz-me')
    const allMessages = ProactiveMessageStorage.loadMessages()
    const stats = ProactiveMessageInteraction.getInteractionStats(allMessages)
    const signals = ProactiveMessageInteraction.generateAdjustmentSignals(stats, defaultSettings)
    expect(signals.preferredCategories).toContain('quiz-me')
  })

  it('does not identify preferred from single click', () => {
    const messages = createMessages(2)
    ProactiveMessageInteraction.handleActionClick(messages[0].id, 'quiz-me')
    const allMessages = ProactiveMessageStorage.loadMessages()
    const stats = ProactiveMessageInteraction.getInteractionStats(allMessages)
    const signals = ProactiveMessageInteraction.generateAdjustmentSignals(stats, defaultSettings)
    expect(signals.preferredCategories).not.toContain('quiz-me')
  })
})

// ─── Edge cases ──────────────────────────────────────────────────────────────

describe('ProactiveMessageInteraction — Edge cases', () => {
  it('handles undefined interactionHistory gracefully', () => {
    const msg = createSampleMessage()
    expect(msg.interactionHistory).toBeUndefined()
    ProactiveMessageInteraction.dismissMessage(msg.id)
    const loaded = ProactiveMessageStorage.getMessage(msg.id)
    expect(loaded!.interactionHistory).toBeDefined()
    expect(loaded!.interactionHistory).toHaveLength(1)
  })

  it('preserves existing interaction history when adding new interaction', () => {
    const msg = createSampleMessage()
    ProactiveMessageInteraction.dismissMessage(msg.id, 'not-now')
    ProactiveMessageInteraction.snoozeMessage(msg.id)
    const loaded = ProactiveMessageStorage.getMessage(msg.id)
    expect(loaded!.interactionHistory).toHaveLength(2)
    expect(loaded!.interactionHistory![0].type).toBe('dismiss')
    expect(loaded!.interactionHistory![1].type).toBe('snooze')
  })

  it('allows snooze after dismiss', () => {
    const msg = createSampleMessage()
    ProactiveMessageInteraction.dismissMessage(msg.id)
    const result = ProactiveMessageInteraction.snoozeMessage(msg.id)
    expect(result.success).toBe(true)
    expect(result.message!.isSnoozed).toBe(true)
    expect(result.message!.isDismissed).toBe(true)
  })

  it('allows action click after feedback', () => {
    const msg = createSampleMessage()
    ProactiveMessageInteraction.provideFeedback(msg.id, 'helpful')
    const result = ProactiveMessageInteraction.handleActionClick(msg.id, 'quiz-me')
    expect(result.success).toBe(true)
    expect(result.message!.actionClicked).toBe('quiz-me')
  })
})

// ─── Constants ───────────────────────────────────────────────────────────────

describe('ProactiveMessageInteraction — Constants', () => {
  it('provides snooze presets', () => {
    expect(DEFAULT_SNOOZE_DURATION_MS).toBe(3600000)
    expect(SNOOZE_PRESETS).toHaveLength(5)
    expect(SNOOZE_PRESETS[0].label).toBe('15 minutes')
    expect(SNOOZE_PRESETS[2].label).toBe('3 hours')
    expect(SNOOZE_PRESETS[4].label).toBe('Next week')
    expect(FEEDBACK_DISMISS_REASONS).toContain('not-relevant')
    expect(FEEDBACK_DISMISS_REASONS).toContain('too-frequent')
    expect(FEEDBACK_DISMISS_REASONS).toContain('other')
  })
})
