export { type ExerciseModule, EXERCISE_MODULES, isExerciseModule } from './exercise-module'
export { type ExerciseMode, EXERCISE_MODES, isExerciseMode } from './exercise-mode'
export { type ExerciseFamily, EXERCISE_FAMILIES, isExerciseFamily } from './exercise-family'
export { type IeltsVariant, IELTS_VARIANTS, isIeltsVariant } from './ielts-variant'
export { type ExerciseStatus, type ExerciseSource, type CefrLevel, type LearningObjective } from './common'
export {
  type ExerciseDifficultyProfile,
  type QuestionDifficultyProfile,
  createDefaultDifficultyProfile,
  validateDifficultyProfile,
} from './difficulty'
export {
  type BaseQuestion,
  type AnswerEvidence,
  type MultipleChoiceQuestion,
  type MultipleSelectQuestion,
  type TrueFalseNotGivenQuestion,
  type YesNoNotGivenQuestion,
  type CompletionQuestion,
  type CompletionGap,
  type MatchingQuestion,
  type MatchingItem,
  type OrderingQuestion,
  type OrderingItem,
  type ShortAnswerQuestion,
  type ClassificationQuestion,
  type MapLabellingQuestion,
  type MapLabel,
  type MapPosition,
  type DiagramLabellingQuestion,
  type DiagramLabel,
  type ExerciseQuestion,
  type QuestionGroup,
} from './question'
export {
  type ChoiceResponse,
  type MultiChoiceResponse,
  type TextResponse,
  type MatchingResponse,
  type OrderingResponse,
  type WritingResponse,
  type SpeakingResponse,
  type ClassificationResponse,
  type MapResponse,
  type LearnerResponse,
  type AnswerNormalizationPolicy,
  createDefaultNormalizationPolicy,
  normalizeAnswer,
} from './response'
export {
  type BaseExercise,
  type ReadingPassage,
  type ReadingExercise,
  type ListeningPart,
  type ListeningExercise,
  type AudioSegment,
  type WritingTask,
  type WritingRubricCriterion,
  type WritingExercise,
  type SpeakingPart,
  type SpeakingExercise,
  type GrammarExerciseType,
  type GrammarItem,
  type GrammarExercise,
  type VocabularyExerciseType,
  type VocabularyTerm,
  type SpacedRepetitionMetadata,
  type VocabularyExercise,
  type SavedContentReference,
  type SavedContentExercise,
  type MistakeEvidence,
  type MistakeReviewExercise,
  type Exercise,
} from './exercise'
export {
  type ExerciseAttemptStatus,
  type ExerciseAttempt,
  type ExerciseResult,
  type QuestionResult,
  type QuestionTypeResult,
  type ExerciseFeedback,
  type FeedbackItem,
  type ExerciseMistakeRecord,
  type PerformanceMetric,
  type LearningRecommendation,
  VALID_ATTEMPT_TRANSITIONS,
  isValidTransition,
} from './attempt'
